const monsterfusionDetailed = {
  "Flame Swordsman": {
    "id": "45231177",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Flame Swordsman",
    "atk": 1800,
    "def": 1600,
    "level": 5,
    "type": "Warrior",
    "attribute": "FIRE",
    "effect": "\"Flame Manipulator\" + \"Masaki the Legendary Swordsman\"",
    "category": []
  },
  "Charubin the Fire Knight": {
    "id": "37421579",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Charubin the Fire Knight",
    "atk": 1100,
    "def": 800,
    "level": 3,
    "type": "Pyro",
    "attribute": "FIRE",
    "effect": "\"\"Monster Egg\" + \"Hinotama Soul\"",
    "category": []
  },
  "Darkfire Dragon": {
    "id": "17881964",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Darkfire Dragon",
    "atk": 1500,
    "def": 1250,
    "level": 4,
    "type": "Dragon",
    "attribute": "DARK",
    "effect": "\"Firegrass\" + \"Petit Dragon\"",
    "category": []
  },
  "Fusionist": {
    "id": "01641882",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Fusionist",
    "atk": 900,
    "def": 700,
    "level": 3,
    "type": "Beast",
    "attribute": "EARTH",
    "effect": "\"Petit Angel\" + \"Mystical Sheep #2\"",
    "category": []
  },
  "Flame Ghost": {
    "id": "58528964",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Flame Ghost",
    "atk": 1000,
    "def": 800,
    "level": 3,
    "type": "Zombie",
    "attribute": "DARK",
    "effect": "\"Skull Servant\" + \"Dissolverock\"",
    "category": []
  },
  "Karbonala Warrior": {
    "id": "54541900",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Karbonala Warrior",
    "atk": 1500,
    "def": 1200,
    "level": 4,
    "type": "Warrior",
    "attribute": "EARTH",
    "effect": "\"M-Warrior #1\" + \"M-Warrior #2\"",
    "category": []
  },
  "Dragoness the Wicked Knight": {
    "id": "70681994",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dragoness the Wicked Knight",
    "atk": 1200,
    "def": 900,
    "level": 3,
    "type": "Warrior",
    "attribute": "WIND",
    "effect": "\"Armaill\" + \"One-Eyed Shield Dragon\"",
    "category": []
  },
  "Metal Dragon": {
    "id": "09293977",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Metal Dragon",
    "atk": 1850,
    "def": 1700,
    "level": 6,
    "type": "Machine",
    "attribute": "WIND",
    "effect": "\"Steel Ogre Grotto #1\" + \"Lesser Dragon\"",
    "category": []
  },
  "Flower Wolf": {
    "id": "95952802",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Flower Wolf",
    "atk": 1800,
    "def": 1400,
    "level": 5,
    "type": "Beast",
    "attribute": "EARTH",
    "effect": "\"Silver Fang\" + \"Darkworld Thorns\"",
    "category": []
  },
  "Gaia the Dragon Champion": {
    "id": "66889139",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Gaia the Dragon Champion",
    "atk": 2600,
    "def": 2100,
    "level": 7,
    "type": "Dragon",
    "attribute": "WIND",
    "effect": "\"Gaia The Fierce Knight\" + \"Curse of Dragon\"",
    "category": []
  },
  "B. Skull Dragon": {
    "id": "11901678",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "B. Skull Dragon",
    "atk": 3200,
    "def": 2500,
    "level": 9,
    "type": "Dragon",
    "attribute": "DARK",
    "effect": "\"Summoned Skull\" + \"Red-Eyes B. Dragon\"",
    "category": []
  },
  "Roaring Ocean Snake": {
    "id": "19066538",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Roaring Ocean Snake",
    "atk": 2100,
    "def": 1800,
    "level": 6,
    "type": "Aqua",
    "attribute": "WATER",
    "effect": "\"Mystic Lamp\", \"Hyosube\"",
    "category": []
  },
  "Deepsea Shark": {
    "id": "28593363",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Deepsea Shark",
    "atk": 1900,
    "def": 1600,
    "level": 5,
    "type": "Fish",
    "attribute": "WATER",
    "effect": "\"Bottom Dweller\" + \"Tongyo\"",
    "category": []
  },
  "Kaminari Attack": {
    "id": "09653271",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Kaminari Attack",
    "atk": 1900,
    "def": 1400,
    "level": 5,
    "type": "Thunder",
    "attribute": "WIND",
    "effect": "\"Ocubeam\" + \"Mega Thunderball\"",
    "category": []
  },
  "Empress Judge": {
    "id": "15237615",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Empress Judge",
    "atk": 2100,
    "def": 1700,
    "level": 6,
    "type": "Warrior",
    "attribute": "EARTH",
    "effect": "\"Queen\\'s Double\" + \"Hibikime\"",
    "category": []
  },
  "Rabid Horseman": {
    "id": "94905343",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Rabid Horseman",
    "atk": 2000,
    "def": 1700,
    "level": 6,
    "type": "Beast-Warrior",
    "attribute": "EARTH",
    "effect": "\"Battle Ox\" + \"Mystic Horseman\"",
    "category": []
  },
  "Labyrinth Tank": {
    "id": "99551425",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Labyrinth Tank",
    "atk": 2400,
    "def": 2400,
    "level": 7,
    "type": "Machine",
    "attribute": "DARK",
    "effect": "\"Giga-Tech Wolf\" + \"Cannon Soldier\"",
    "category": []
  },
  "Bickuribox": {
    "id": "25655502",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Bickuribox",
    "atk": 2300,
    "def": 2000,
    "level": 7,
    "type": "Fiend",
    "attribute": "DARK",
    "effect": "\"Crass Clown\" + \"Dream Clown\"",
    "category": []
  },
  "Giltia the D. Knight": {
    "id": "51828629",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Giltia the D. Knight",
    "atk": 1850,
    "def": 1500,
    "level": 5,
    "type": "Warrior",
    "attribute": "LIGHT",
    "effect": "\"Guardian of the Labyrinth\" + \"Protector of the Throne\"",
    "category": []
  },
  "Punished Eagle": {
    "id": "74703140",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Punished Eagle",
    "atk": 2100,
    "def": 1800,
    "level": 6,
    "type": "Winged Beast",
    "attribute": "WIND",
    "effect": "\"Blue-Winged Crown\" + \"Niwatori\"",
    "category": []
  },
  "Musician King": {
    "id": "56907389",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Musician King",
    "atk": 1750,
    "def": 1500,
    "level": 5,
    "type": "Spellcaster",
    "attribute": "LIGHT",
    "effect": "\"Witch of the Black Forest\" + \"Lady of Faith\"",
    "category": []
  },
  "Cyber Saurus": {
    "id": "89112729",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Cyber Saurus",
    "atk": 1800,
    "def": 1400,
    "level": 5,
    "type": "Machine",
    "attribute": "EARTH",
    "effect": "\"Blast Juggler\" + \"Two-Headed King Rex\"",
    "category": []
  },
  "Twin-Headed Thunder Dragon": {
    "id": "54752875",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Twin-Headed Thunder Dragon",
    "atk": 2800,
    "def": 2100,
    "level": 7,
    "type": "Thunder",
    "attribute": "LIGHT",
    "effect": "\"Thunder Dragon\" + \"Thunder Dragon\"",
    "category": []
  },
  "Skull Knight": {
    "id": "02504891",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Skull Knight",
    "atk": 2650,
    "def": 2250,
    "level": 7,
    "type": "Spellcaster",
    "attribute": "DARK",
    "effect": "\"Tainted Wisdom\" + \"Ancient Brain\"",
    "category": []
  },
  "Thousand Dragon": {
    "id": "41462083",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Thousand Dragon",
    "atk": 2400,
    "def": 2000,
    "level": 7,
    "type": "Dragon",
    "attribute": "WIND",
    "effect": "\"Time Wizard\" + \"Baby Dragon\"",
    "category": []
  },
  "Thousand-Eyes Restrict": {
    "id": "63519819",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Thousand-Eyes Restrict",
    "atk": 0,
    "def": 0,
    "level": 1,
    "type": "Spellcaster",
    "attribute": "DARK",
    "effect": "\"Relinquished\" + \"Thousand-Eyes Idol\"\\nOther monsters on the field cannot change their battle positions or attack. Once per turn: You can target 1 monster your opponent controls; equip it to this card (max. 1). This card\\'s ATK and DEF become equal to that equipped monster\\'s. If this card would be destroyed by battle, destroy that equipped monster instead.",
    "category": ["Control", "Attack Restriction", "Change ATK/DEF"]
  },
  "Humanoid Worm Drake": {
    "id": "05600127",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Humanoid Worm Drake",
    "atk": 2200,
    "def": 2000,
    "level": 7,
    "type": "Aqua",
    "attribute": "WATER",
    "effect": "\"Worm Drake\" + \"Humanoid Slime\"",
    "category": []
  },
  "St. Joan": {
    "id": "21175632",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "St. Joan",
    "atk": 2800,
    "def": 2000,
    "level": 7,
    "type": "Fairy",
    "attribute": "LIGHT",
    "effect": "\"The Forgiving Maiden\" + \"Marie the Fallen One\"",
    "category": []
  },
  "The Last Warrior from Another Planet": {
    "id": "86099788",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "The Last Warrior from Another Planet",
    "atk": 2350,
    "def": 2300,
    "level": 7,
    "type": "Warrior",
    "attribute": "EARTH",
    "effect": "\"Zombyra the Dark\" + \"Maryokutai\" If this card is Special Summoned: Destroy all other monsters you control. Neither player can Summon monsters.",
    "category": ["Destroy Monster", "Control"]
  },
  "Dark Balter the Terrible": {
    "id": "80071763",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dark Balter the Terrible",
    "atk": 2000,
    "def": 1200,
    "level": 5,
    "type": "Fiend",
    "attribute": "DARK",
    "effect": "\"Possessed Dark Soul\" + \"Frontier Wiseman\" A Fusion Summon of this card can only be done with the above Fusion Material Monsters. When a Normal Spell is activated (Quick Effect): You can pay 1000 Life Points; negate that effect. Negate the effects of monsters destroyed by battle with this card.",
    "category": ["Negate Effect"]
  },
  "Ryu Senshi": {
    "id": "49868263",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Ryu Senshi",
    "atk": 2000,
    "def": 1200,
    "level": 6,
    "type": "Warrior",
    "attribute": "EARTH",
    "effect": "\"Warrior Dai Grepher\" + \"Spirit Ryu\" A Fusion Summon of this card can only be done with the above Fusion Materials. When a Normal Trap is activated (Quick Effect): You can pay 1000 Life Points; negate that effect. Negate any Spell effects that target this card, and if you do, destroy that Spell.",
    "category": ["Negate Effect", "Destroy S/T"]
  },
  "Fiend Skull Dragon": {
    "id": "66235877",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Fiend Skull Dragon",
    "atk": 2000,
    "def": 1200,
    "level": 5,
    "type": "Dragon",
    "attribute": "WIND",
    "effect": "\"Cave Dragon\" + \"Lesser Fiend\" A Fusion Summon of this card can only be done with the above Fusion Material Monsters. Negate the effects of Flip Monsters. Negate any Trap effects that target this card on the field, and if you do, destroy that Trap.",
    "category": ["Negate Effect", "Destroy S/T"]
  },
  "Super Robolady": {
    "id": "75923050",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Super Robolady",
    "atk": 1200,
    "def": 500,
    "level": 6,
    "type": "Machine",
    "attribute": "EARTH",
    "effect": "\"Robolady\" + \"Roboyarou\" If this card attacks directly, it gains 1000 ATK during the Damage Step only. You can return this card from the field to the Fusion Deck; Special Summon 1 \"Super Roboyarou\" from the Fusion Deck. You cannot use this effect during the same turn this monster is Special Summoned.",
    "category": ["Change ATK/DEF", "Special Summon"]
  },
  "Super Roboyarou": {
    "id": "01412158",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Super Roboyarou",
    "atk": 1200,
    "def": 500,
    "level": 6,
    "type": "Machine",
    "attribute": "EARTH",
    "effect": "\"Roboyarou\" + \"Robolady\" If this card battles a monster, this card gains 1000 ATK during the Damage Step only. You can return this card from the field to the Fusion Deck; Special Summon 1 \"Super Robolady\" from the Fusion Deck. You cannot use this effect during the same turn this monster is Special Summoned.",
    "category": ["Change ATK/DEF", "Special Summon"]
  },
  "Reaper on the Nightmare": {
    "id": "85684223",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Reaper on the Nightmare",
    "atk": 800,
    "def": 600,
    "level": 5,
    "type": "Zombie",
    "attribute": "DARK",
    "effect": "\"Spirit Reaper\" + \"Nightmare Horse\" Cannot be destroyed by battle. After resolving a card effect that targets this face-up card, destroy this card. This card can attack directly. When this card inflicts battle damage to your opponent by a direct attack: Discard 1 random card from their hand.",
    "category": ["Direct Attack", "Destroy Hand"]
  },
  "XY-Dragon Cannon": {
    "id": "02111707",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "XY-Dragon Cannon",
    "atk": 2200,
    "def": 1900,
    "level": 6,
    "type": "Machine",
    "attribute": "LIGHT",
    "effect": "\"X-Head Cannon\" + \"Y-Dragon Head\" Must first be Special Summoned (from your Extra Deck) by banishing the above cards you control. (You do not use \"Polymerization\".) Cannot be Special Summoned from the Graveyard. You can discard 1 card, then target 1 face-up Spell or Trap your opponent controls; destroy it.",
    "category": ["Destroy S/T"]
  },
  "XYZ-Dragon Cannon": {
    "id": "91998119",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "XYZ-Dragon Cannon",
    "atk": 2800,
    "def": 2600,
    "level": 8,
    "type": "Machine",
    "attribute": "LIGHT",
    "effect": "\"X-Head Cannon\" + \"Y-Dragon Head\" + \"Z-Metal Tank\" Must first be Special Summoned (from your Fusion Deck) by banishing the above cards you control. (You do not use \"Polymerization\".) Cannot be Special Summoned from the Graveyard. You can discard 1 card, then target 1 card your opponent controls; destroy it.",
    "category": ["Destroy S/T", "Destroy Monster"]
  },
  "XZ-Tank Cannon": {
    "id": "99724761",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "XZ-Tank Cannon",
    "atk": 2400,
    "def": 2100,
    "level": 6,
    "type": "Machine",
    "attribute": "LIGHT",
    "effect": "\"X-Head Cannon\" + \"Z-Metal Tank\" Must first be Special Summoned (from your Extra Deck) by banishing the above cards you control. (You do not use \"Polymerization\".) Cannot be Special Summoned from the Graveyard. You can discard 1 card, then target 1 Set Spell or Trap your opponent controls; destroy it.",
    "category": ["Destroy S/T"]
  },
  "YZ-Tank Dragon": {
    "id": "25119460",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "YZ-Tank Dragon",
    "atk": 2100,
    "def": 2200,
    "level": 6,
    "type": "Machine",
    "attribute": "LIGHT",
    "effect": "\"Y-Dragon Head\" + \"Z-Metal Tank\" Must first be Special Summoned (from your Extra Deck) by banishing the above cards you control. (You do not use \"Polymerization\".) Cannot be Special Summoned from the Graveyard. You can discard 1 card, then target 1 face-down monster your opponent controls; destroy it.",
    "category": ["Destroy Monster"]
  },
  "Dark Paladin": {
    "id": "98502113",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dark Paladin",
    "atk": 2900,
    "def": 2400,
    "level": 8,
    "type": "Spellcaster",
    "attribute": "DARK",
    "effect": "\"Dark Magician\" + \"Buster Blader\" Must be Fusion Summoned. Gains 500 ATK for each Dragon monster on the field and in the Graveyard. When a Spell is activated (Quick Effect): You can discard 1 card; negate the activation, and if you do, destroy it. This card must be face-up on the field to activate and to resolve this effect.",
    "category": ["Change ATK/DEF", "Negate Activation"]
  },
  "Dark Paladin2": {
    "id": "98502113",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dark Paladin",
    "atk": 2900,
    "def": 2400,
    "level": 8,
    "type": "Spellcaster",
    "attribute": "DARK",
    "effect": "\"Dark Magician\" + \"Buster Blader\" Must be Fusion Summoned. Gains 500 ATK for each Dragon monster on the field and in the Graveyard. When a Spell is activated (Quick Effect): You can discard 1 card; negate the activation, and if you do, destroy it. This card must be face-up on the field to activate and to resolve this effect.",
    "category": ["Change ATK/DEF", "Negate Activation"]
  },
  "Dark Flare Knight": {
    "id": "13722870",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dark Flare Knight",
    "atk": 2200,
    "def": 800,
    "level": 6,
    "type": "Warrior",
    "attribute": "DARK",
    "effect": "\"Dark Magician\" + \"Flame Swordsman\" You take no Battle Damage from battles involving this card. When this card is destroyed by battle and sent to the Graveyard: Special Summon 1 \"Mirage Knight\" from your hand or Deck.",
    "category": ["Battle Protection", "Special Summon"]
  },
  "Ojama King": {
    "id": "90140980",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Ojama King",
    "atk": 0,
    "def": 3000,
    "level": 6,
    "type": "Beast",
    "attribute": "LIGHT",
    "effect": "\"Ojama Green\" + \"Ojama Yellow\" + \"Ojama Black\" When this card is Summoned: Choose up to 3 of your opponent\\'s unused Monster Zones; those zones cannot be used.",
    "category": ["Control"]
  },
  "Master of Oz": {
    "id": "27134689",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Master of Oz",
    "atk": 4200,
    "def": 3700,
    "level": 9,
    "type": "Beast",
    "attribute": "EARTH",
    "effect": "\"Big Koala\" + \"Des Kangaroo\"",
    "category": []
  },
  "Sanwitch": {
    "id": "53539634",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Sanwitch",
    "atk": 2100,
    "def": 1800,
    "level": 6,
    "type": "Spellcaster",
    "attribute": "DARK",
    "effect": "\"Sangan\" + \"Witch of the Black Forest\"",
    "category": []
  },
  "Dark Blade the Dragon Knight": {
    "id": "86805855",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dark Blade the Dragon Knight",
    "atk": 2200,
    "def": 1500,
    "level": 6,
    "type": "Warrior",
    "attribute": "DARK",
    "effect": "\"Dark Blade\" + \"Pitch-Dark Dragon\" When this card inflicts battle damage to your opponent: You can target up to 3 monsters in their Graveyard; banish them.",
    "category": ["Banish"]
  },
  "Mokey Mokey King": {
    "id": "13803864",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Mokey Mokey King",
    "atk": 300,
    "def": 100,
    "level": 6,
    "type": "Fairy",
    "attribute": "LIGHT",
    "effect": "\"Mokey Mokey\" + \"Mokey Mokey\" + \"Mokey Mokey\" When this card leaves the field: You can Special Summon as many \"Mokey Mokey\" as possible from your Graveyard.",
    "category": ["Special Summon"]
  },
  "Gatling Dragon": {
    "id": "87751584",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Gatling Dragon",
    "atk": 2600,
    "def": 1200,
    "level": 8,
    "type": "Machine",
    "attribute": "DARK",
    "effect": "\"Barrel Dragon\" + \"Blowback Dragon\" Once per turn: You can toss a coin 3 times and destroy as many monsters on the field as possible, but not more than the number of heads.",
    "category": ["Gamble", "Destroy Monster"]
  },
  "King Dragun": {
    "id": "13756293",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "King Dragun",
    "atk": 2400,
    "def": 1100,
    "level": 7,
    "type": "Dragon",
    "attribute": "DARK",
    "effect": "\"Lord of D.\" + \"Divine Dragon Ragnarok\" Your opponent cannot target Dragon monsters with card effects. Once per turn: You can Special Summon 1 Dragon monster from your hand.",
    "category": ["Control", "Special Summon"]
  },
  "Elemental HERO Flame Wingman": {
    "id": "35809262",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Elemental HERO Flame Wingman",
    "atk": 2100,
    "def": 1200,
    "level": 6,
    "type": "Warrior",
    "attribute": "WIND",
    "effect": "\"Elemental HERO Avian\" + \"Elemental HERO Burstinatrix\" Must be Fusion Summoned. When this card destroys a monster by battle and sends it to the Graveyard: Inflict damage to your opponent equal to the ATK of the destroyed monster in the Graveyard.",
    "category": ["Damage LP"]
  },
  "Elemental HERO Thunder Giant": {
    "id": "61204971",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Elemental HERO Thunder Giant",
    "atk": 2400,
    "def": 1500,
    "level": 6,
    "type": "Warrior",
    "attribute": "LIGHT",
    "effect": "\"Elemental HERO Sparkman\" + \"Elemental HERO Clayman\" Must be Fusion Summoned. Once per turn: You can discard 1 card, then target 1 monster on the field with original ATK less than the ATK of this card; destroy it.",
    "category": ["Destroy Monster"]
  },
  "Kwagar Hercules": {
    "id": "95144193",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Kwagar Hercules",
    "atk": 1900,
    "def": 1700,
    "level": 6,
    "type": "Insect",
    "attribute": "EARTH",
    "effect": "\"Kuwagata \\u03B1\" + \"Hercules Beetle\"",
    "category": []
  },
  "Warrior of Tradition": {
    "id": "56413937",
    "card-type": "fusion-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Warrior of Tradition",
    "atk": 1900,
    "def": 1700,
    "level": 6,
    "type": "Warrior",
    "attribute": "EARTH",
    "effect": "\"Sonic Maid\" + \"Beautiful Headhuntress\"",
    "category": []
  }
};