const monsterritualDetailed = {
  "Relinquished": {
    "id": "64631466",
    "card-type": "ritual-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Relinquished",
    "atk": 0,
    "def": 0,
    "level": 1,
    "type": "Spellcaster",
    "attribute": "DARK",
    "effect": "You can Ritual Summon this card with \"Black Illusion Ritual\". Once per turn: You can target 1 monster your opponent controls; equip it to this card (max. 1). This card's ATK and DEF become equal to that equipped monster's. If this card would be destroyed by battle, destroy that equipped monster instead, and any battle damage you received from the battle is also inflicted to your opponent.",
    "category": ["Control", "Change ATK/DEF", "Damage LP"]
  },
  "Performance of Sword": {
    "id": "04849037",
    "card-type": "ritual-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Performance of Sword",
    "atk": 1950,
    "def": 1850,
    "level": 6,
    "type": "Warrior",
    "attribute": "EARTH",
    "effect": "You can Ritual Summon this card with \"Commencement Dance\".",
    "category": []
  },
  "Hungry Burger": {
    "id": "30243636",
    "card-type": "ritual-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Hungry Burger",
    "atk": 2000,
    "def": 1850,
    "level": 6,
    "type": "Warrior",
    "attribute": "DARK",
    "effect": "You can Ritual Summon this card with \"Hamburger Recipe\".",
    "category": []
  },
  "Crab Turtle": {
    "id": "91782219",
    "card-type": "ritual-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Crab Turtle",
    "atk": 2250,
    "def": 2500,
    "level": 8,
    "type": "Aqua",
    "attribute": "WATER",
    "effect": "You can Ritual Summon this card with \"Turtle Oath\".",
    "category": []
  },
  "The Masked Beast": {
    "id": "49064413",
    "card-type": "ritual-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "The Masked Beast",
    "atk": 3200,
    "def": 1800,
    "level": 8,
    "type": "Fiend",
    "attribute": "DARK",
    "effect": "You can Ritual Summon this card with \"Curse of the Masked Beast\".",
    "category": []
  },
  "Paladin of White Dragon": {
    "id": "73398797",
    "card-type": "ritual-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Paladin of White Dragon",
    "atk": 1900,
    "def": 1200,
    "level": 4,
    "type": "Dragon",
    "attribute": "LIGHT",
    "effect": "You can Ritual Summon this card with \"White Dragon Ritual\". At the start of the Damage Step, if this card attacks a face-down Defense Position monster: Destroy that monster. You can Tribute this card; Special Summon 1 \"Blue-Eyes White Dragon\" from your hand or Deck, but \"Blue-Eyes White Dragon\" cannot attack for the rest of this turn.",
    "category": ["Destroy Monster", "Special Summon"]
  },
  "Shinato, King of a Higher Plane": {
    "id": "86327225",
    "card-type": "ritual-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Shinato, King of a Higher Plane",
    "atk": 3300,
    "def": 3000,
    "level": 8,
    "type": "Fairy",
    "attribute": "LIGHT",
    "effect": "You can Ritual Summon this card with \"Shinato's Ark\". When this card destroys a Defense Position monster by battle and sends it to the Graveyard: Inflict damage to your opponent equal to the original ATK of the destroyed monster.",
    "category": ["Damage LP"]
  },
  "Legendary Flame Lord": {
    "id": "60258960",
    "card-type": "ritual-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Legendary Flame Lord",
    "atk": 2400,
    "def": 2000,
    "level": 7,
    "type": "Spellcaster",
    "attribute": "FIRE",
    "effect": "You can Ritual Summon this card with \"Incandescent Ordeal\". Each time a Spell is activated, place 1 Spell Counter on this card when that Spell resolves. You can remove 3 Spell Counters from this card; destroy all other monsters on the field.",
    "category": ["Spell Counter", "Destroy Monster"]
  },
  "Dark Master - Zorc": {
    "id": "97642679",
    "card-type": "ritual-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dark Master - Zorc",
    "atk": 2700,
    "def": 1500,
    "level": 8,
    "type": "Fiend",
    "attribute": "DARK",
    "effect": "You can Ritual Summon this card with \"Contract with the Dark Master\". Once per turn: You can roll a six-sided die, destroy all monsters your opponent controls if you roll 1 or 2, destroy 1 monster your opponent controls if you roll 3, 4 or 5, or destroy all monsters you control if you roll 6.",
    "category": ["Gamble", "Destroy Monster"]
  },
  "Reshef the Dark Being": {
    "id": "62420419",
    "card-type": "ritual-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Reshef the Dark Being",
    "atk": 2500,
    "def": 1500,
    "level": 8,
    "type": "Fiend",
    "attribute": "LIGHT",
    "effect": "You can Ritual Summoned this card with \"Final Ritual of the Ancients\". Once per turn: You can discard 1 Spell, then target 1 monster your opponent controls; take control of that monster, until the end of this turn.",
    "category": ["Control"]
  },
  "Elemental Mistress Doriado": {
    "id": "99414168",
    "card-type": "ritual-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Elemental Mistress Doriado",
    "atk": 1200,
    "def": 1400,
    "level": 3,
    "type": "Spellcaster",
    "attribute": "LIGHT",
    "effect": "You can Ritual Summoned this card with \"Doriado's Blessing\". The Attribute of this card is also treated as WIND, WATER, FIRE, and EARTH while it is face-up on the field.",
    "category": ["Control"]
  },
  "Skull Guardian": {
    "id": "03627449",
    "card-type": "ritual-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Skull Guardian",
    "atk": 2050,
    "def": 2500,
    "level": 7,
    "type": "Warrior",
    "attribute": "LIGHT",
    "effect": "You can Ritual Summoned this card with \"Novox's Prayer\".",
    "category": []
  },
  "Dokurorider": {
    "id": "99721536",
    "card-type": "ritual-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dokurorider",
    "atk": 1900,
    "def": 1850,
    "level": 6,
    "type": "Zombie",
    "attribute": "DARK",
    "effect": "You can Ritual Summoned this card with \"Revival of Dokurorider\".",
    "category": []
  },
  "Black Luster Soldier": {
    "id": "05405694",
    "card-type": "ritual-monster",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Black Luster Soldier",
    "atk": 3000,
    "def": 2500,
    "level": 8,
    "type": "Warrior",
    "attribute": "EARTH",
    "effect": "You can Ritual Summon this card with \"Black Luster Ritual\".",
    "category": []
  }
};