const spellnormalDetailed = {
  "Dark Hole": {
    "id": "53129443",
    "card-type": "normal-spell",
    "banlist": "Banned",
    "Genesys": 0,
    "name": "Dark Hole",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Destruye todos los monstruos en el Campo.",
    "category": ["Destroy Monster"]
  },
  "Raigeki": {
    "id": "12580477",
    "card-type": "normal-spell",
    "banlist": "Banned",
    "Genesys": 0,
    "name": "Raigeki",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Destruye todos los monstruos en el Campo de tu adversario.",
    "category": ["Destroy Monster"]
  },
  "Red Medicine": {
    "id": "38199696",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Red Medicine",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Gain 500 Life Points.",
    "category": ["Recover LP"]
  },
  "Sparks": {
    "id": "76103675",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Sparks",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Inflict 200 damage to your opponent.",
    "category": ["Damage LP"]
  },
  "Hinotama": {
    "id": "46130346",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Hinotama",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Inflict 500 damage to your opponent.",
    "category": ["Damage LP"]
  },
  "Fissure": {
    "id": "66788016",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Fissure",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Destroy the 1 face-up monster your opponent controls that has the lowest ATK (your choice, if tied).",
    "category": ["Destroy Monster"]
  },
  "Polymerization": {
    "id": "24094653",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Polymerization",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Fusion Summon 1 Fusion Monster from your Fusion Deck, using monsters from your hand or field as Fusion Material.",
    "category": ["Fusion", "Special Summon"]
  },
  "Remove Trap": {
    "id": "51482758",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Remove Trap",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 face-up Trap on the field; destroy it.",
    "category": ["Destroy S/T"]
  },
  "Gravedigger Ghoul": {
    "id": "82542267",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Gravedigger Ghoul",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 2 monsters in your opponent's Graveyard: Banish them.",
    "category": ["Banish"]
  },
  "Stop Defense": {
    "id": "63102017",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Stop Defense",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 Defense Position monster your opponent controls: Change it to face=up Attack Position.",
    "category": ["Position"]
  },
  "Goblin's Secret Remedy": {
    "id": "11868825",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Goblin's Secret Remedy",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Gain 600 Life Points.",
    "category": ["Recover LP"]
  },
  "Final Flame": {
    "id": "73134081",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Final Flame",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Inflict 600 damage to your opponent.",
    "category": ["Damage LP"]
  },
  "Swords of Revealing Light": {
    "id": "72302403",
    "card-type": "normal-spell",
    "banlist": "Limited",
    "Genesys": 0,
    "name": "Swords of Revealing Light",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Voltea todos los monstruos boca abajo en el Campo de tu adversario boca arriba. Esta carta permanece boca arriba en el Campo por 3 turnos de tu adversario. Mientras esta carta permanezca en el Campo, tu adversario no puede declarar un ataque.",
    "category": ["Battle Protection", "Attack Restriction"]
  },
  "Monster Reborn": {
    "id": "83764718",
    "card-type": "normal-spell",
    "banlist": "Banned",
    "Genesys": 0,
    "name": "Monster Reborn",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Selecciona 1 monstruo del Cementerio de tu adversario o del tuyo. Invoca mediante una Invocación Especial el monstruo seleccionado en tu Campo.",
    "category": ["Special Summon"]
  },
  "Pot of Greed": {
    "id": "55144522",
    "card-type": "normal-spell",
    "banlist": "Limited",
    "Genesys": 0,
    "name": "Pot of Greed",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Roba dos cartas de tu Deck.",
    "category": ["Draw"]
  },
  "Elegant Egotist": {
    "id": "90219263",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Elegant Egotist",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If \"Harpie Lady\" is on the field: Special Summon 1 \"Harpie Lady\" or \"Harpie Lady Sisters\" from your hand or Deck.",
    "category": ["Special Summon"]
  },
  "Tribute to the Doomed": {
    "id": "79759861",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Tribute to The Doomed",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Descarta 1 carta de tu mano. Selecciona 1 Monstruo en el Campo y destruyelo.",
    "category": ["Destroy Monster"]
  },
  "Soul Release": {
    "id": "05758500",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Soul Release",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target up to 5 cards in any Graveyard(s); banish them.",
    "category": ["Banish"]
  },
  "The Cheerful Coffin": {
    "id": "41142615",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "The Cheerful Coffin",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Discard up to 3 monsters from your hand to the Graveyard.",
    "category": ["Destroy Hand"]
  },
  "Change of Heart": {
    "id": "04031928",
    "card-type": "normal-spell",
    "banlist": "Banned",
    "Genesys": 0,
    "name": "Change of Heart",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Selecciona y controla 1 monstruo en el Campo de tu adversario hasta el final de tu turno.",
    "category": ["Control"]
  },
  "Tremendous Fire": {
    "id": "46918794",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Tremendous Fire",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Inflict 1000 damage to your opponent and take 500 damage.",
    "category": ["Damage LP"]
  },
  "Shield & Sword": {
    "id": "52097679",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Shield & Sword",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Switch the original ATK and DEF of all current face-up monsters on the field, until the end of this turn.",
    "category": ["Change ATK/DEF"]
  },
  "Block Attack": {
    "id": "25880422",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Block Attack",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 face-up Attack Position monster your opponent controls; change it to Defense Position.",
    "category": ["Position"]
  },
  "Share the Pain": {
    "id": "56830749",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Share the Pain",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Tribute 1 monster; your opponent Tributes 1 monster they control.",
    "category": ["Control"]
  },
  "Heavy Storm": {
    "id": "19613556",
    "card-type": "normal-spell",
    "banlist": "Limited",
    "Genesys": 0,
    "name": "Heavy Storm",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Destruye todas las Cartas Mágicas y de Trampa en el Campo.",
    "category": ["Destroy S/T"]
  },
  "Curse of Fiend": {
    "id": "12470447",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Curse of Fiend",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "During your Standby Phase: Change all Attack Position monsters on the field to face-up Defense Position and all Defense Position monsters on the field to face-up Attack Position. Those monsters cannot change their battle positions for the rest of this turn.",
    "category": ["Position"]
  },
  "Upstart Goblin": {
    "id": "70368879",
    "card-type": "normal-spell",
    "banlist": "Semi-limited",
    "Genesys": 0,
    "name": "Upstart Goblin",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Roba 1 carta de tu Deck. Aumenta los Life Points de tu adversario en 1000 puntos",
    "category": ["Draw"]
  },
  "Final Destiny": {
    "id": "18591904",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Final Destiny",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Discard 5 cards from your hand; destroy all cards on the field.",
    "category": ["Destroy S/T", "Destroy Monster"]
  },
  "Confiscation": {
    "id": "17375316",
    "card-type": "normal-spell",
    "banlist": "Banned",
    "Genesys": 0,
    "name": "Confiscation",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Paga 1000 Life Points. Mira la mano de tu adversario, selecciona 1 carta de entre ellas y descártala al Cementerio.",
    "category": ["Destroy Hand"]
  },
  "Delinquent Duo": {
    "id": "44763025",
    "card-type": "normal-spell",
    "banlist": "Limited",
    "Genesys": 0,
    "name": "Delinquent Duo",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Paga 1000 Life Points. Tu adversario descarta 1 al azar carta de su mano y luego selecciona y descarta otra carta de su mano.",
    "category": ["Destroy Hand"],
    "ruling": "Puedes activarla inclusivo si tu oponente controla una sola carta."
  },
  "Darkness Approaches": {
    "id": "80168720",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Darkness Approaches",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Discard 2 cards, then target 1 face-up monster on the field; flip it face-down, but do not change its battle position..",
    "category": ["Position"]
  },
  "The Forceful Sentry": {
    "id": "42829885",
    "card-type": "normal-spell",
    "banlist": "Banned",
    "Genesys": 0,
    "name": "The Forceful Sentry",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Mira la mano de tu adversario, selecciona 1 carta de ellas y devuélvela al Deck de tu adversario. Luego tu adversario baraja su Deck.",
    "category": ["Send to Deck", "Destroy Hand"]
  },
  "Giant Trunade": {
    "id": "42703248",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Giant Trunade",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Devuelve todas las Cartas Mágicas y de Trampa en el Campo a las manos de sus propietarios.",
    "category": ["Send to Hand"]
  },
  "Painful Choice": {
    "id": "74191942",
    "card-type": "normal-spell",
    "banlist": "Banned",
    "Genesys": 0,
    "name": "Painful Choice",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Selecciona 5 cartas de tu Deck y muéstralas a tu adversario. Tu adversario selecciona 1 carta de entre ellas. Añade la carta seleccionada a tu mano y descarta las cartas restantes al Cementerio.",
    "category": ["Send to Graveyard", "Send to Hand"]
  },
  "Eternal Rest": {
    "id": "95051344",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Eternal Rest",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Destroy all equipped monsters on the field.",
    "category": ["Destroy Monster"]
  },
  "Nobleman of Crossout": {
    "id": "71044499",
    "card-type": "normal-spell",
    "banlist": "Semi-limited",
    "Genesys": 0,
    "name": "Nobleman of Crossout",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Destruye 1 monstruo boca abajo y retíralo del juego. Si el monstruo es un Monstruo de Efecto de Volteo, ambos jugadores deben revisar sus Decks y retirar del juego todos los monstruos con el mismo nombre. Luego baraja los Decks.",
    "category": ["Destroy Monster", "Banish", "Flip"],
    "ruling": "Ver el Deck es un efecto mandatorio."
  },
  "Nobleman of Extermination": {
    "id": "17449108",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Nobleman of Extermination",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 face-down Spell or Trap on the field; destroy it, and if you do, banish it, then, if it was a Trap, each player reveals their Main Deck, then banishes all cards from it with that card's name.",
    "category": ["Banish", "Destroy S/T"]
  },
  "The Shallow Grave": {
    "id": "43434803",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "The Shallow Grave",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Each player targets 1 monster in their Graveyard; each player Special Summons the target from their Graveyard in face-down Defense Position.",
    "category": ["Special Summon"]
  },
  "Cold Wave": {
    "id": "60682203",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Cold Wave",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "At the start of your Main Phase 1: Neither player can Set or activate Spells and Traps, also, Spell and Trap effects cannot be activated, until your next Draw Phase.",
    "category": ["Control"]
  },
  "Rain of Mercy": {
    "id": "66719324",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Rain of Mercy",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Both players gain 1000 Life Points.",
    "category": ["Recover LP"]
  },
  "Insect Imitation": {
    "id": "96965364",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Insect Imitation",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Tribute 1 monster; Special Summon 1 Insect monster from your Deck whose Level is 1 higher than the Tributed monster had on the field.",
    "category": ["Special Summon"]
  },
  "Dimensionhole": {
    "id": "22959079",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dimensionhole",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 monster you control; banish it until your next Standby Phase. While the monster is banished by this effect, the Monster Zone of the targeted monster cannot be used.",
    "category": ["Banish"]
  },
  "Chosen One": {
    "id": "21888494",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Chosen One",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 monster than can be Special Summoned and 2 Spells or Traps in your hand; your opponent chooses 1 randomly card of them. If it is the monster, Special Summon it, also send the remaining cards to the Graveyard. If not, send those cards to the Graveyard.",
    "category": ["Send to Graveyard", "Special Summon"]
  },
  "Return of the Doomed": {
    "id": "19827717",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Return of the Doomed",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Discard 1 monster to the Graveyard; during the End Phase of this turn, add 1 monster destroyed by battle and sent to your Graveyard this turn to your hand.",
    "category": ["Destroy Monster"]
  },
  "Spiritualism": {
    "id": "15866454",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Spiritualism",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 Spell or Trap your opponent controls; return it to the hand. This card's activation and effect cannot be negated.",
    "category": ["Send to Hand"]
  },
  "Bait Doll": {
    "id": "07165085",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Bait Doll",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 Set Spell or Trap on the field; reveal it, force its activation if it is a Trap, then negate its effect if the activation timing is incorrect, and if you do, destroy it. (If it is not a Trap, return it face-down.) When this card resolves, shuffle it into the Deck instead of sending it to the Graveyard.",
    "category": ["Control", "Negate Effect", "Destroy S/T", "Send to Deck"]
  },
  "Miracle Dig": {
    "id": "06343408",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Miracle Dig",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If 5 or more of your monsters are banished: Target 3 of them; return them to the Graveyard.",
    "category": ["Send to Graveyard"]
  },
  "Spirit Elimination": {
    "id": "69832741",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Spirit Elimination",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "During this turn, if a monster(s) will be banished from the either Graveyard, you must banish monsters you control instead.",
    "category": ["Banish"]
  },
  "The Puppet Magic of Dark Ruler": {
    "id": "40703393",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "The Puppet Magic of Dark Ruler",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 Fiend monster in your Graveyard; banish face-up monsters you control whose total Levels exactly equal the Level of that monster, then Special Summon it.",
    "category": ["Special Summon"]
  },
  "Double Snare": {
    "id": "03682106",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Double Snare",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Destruye 1 carta boca arriba en el Campo que tenga el efecto de negar el efecto de las Cartas de Trampa.",
    "category": ["Destroy S/T"]
  },
  "Reinforcement of the Army": {
    "id": "32807846",
    "card-type": "normal-spell",
    "banlist": "Semi-limited",
    "Genesys": 0,
    "name": "Reinforcement of the Army",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Añade 1 monstruo de Tipo Guerrero de Nivel 4 o inferior desde tu Deck a tu mano. Luego baraja tu Deck.",
    "category": ["Search", "Send to Hand"]
  },
  "The Warrior Returning Alive": {
    "id": "95281259",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "The Warrior Returning Alive",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 Warrior monster in your Graveyard; add it to your hand.",
    "category": ["Send to Hand"]
  },
  "A Wingbeat of Giant Dragon": {
    "id": "28596933",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "A Wingbeat of Giant Dragon",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Return 1 Level 5 or higher Dragon monster you control to the hand, and if you do, destroy all Spells and Traps on the field.",
    "category": ["Send to Hand", "Destroy S/T"]
  },
  "Dragon's Gunfire": {
    "id": "55991637",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dragon's Gunfire",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If you control a Dragon monster: Activate 1 of these effects. ● Inflict 800 damage to your opponent. ● Target 1 monster with 800 or less DEF on the field; destroy it.",
    "category": ["Damage LP", "Destroy Monster"]
  },
  "Stamping Destruction": {
    "id": "81385346",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Stamping Destruction",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Sólo puedes activar esta carta cuando tengas un monstruo de Tipo Dragón boca arriba en tu Campo. Destruye 1 Carta Mágica o de Trampa en el Campo e inflige 500 puntos de daño al controlador de esa carta.",
    "category": ["Damage LP", "Destroy S/T"]
  },
  "Fengsheng Mirror": {
    "id": "37406863",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Fengsheng Mirror",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Look at your opponent's hand and discard 1 Spirit monster from their hand (if any).",
    "category": ["Control", "Destroy Hand"]
  },
  "Creature Swap": {
    "id": "31036355",
    "card-type": "normal-spell",
    "banlist": "Semi-limited",
    "Genesys": 0,
    "name": "Creature Swap",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Ambos jugadores seleccionan 1 monstruo de sus respectivos Campos e intercambian el control de esos monstruos con el otro. Los monstruos seleccionados no pueden cambiar sus posiciones de batalla este turno.",
    "category": ["Control"],
    "ruling": "Si al activar esta carta cuando cada jugador controla un sólo monstruo y se activa una carta en respuesta a ésta que su efecto mueva un monstruo (destruya o devuelva) el jugador que queda con un sólo monstruo no lo cambia por el efecto de la carta."
  },
  "The Secret of the Bandit": {
    "id": "99351431",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "The Secret of the Bandit",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "During your Main Phase 1: Target 1 face-up monster on the field; each time the targeted monster inflicts battle damage to your opponent this turn, your opponent discards 1 random card.",
    "category": ["Destroy Hand"]
  },
  "After Genocide": {
    "id": "25345186",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "After Genocide",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "During Main Phase 1: This turn, at the end of the Damage Step, if a monster battled, destroy it.",
    "category": ["Destroy Monster"]
  },
  "Magic Reflector": {
    "id": "61844784",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Magic Reflector",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 face-up Spell you control; place 1 counter on it. If it would ever be destroyed, remove the counter instead.",
    "category": []
  },
  "Book of Life": {
    "id": "02204140",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Book of Life",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Invoca mediante una Invocación Especial 1 monstruo de Tipo Zombi de tu Cementerio al Campo y retira 1 monstruo en el Cementerio de tu adversario del juego.",
    "category": ["Special Summon", "Banish"]
  },
  "Book of Taiyou": {
    "id": "38699854",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Book of Taiyou",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 face-down monster on the field; change it to face-up Attack Position.",
    "category": ["Position"]
  },
  "Secret Pass to the Treasures": {
    "id": "77876207",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Secret Pass to the Treasures",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 face-up monster with 1000 or less ATK you control; that monster with 1000 or less ATK can attack directly this turn.",
    "category": ["Direct Attack"]
  },
  "Timidity": {
    "id": "40350910",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Timidity",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Set Spells and Traps on the field cannot be destroyed by card effects, until the end of your opponent's next turn.",
    "category": ["Control"]
  },
  "Dark Designator": {
    "id": "78053598",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dark Designator",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Declare 1 monster name; if that card is in your opponent's Main Deck, add 1 card with that name to your opponent's hand.",
    "category": ["Send to Hand"]
  },
  "Reasoning": {
    "id": "58577036",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Reasoning",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Your opponent declares a monster Level from 1 to 12. Excavate cards from the top of your Deck until you excavate a monster that can be Normal Summoned or Set, then, if that monster's Level is the same as the declared Level, send all excavated cards to the Graveyard. If not, Special Summon the excavated monster, also send the remaining cards to the Graveyard. If no monster is excavated, shuffle your Deck and put it back in the Deck Zone.",
    "category": ["Special Summon"]
  },
  "Different Dimension Capsule": {
    "id": "11961740",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Different Dimension Capsule",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Banish 1 card from your Deck face-down. After this card's activation, it remains on the field. Destroy this card during your 2nd Standby Phase after activating this card, and if you do, add the banished card to the hand.",
    "category": ["Banish", "Send to Hand"]
  },
  "Hieroglyph Lithograph": {
    "id": "10248192",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Hieroglyph Lithograph",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Pay 1000 Life Points; your hand size limit becomes 7.",
    "category": ["Control"]
  },
  "Terraforming": {
    "id": "73628505",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Terraforming",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Add 1 Field from your Deck to your hand.",
    "category": ["Search", "Send to Hand"]
  },
  "Metamorphosis": {
    "id": "46411259",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Metamorphosis",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Ofrece 1 monstruo en tu Campo como Sacrificio para Invocar mediante una Invocación Especial 1 Monstruo de Fusión del mismo Nivel de tu Deck Extra.",
    "category": ["Special Summon", "Fusion"]
  },
  "Royal Tribute": {
    "id": "72405967",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Royal Tribute",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If you control \"Necrovalley\": Both players discard all monsters in their hands.",
    "category": ["Destroy Hand"]
  },
  "Reversal Quiz": {
    "id": "05990062",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Reversal Quiz",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Send all cards you control and your entire hand to the Graveyard (min.1); Call the type of card (Spell, Trap, or Monster) on the top of your Deck. If you call it right, exchange your current Life Points with your opponent's current ones.",
    "category": ["Recover LP", "Damage LP"]
  },
  "Question": {
    "id": "38723936",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Question",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When activating this card, your opponent cannot check the Graveyard. Your opponent calls the name of the first monster found at the bottom of your Graveyard. If they call it right, the monster is banished. If they call it wrong, Special Summon it.",
    "category": ["Banish", "Special Summon"]
  },
  "Ante": {
    "id": "34236961",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Ante",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Each Player reveals 1 card from their hand, then if one card is higher Level than the other, the card with the lower Level is sent to the Graveyard, and the player who revealed it takes 1000 damage. (Non-Monster Cards are treated as Level 0.)",
    "category": ["Damage LP"]
  },
  "Dark Core": {
    "id": "70231910",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dark Core",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Discard 1 card, then target 1 face-up monster on the field; banish it.",
    "category": ["Banish"]
  },
  "Tribute Doll": {
    "id": "02903036",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Tribute Doll",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Tribute 1 monster; Special Summon 1 Level 7 monster from your hand that can be Normal Summoned or Set, but it cannot attack this turn.",
    "category": ["Special Summon", "Attack Restriction"]
  },
  "Amazoness Spellcaster": {
    "id": "81325903",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Amazoness Spellcaster",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 \"Amazoness\" monster you control and 1 face-up monster your opponent controls; switch the original ATK of those targets, until the end of this turn.",
    "category": ["Change ATK/DEF"]
  },
  "Gather Your Mind": {
    "id": "07512044",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Gather Your Mind",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Add 1 \"Gather Your Mind\" from your Deck to your hand. You can only activate 1 \"Gather Your Mind\" per turn.",
    "category": ["Search", "Send to Hand"]
  },
  "Emblem of Dragon Destroyer": {
    "id": "06390406",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Emblem of Dragon Destroyer",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Add 1 \"Buster Blader\" from your Deck or Graveyard to your hand.",
    "category": ["Search", "Send to Hand"]
  },
  "Mega Ton Magical Cannon": {
    "id": "32062913",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Mega Ton Magical Cannon",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Remove 10 Spell Counters from your field; destroy all cards your opponent controls.",
    "category": ["Spell Counter", "Destroy S/T", "Destroy Monster"]
  },
  "Double Spell": {
    "id": "24096228",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Double Spell",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Discard 1 Spell, then target 1 Spell in your opponent's Graveyard; place that target in the appropriate Zone on your field, and as this card's effect resolution, follow its card text as if you had used it yourself.",
    "category": ["Control"]
  },
  "Diffusion Wave-Motion": {
    "id": "87880531",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Diffusion Wave-Motion",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If your opponent controls a monster: Pay 1000 Life Points, then target 1 Level 7 or higher Spellcaster monster you control; this turn, it must attack all monsters your opponent controls once each, also other monsters you control cannot attack. The effects of monsters destroyed by these attacks cannot activate and are negated.",
    "category": ["Multi Attack", "Negate Effect"]
  },
  "Contract with Exodia": {
    "id": "33244944",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Contract with Exodia",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If all 5 of \"Exodia the Forbidden One\", \"Right Arm of the Forbidden One\", \"Left Arm of the Forbidden One\", \"Right Leg of the Forbidden One\", and \"Left Leg of the Forbidden One\" are in your Graveyard: Special Summon 1 \"Exodia Necross\" from your hand.",
    "category": ["Special Summon"]
  },
  "Fairy of the Spring": {
    "id": "20188127",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Fairy of the Spring",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 Equip Spell in your Graveyard; add it to your hand. That Equip Spell cannot be activated this turn.",
    "category": ["Send to Hand"]
  },
  "Token Thanksgiving": {
    "id": "57182235",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Token Thanksgiving",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Destroy all tokens on the field, then gain Life Points equal to the number of tokens destroyed x 800.",
    "category": ["Destroy Monster", "Token", "Recover LP"]
  },
  "Cost Down": {
    "id": "23265313",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Cost Down",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Discard 1 card; for the rest of this turn, reduce the Levels of all monsters in your hand by 2 (even after they are Summoned).",
    "category": ["Control"]
  },
  "Spell Reproduction": {
    "id": "29228529",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Spell Reproduction",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Send 2 Spells from your hand to the Graveyard, then target 1 Spell in your Graveyard; add it to your hand.",
    "category": ["Send to Hand"]
  },
  "Dragged Down into the Grave": {
    "id": "16435215",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dragged Down into the Grave",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Both players reveal their hands, each chooses 1 card from their opponent's hand, then you discard the chosen cards from both players' hands, then both players draw 1 card.",
    "category": ["Draw", "Destroy Hand", "Control"]
  },
  "Checkmate": {
    "id": "69313735",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Checkmate",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Tribute 1 \"Archfiend\" monster, then target 1 \"Terrorking Archfiend\" you control; it can attack directly this turn.",
    "category": ["Direct Attack"]
  },
  "Final Countdown": {
    "id": "95308449",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Final Countdown",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Pay 2000 Life Points; after 20 turns have passed after you activate this card (counting the turn you activate this card as the 1st turn), you win the Duel.",
    "category": ["Win Condition"]
  },
  "Mustering of the Dark Scorpions": {
    "id": "68191243",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Mustering of the Dark Scorpions",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If you control \"Don Zaloog\": Special Summon any number of \"Dark Scorpion\" monsters from your hand, but only 1 copy of each.",
    "category": ["Special Summon"]
  },
  "Wild Nature's Release": {
    "id": "61166988",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Wild Nature's Release",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 Beast or Beast-Warrior monster on the field; it gains ATK equal to its current DEF (until the End Phase), and if it does, it is destroyed during the End Phase.",
    "category": ["Change ATK/DEF"]
  },
  "Ojama Delta Hurricane!!": {
    "id": "08251996",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Ojama Delta Hurricane!!",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If you control \"Ojama Green\", \"Ojama Yellow\", and \"Ojama Black\": Destroy all cards your opponent controls.",
    "category": ["Destroy Monster", "Destroy S/T"]
  },
  "Chaos End": {
    "id": "61044390",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Chaos End",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If 7 or more of your cards are banished: Destroy all monsters on the field.",
    "category": ["Destroy Monster"]
  },
  "Chaos Greed": {
    "id": "97439308",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Chaos Greed",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If 4 or more of your cards are banished, and there are no cards in your Graveyard: Draw 2 cards.",
    "category": ["Draw"]
  },
  "D.D. Designator": {
    "id": "33423043",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "D.D. Designator",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Declare 1 card name; look at your opponent's hand, and if they have the declared card in their hand, banish 1 card with that name from their hand. If they do not have the declared card in their hand, banish 1 random card from your hand.",
    "category": ["Destroy Hand", "Banish", "Control"]
  },
  "Primal Seed": {
    "id": "23701465",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Primal Seed",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If \"Black Luster Soldier - Envoy of the Beginning\" or \"Chaos Emperor Dragon - Envoy of the End\" is on the field: Target 2 of your banished cards; add them to your hand.",
    "category": ["Send to Hand"]
  },
  "Thunder Crash": {
    "id": "69196160",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Thunder Crash",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Destroy all monsters you control, and if you do, inflict 300 damage to your opponent for each monster destroyed by this effect.",
    "category": ["Destroy Monster", "Damage LP"]
  },
  "Dimension Distortion": {
    "id": "95194279",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dimension Distortion",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If there are no cards in your Graveyard: Target 1 banished monster; Special Summon it.",
    "category": ["Special Summon"]
  },
  "Gryphon's Feather Duster": {
    "id": "34370473",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Gryphon's Feather Duster",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Destroy all Spells and Traps you control, and if you do, gain Life Points equal to the number of destroyed cards by this effect x 500.",
    "category": ["Destroy S/T", "Recover LP"]
  },
  "Stray Lambs": {
    "id": "60764581",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Stray Lambs",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Special Summon 2 \"Lamb Tokens\" (Beast/EARTH/Level 1/ATK 0/DEF 0) in Defense Position. You cannot Summon other monsters the turn you activate this card (but you can Set).",
    "category": ["Special Summon", "Token"]
  },
  "Smashing Ground": {
    "id": "97169186",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Smashing Ground",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Destroy the 1 face-up monster your opponent controls that has the highest DEF (your choice, if tied).",
    "category": ["Destroy Monster"]
  },
  "Dimension Fusion": {
    "id": "23557835",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dimension Fusion",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Pay 2000 Life Points; both players Special Summon as many of their banished monsters as possible.",
    "category": ["Special Summon"]
  },
  "Salvage": {
    "id": "96947648",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Salvage",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Añade 2 monstruos de AGUA con un ATK de 1500 o menor de tu Cementerio a tu mano.",
    "category": ["Send to Hand"]
  },
  "Ultra Evolution Pill": {
    "id": "22431243",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Ultra Evolution Pill",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Tribute 1 Reptile monster; Special Summon 1 Dinosaur monster from your hand.",
    "category": ["Special Summon"]
  },
  "Multiplication of Ants": {
    "id": "22493811",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Multiplication of Ants",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Tribute 1 Insect monster; Special Summon 2 \"Army Ant Tokens\" (Insect/EARTH/Level 4/ATK 500/DEF 1200). They cannot be Tributed for a Tribute Summon.",
    "category": ["Special Summon", "Token"]
  },
  "Jade Insect Whistle": {
    "id": "95214051",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Jade Insect Whistle",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Your opponent chooses 1 Insect monster from their Deck and places it on the top of their Deck.",
    "category": ["Send to Deck"]
  },
  "Burst Stream of Destruction": {
    "id": "17655904",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Burst Stream of Destruction",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If you control \"Blue-Eyes White Dragon\": Destroy all monsters your opponent controls. \"Blue-Eyes White Dragon\" you control cannot attack the turn you activate this card.",
    "category": ["Destroy Monster", "Attack Restriction"]
  },
  "Monster Gate": {
    "id": "43040603",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Monster Gate",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Tribute 1 monster; excavate cards from the top of your Deck until you excavate a monster that can be Normal Summoned or Set, then, Special Summon the excavated monster, also send the remaining cards to the Graveyard. If no monster is excavated, shuffle your Deck and put it back in the Deck Zone.",
    "category": ["Special Summon"]
  },
  "Earthquake": {
    "id": "82828051",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Earthquake",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Change all face-up monsters on the field to Defense Position.",
    "category": ["Position"]
  },
  "Goblin Thief": {
    "id": "45311864",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Goblin Thief",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Inflict 500 damage to your opponent and gain 500 Life Points.",
    "category": ["Damage LP"]
  },
  "Special Hurricane": {
    "id": "42598242",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Special Hurricane",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Discard 1 card; destroy all Special Summoned monsters on the field.",
    "category": ["Destroy Monster"]
  },
  "Enchanting Fitting Room": {
    "id": "30531525",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Enchanting Fitting Room",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Pay 800 Life Points; excavate the top 4 cards of your Deck and Special Summon all Level 3 or lower Normal Monsters, also shuffle the other cards (if any) into the Deck.",
    "category": ["Special Summon"]
  },
  "The Law of the Normal": {
    "id": "66926224",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "The Law of the Normal",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If you control 5 Level 2 or lower Normal Monsters: Both players discard all cards in their hands, also destroy all cards on the field, except Level 2 or lower Normal Monsters.",
    "category": ["Destroy Hand", "Destroy Monster", "Destroy S/T"]
  },
  "Dark Magic Attack": {
    "id": "02314238",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dark Magic Attack",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If you control \"Dark Magician\": Destroy all Spells and Traps your opponent controls.",
    "category": ["Destroy S/T"]
  },
  "Delta Attacker": {
    "id": "39719977",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Delta Attacker",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If you control 3 non-Token Normal Monsters with the same name: All Normal Monsters with that name you currently control can attack directly this turn.",
    "category": ["Direct Attack"]
  },
  "Thousand Energy": {
    "id": "05703682",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Thousand Energy",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "All Level 2 non-Token Normal Monsters you currently control gain 1000 ATK and DEF, until the end of this turn. During the End Phase of this turn, destroy all Level 2 Normal Monsters you control.",
    "category": ["Change ATK/DEF", "Destroy Monster"]
  },
  "Triangle Power": {
    "id": "32298781",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Triangle Power",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "All Level 1 non-Token Normal Monsters you currently control gain 2000 ATK and DEF, until the end of this turn. During the End Phase of this turn, destroy all Level 1 Normal Monsters you control.",
    "category": ["Change ATK/DEF", "Destroy Monster"]
  },
  "Dark Factory of Mass Production": {
    "id": "90928333",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dark Factory of Mass Production",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 2 Normal Monsters in your Graveyard; add them to your hand.",
    "category": ["Send to Hand"]
  },
  "Hammer Shot": {
    "id": "26412047",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Hammer Shot",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Destruye 1 monstruo boca arriba en Posición de Ataque con el mayor ATK en el Campo.",
    "category": ["Destroy Monster"]
  },
  "Abyssal Designator": {
    "id": "89801755",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Abyssal Designator",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Pay 1000 Life Points, then declare a Monster Type and an Attribute; your opponent sends 1 monster with both the declared Type and Attribute from their hand or Deck to the Graveyard.",
    "category": ["Destroy Hand", "Destroy Deck"]
  },
  "Level Up!": {
    "id": "25290459",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Level Up!",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Send 1 face-up \"LV\" monster you control to the Graveyard; Special Summon 1 monster from your hand or Deck that is listed in the sent monster's text, ignoring its Summoning conditions.",
    "category": ["Special Summon", "LV"]
  },
  "Inferno Fire Blast": {
    "id": "52684508",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Inferno Fire Blast",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 \"Red-Eyes B. Dragon\" in your Monster Zone; inflict damage to your opponent equal to the original ATK of that \"Red-Eyes B. Dragon\". \"Red-Eyes B. Dragon\" cannot attack the turn you activate this card.",
    "category": ["Damage LP", "Attack Restriction"]
  },
  "The Graveyard in the Fourth Dimension": {
    "id": "88089103",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "The Graveyard in the Fourth Dimension",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Añade 2 monstruos en tu Cementerio que tengan <b>LV</b> a tu Deck y barajalo.",
    "category": ["LV", "Send to Deck"]
  },
  "Big Wave Small Wave": {
    "id": "51562916",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Big Wave Small Wave",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Destruye todos los monstruos de AGUA boca arriba en tu Campo. Puedes entonces Invocar mediante una Invocación Especial de tu mano monstruos de AGUA hasta el mismo número de monstruos destruidos por este efecto.",
    "category": ["Special Summon"]
  },
  "Triangle Ecstasy Spark": {
    "id": "12181376",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Triangle Ecstasy Spark",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Until the end of this turn, the ATK of all \"Harpie Lady Sisters\" currently on the field becomes 2700, your opponent cannot activate Trap, also negate all your opponent's Trap effects on the field.",
    "category": ["Change ATK/DEF", "Negate Effect", "Control"]
  },
  "Machine Duplication": {
    "id": "63995093",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Machine Duplication",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 Machine monster you control with 500 or less ATK; Special Summon up to 2 monsters from your Deck with the same name as that monster.",
    "category": ["Special Summon"]
  },
  "Back to Square One": {
    "id": "47453433",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Back to Square One",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Discard 1 card, then target 1 monster on the field; place it on the top of the Deck.",
    "category": ["Send to Deck"]
  },
  "Monster Reincarnation": {
    "id": "74848038",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Monster Reincarnation",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Discard 1 card, then target 1 monster in your Graveyard; add it to your hand.",
    "category": ["Send to Hand"]
  },
  "A Feather of the Phoenix": {
    "id": "49140998",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "A Feather of the Phoenix",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Discard 1 card, then target 1 card in your Graveyard; place it on the top of your Deck.",
    "category": ["Send to Deck"]
  },
  "Lightning Vortex": {
    "id": "69162969",
    "card-type": "normal-spell",
    "banlist": "Limited",
    "Genesys": 0,
    "name": "Lightning Vortex",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Descarta 1 carta de tu mano. Destruye todos los monstruos boca arriba en el Campo de tu adversario.",
    "category": ["Destroy Monster"]
  },
  "Meteor of Destruction": {
    "id": "33767325",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Meteor of Destruction",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Inflige 1000 puntos de daño a los Life Points de tu adversario. No puedes activar esta carta si los Life Points de tu adversario son 3000 o menos.",
    "category": ["Damage LP"]
  },
  "Release Restraint": {
    "id": "75417459",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Release Restraint",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Tribute 1 \"Gearfried the Iron Knight\"; Special Summon 1 \"Gearfried the Swordmaster\" from your hand or Deck.",
    "category": ["Special Summon"]
  },
  "Card of Sanctity": {
    "id": "42664989",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Card of Sanctity",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Banish all other cards you control and in your hand (min. 1); draw until you have 2 cards in your hand.",
    "category": ["Banish", "Draw"]
  },
  "Brain Control": {
    "id": "87910978",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Brain Control",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Pay 800 Life Points, then target 1 face-up monster your opponent controls; take control of it, until the end of this turn.",
    "category": ["Control"]
  },
  "Gift of the Martyr": {
    "id": "98792570",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Gift of the Martyr",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Send 1 monster you control to the Graveyard, then target 1 monster you control; The targeted monster gains ATK equal to the sent monster's ATK in the Graveyard, until the end of this turn.",
    "category": ["Change ATK/DEF"]
  },
  "Double Attack": {
    "id": "34187685",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Double Attack",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Discard 1 monster from your hand to the Graveyard, then target 1 monster you control that has a level lower Level than the discarded monster; the targeted monster can attack twice this turn.",
    "category": ["Multi Attack"]
  },
  "Battery Charger": {
    "id": "61181383",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Battery Charger",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Pay 500 Life Points; Special Summon 1 \"Batteryman\" monster from your Graveyard.",
    "category": ["Special Summon"]
  },
  "Kaminote Blow": {
    "id": "97570038",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Kaminote Blow",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If you control 1 face-up \"Chu-Ske the Mouse Fighter\", \"Monk Fighter\", or \"Master Monk\": This turn, at the end of the Damage Step, destroy the monster(s) that battle with \"Chu-Ske the Mouse Fighter\", \"Monk Fighter\", or \"Master Monk\" your currently control.",
    "category": ["Destroy Monster"]
  },
  "Blue Medicine": {
    "id": "20871001",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Blue Medicine",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Gain 400 Life Points.",
    "category": ["Recover LP"]
  },
  "Raimei": {
    "id": "56260110",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Raimei",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Inflict 300 damage to your opponent.",
    "category": ["Damage LP"]
  },
  "Exile of the Wicked": {
    "id": "26725158",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Exile of the Wicked",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Destroy all Fiend monsters on the field.",
    "category": ["Destroy Monster"]
  },
  "Soul of the Pure": {
    "id": "47852924",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Soul of the Pure",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Gain 800 Life Points.",
    "category": ["Recover LP"]
  },
  "Toon Table of Contents": {
    "id": "89997728",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Toon Table of Contents",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Add 1 \"Toon\" card from your Deck to your hand.",
    "category": ["Search", "Send to Hand", "Toon"]
  },
  "Fusion Sage": {
    "id": "26902560",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Fusion Sage",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Add 1 \"Polymerization\" from your Deck to your hand.",
    "category": ["Search", "Send to Hand", "Fusion"]
  },
  "Restructer Revolution": {
    "id": "99518961",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Restructer Revolution",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Inflict 200 damage to your opponent for each card in their hand.",
    "category": ["Damage LP"]
  },
  "Dark-Piercing Light": {
    "id": "45895206",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dark-Piercing Light",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If your opponent controls a face-down monster: Flip all face-down monster they control face-up, but do not change their battle position.",
    "category": ["Position"]
  },
  "Dian Keto the Cure Master": {
    "id": "84257639",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dian Keto the Cure Master",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Gain 1000 Life Points.",
    "category": ["Recover LP"]
  },
  "De-Spell": {
    "id": "19159413",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "De-Spell",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 face-up Spell, or 1 Set Spell or Trap, on the field; destroy it if it is a Spell. (If the target is Set, reveal it.)",
    "category": ["Destroy S/T"]
  },
  "Last Will": {
    "id": "85602018",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Last Will",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Once, during this turn, the first time a monster(s) you control is sent to your Graveyard after this card is activated, you can Special Summon 1 monster with 1500 ATK or less from your Deck.",
    "category": ["Special Summon"]
  },
  "Soul Exchange": {
    "id": "68005187",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Soul Exchange",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 monster your opponent controls; this turn, if you Tribute a monster, you must Tribute that monster, as if you controlled it. You cannot conduct your Battle Phase the turn you activate this card.",
    "category": ["Control"]
  },
  "Card Destruction": {
    "id": "72892473",
    "card-type": "normal-spell",
    "banlist": "Limited",
    "Genesys": 0,
    "name": "Card Destruction",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Ambos jugadores descartan todas las cartas de su mano y roban de sus respectivos Deck la misma cantidad de cartas que descartaron.",
    "category": ["Destroy Hand", "Draw"],
    "ruling": "El jugador que la activa debe tener, como mínimo, la misma cantidad de cartas que va a descartar. Puede hacer deckear al oponente, pero no a sí mismo."
  },
  "Ookazi": {
    "id": "19523799",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Ookazi",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Inflict 800 damage to your opponent.",
    "category": ["Damage LP"]
  },
  "The Inexperienced Spy": {
    "id": "81820689",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "The Inexperienced Spy",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 card in your opponent's hand: Reveal it.",
    "category": ["Control"]
  },
  "Ancient Telescope": {
    "id": "17092736",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Ancient Telescope",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Look at the top 5 cards of your opponent's Deck. Return the cards to the Deck in the same order.",
    "category": ["Send to Deck", "Control"]
  },
  "The Flute of Summoning Dragon": {
    "id": "43973174",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "The Flute of Summoning Dragon",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If \"Lord of D.\" is on the field: Special Summon up to 2 Dragon monsters from your hand.",
    "category": ["Special Summon"]
  },
  "Graceful Charity": {
    "id": "79571449",
    "card-type": "normal-spell",
    "banlist": "Limited",
    "Genesys": 0,
    "name": "Graceful Charity",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Roba 3 cartas de tu Deck, y descarta 2 cartas de tu mano.",
    "category": ["Draw", "Destroy Hand"]
  },
  "Acid Rain": {
    "id": "21323861",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Acid Rain",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Destroy all Machine monsters on the field.",
    "category": ["Destroy Monster"]
  },
  "Exchange": {
    "id": "05556668",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Exchange",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Both players reveal their hands and add 1 card from each other's hand to their hand.",
    "category": ["Control"]
  },
  "Riryoku": {
    "id": "34016756",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Riryoku",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 2 face-up monsters on the field; halve the ATK of 1 monster, and if you do, add that lost ATK to the other monster, until the end of this turn.",
    "category": ["Change ATK/DEF"]
  },
  "Knight's Title": {
    "id": "87210505",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Knight's Title",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Tribute 1 face-up \"Dark Magician\"; Special Summon 1 \"Dark Magician Knight\" from your hand, Deck or Graveyard.",
    "category": ["Special Summon"]
  },
  "Sage's Stone": {
    "id": "13604200",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Sage's Stone",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If you control a face-up \"Dark Magician Girl\": Special Summon 1 \"Dark Magician\" from your hand or Deck.",
    "category": ["Special Summon"]
  },
  "Harpie's Feather Duster": {
    "id": "18144506",
    "card-type": "normal-spell",
    "banlist": "Banned",
    "Genesys": 0,
    "name": "Harpie's Feather Duster",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Destruye todas las Cartas Mágicas y de Trampa en el Campo de tu adversario.",
    "category": ["Destroy S/T"]
  },
  "Thousand Knives": {
    "id": "63391643",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Thousand Knives",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If you control \"Dark Magician\": Target 1 monster your opponent controls; destroy it.",
    "category": ["Destroy Monster"]
  },
  "Seal of the Ancients": {
    "id": "97809599",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Seal of the Ancients",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Pay 1000 Life Points: reveal all face-down cards your opponent controls. (The effects of the face-down cards are not activated.)",
    "category": ["Control"]
  },
  "Mind Control": {
    "id": "37520316",
    "card-type": "normal-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Mind Control",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Toma el control de 1 monstruo controlado por tu adversario hasta la End Phase. Ese monstruo no puede declarar un ataque o ser Sacrificado.",
    "category": ["Control"]
  }
};