const spellritualDetailed = {
  "Black Illusion Ritual": {
    "id": "41426869",
    "card-type": "ritual-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Black Illusion Ritual",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "This card is used to Ritual Summon \"Relinquished\". You must also Tribute a monster from your hand or field whose Level is 1 or more.",
    "category": []
  },
  "Commencement Dance": {
    "id": "43417563",
    "card-type": "ritual-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Commencement Dance",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "This card is used to Ritual Summon \"Performance of Sword\". You must also Tribute monsters from your hand or field whose total Levels equal 6 or more.",
    "category": []
  },
  "Hamburger Recipe": {
    "id": "80811661",
    "card-type": "ritual-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Hamburger Recipe",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "This card is used to Ritual Summon \"Hungry Burger\". You must also Tribute monsters from your hand or field whose total Levels equal 6 or more.",
    "category": []
  },
  "Turtle Oath": {
    "id": "76806714",
    "card-type": "ritual-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Turtle Oath",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "This card is used to Ritual Summon \"Crab Turtle\". You must also Tribute monsters from your hand or field whose total Levels equal 8 or more.",
    "category": []
  },
  "Curse of the Masked Beast": {
    "id": "94377247",
    "card-type": "ritual-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Curse of the Masked Beast",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "This card is used to Ritual Summon \"The Masked Beast\". You must also Tribute monsters from your hand or field whose total Levels equal 8 or more.",
    "category": []
  },
  "White Dragon Ritual": {
    "id": "09786492",
    "card-type": "ritual-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "White Dragon Ritual",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "This card is used to Ritual Summon \"Paladin of White Dragon\". You must also Tribute monsters from your hand or field whose total Levels equal 4 or more.",
    "category": []
  },
  "Shinato's Ark": {
    "id": "60365591",
    "card-type": "ritual-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Shinato's Ark",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "This card is used to Ritual Summon \"Shinato, King of a Higher Plane\". You must also Tribute monsters from your hand or field whose total Levels equal 8 or more.",
    "category": []
  },
  "Incandescent Ordeal": {
    "id": "33031674",
    "card-type": "ritual-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Incandescent Ordeal",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "This card is used to Ritual Summon \"Legendary Flame Lord\". You must also Tribute monsters from your hand or field whose total Levels equal 7 or more.",
    "category": []
  },
  "Contract with the Abyss": {
    "id": "69035382",
    "card-type": "ritual-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Contract with the Abyss",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "This card can be used to Ritual Summon any DARK Ritual Monster. You must also Tribute monsters from your hand or field whose total Levels exactly equal the original Level of the Ritual Monster you Ritual Summon.",
    "category": ["Ritual"]
  },
  "Contract with the Dark Master": {
    "id": "96420087",
    "card-type": "ritual-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Contract with the Dark Master",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "This card is used to Ritual Summon \"Dark Master - Zorc\". You must also Tribute monsters from your hand or field whose total Levels equal 8 or more.",
    "category": []
  },
  "Earth Chant": {
    "id": "59820352",
    "card-type": "ritual-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Earth Chant",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "This card can be used to Ritual Summon any EARTH Ritual Monster. You must also Tribute monsters from your hand or field whose total Levels exactly equal the original Level of the Ritual Monster you Ritual Summon.",
    "category": ["Ritual"]
  },
  "Doriado's Blessing": {
    "id": "23965037",
    "card-type": "ritual-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Doriado's Blessing",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "This card is used to Ritual Summon \"Elemental Mistress Doriado\". You must also Tribute monsters from your hand or field whose total Levels equal 3 or more.",
    "category": []
  },
  "Final Ritual of the Ancients": {
    "id": "60369732",
    "card-type": "ritual-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Final Ritual of the Ancients",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "This card is used to Ritual Summon \"Reshef the Dark Being\". You must also Tribute monsters from your hand or field whose total Levels equal 8 or more.",
    "category": []
  },
  "Novox's Prayer": {
    "id": "43694075",
    "card-type": "ritual-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Novox's Prayer",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "This card is used to Ritual Summon \"Skull Guardian\". You must also Tribute monsters from your hand or field whose total Levels equal 7 or more.",
    "category": []
  },
  "Revival of Dokurorider": {
    "id": "31066283",
    "card-type": "ritual-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Revival of Dokurorider",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "This card is used to Ritual Summon \"Dokurorider\". You must also Tribute monsters from your hand or field whose total Levels equal 6 or more.",
    "category": []
  },
  "Black Luster Ritual": {
    "id": "55761792",
    "card-type": "ritual-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Black Luster Ritual",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "This card is used to Ritual Summon \"Black Luster Soldier\". You must also Tribute monsters from your hand or field whose total Levels equal 8 or more.",
    "category": []
  }
};