const spellequipDetailed = {
  "Legendary Sword": {
    "id": "61854111",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Legendary Sword",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Un monstruo de Tipo Guerrero equipado con esta carta aumenta su ATK y su DEF en 300 puntos.",
    "category": ["Change ATK/DEF"]
  },
  "Beast Fangs": {
    "id": "46009906",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Beast Fangs",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Un monstruo de Tipo Bestia equipado con esta carta aumenta su ATK y su DEF en 300 puntos.",
    "category": ["Change ATK/DEF"]
  },
  "Violet Crystal": {
    "id": "15052462",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Violet Crystal",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Un monstruo de Tipo Zombi equipado con esta carta aumenta su ATK y su DEF en 300 puntos.",
    "category": ["Change ATK/DEF"]
  },
  "Book of Secret Arts": {
    "id": "91595718",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Book of Secret Arts",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Un monstruo de Tipo Lanzador de Conjuros equipado con esta carta aumenta su ATK y su DEF en 300 puntos.",
    "category": ["Change ATK/DEF"]
  },
  "Power of Kaishin": {
    "id": "77027445",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Power of Kaishin",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Un monstruo de Tipo Aqua equipado con esta carta aumenta su ATK y su DEF en 300 puntos.",
    "category": ["Change ATK/DEF"]
  },
  "Dark Energy": {
    "id": "04614116",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dark Energy",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Un monstruo de Tipo Demonio equipado con esta carta aumenta su ATK y su DEF en 300 puntos.",
    "category": ["Change ATK/DEF"]
  },
  "Laser Cannon Armor": {
    "id": "77007920",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Laser Cannon Armor",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Un monstruo de Tipo Insecto equipado con esta carta aumenta su ATK y su DEF en 300 puntos.",
    "category": ["Change ATK/DEF"]
  },
  "Vile Germs": {
    "id": "39774685",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Vile Germs",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Un monstruo de Tipo Planta equipado con esta carta aumenta su ATK y su DEF en 300 puntos.",
    "category": ["Change ATK/DEF"]
  },
  "Silver Bow and Arrow": {
    "id": "01557499",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Silver Bow and Arrow",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Un monstruo de Tipo Hada equipado con esta carta aumenta su ATK y su DEF en 300 puntos.",
    "category": ["Change ATK/DEF"]
  },
  "Dragon Treasure": {
    "id": "01435851",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dragon Treasure",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Un monstruo de Tipo Dragón equipado con esta carta aumenta su ATK y su DEF en 300 puntos.",
    "category": ["Change ATK/DEF"]
  },
  "Electro-Whip": {
    "id": "37820550",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Electro-Whip",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Un monstruo de Tipo Trueno equipado con esta carta aumenta su ATK y su DEF en 300 puntos.",
    "category": ["Change ATK/DEF"]
  },
  "Mystical Moon": {
    "id": "36607978",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Mystical Moon",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Un monstruo de Tipo Bestia equipado con esta carta aumenta su ATK y su DEF en 300 puntos.",
    "category": ["Change ATK/DEF"]
  },
  "Machine Conversion Factory": {
    "id": "25769732",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Machine Conversion Factory",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Un monstruo de Tipo Máquina equipado con esta carta aumenta su ATK y su DEF en 300 puntos.",
    "category": ["Change ATK/DEF"]
  },
  "Raise Body Heat": {
    "id": "51267887",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Raise Body Heat",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Un monstruo de Tipo Dinosaurio equipado con esta carta aumenta su ATK y su DEF en 300 puntos.",
    "category": ["Change ATK/DEF"]
  },
  "Follow Wind": {
    "id": "98252586",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Follow Wind",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Un monstruo de Tipo Bestia Alada equipado con esta carta aumenta su ATK y su DEF en 300 puntos.",
    "category": ["Change ATK/DEF"]
  },
  "Sword of Deep-Seated": {
    "id": "98495314",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Sword of Deep-Seated",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Una Carta de Monstruo equipada con esta carta aumenta su ATK y DEF en 500 puntos. Cuando esta carta se manda al Cementerio devuélvela a la parte superior de tu Deck.",
    "category": ["Change ATK/DEF", "Send to Deck"]
  },
  "Germ Infection": {
    "id": "24668830",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Germ Infection",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "El ATK de un monstruo que no sea del Tipo Máquina equipado con esta carta disminuye en 300 puntos en cada una de tus Standby Phases.",
    "category": ["Change ATK/DEF"]
  },
  "Paralyzing Potion": {
    "id": "50152549",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Paralyzing Potion",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Un monstruo que no sea del Tipo Máquina equipado con esta carta no puede atacar.",
    "category": ["Attack Restriction"]
  },
  "Ring of Magnetism": {
    "id": "20436034",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Ring of Magnetism",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Esta carta sólo se puede equipar a un monstruo en tu Campo. El monstruo equipado con esta carta disminuye su ATK y DEF en 500 puntos. Todos los monstuos en el Campo de tu adversario deben atacar al monstruo equipado con esta carta si eligen atacar.",
    "category": ["Change ATK/DEF", "Battle Protection"]
  },
  "Stim-Pack": {
    "id": "83225447",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Stim-Pack",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Un monstruo equipado con esta carta aumenta su ATK en 700 puntos. Su ATK disminuye en 200 puntos en cada una de tus Standby Phases.",
    "category": ["Change ATK/DEF"]
  },
  "Axe of Despair": {
    "id": "40619825",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Axe of Despair",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Aumenta el ATK del monstruo equipado con esta carta en 1000 puntos. Cuando esta carta es mandada del Campo al Cementerio, si ofreces 1 monstruo en tu Campo como Sacrificio, esta carta vuelve a la parte superior de tu Deck.",
    "category": ["Change ATK/DEF", "Send to Deck"]
  },
  "Black Pendant": {
    "id": "65169794",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Black Pendant",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Aumenta el ATK de un monstruo equipado con esta carta en 500 puntos. Cuando esta carta es mandada del Campo al Cementerio, inflige 500 puntos de daño a los Life Points de tu adversario.",
    "category": ["Change ATK/DEF", "Damage LP"]
  },
  "Horn of Light": {
    "id": "38552107",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Horn of Light",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Aumenta la DEF de un monstruo equipado con esta carta en 800 puntos. Cuando esta carta es mandada del Campo al Cementerio, si pagas 500 Life Points, esta carta vuelve a la parte superior de tu Deck.",
    "category": ["Change ATK/DEF", "Send to Deck"]
  },
  "Malevolent Nuzzler": {
    "id": "99597615",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Malevolent Nuzzler",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Aumenta el ATK de un monstruo equipado con esta carta en 700 puntos. Cuando esta carta es mandada del Campo al Cementerio, si pagas 500 Life Points, esta carta vuelve a la parte superior de tu Deck.",
    "category": ["Change ATK/DEF", "Send to Deck"]
  },
  "Snatch Steal": {
    "id": "45986603",
    "card-type": "equip-spell",
    "banlist": "Limited",
    "Genesys": 0,
    "name": "Snatch Steal",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Toma el control de un monstruo en el Campo de tu adversario equipado con esta carta. Aumenta los Life Points de tu adversario en 1000 puntos durante cada una de sus Standby Phases.",
    "category": ["Control"],
    "ruling": "Si el monstruo equipado es cambiado a posición boca abajo, éste se quedará del lado del Campo en donde cambió de posición."
  },
  "Horn of the Unicorn": {
    "id": "64047146",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Horn of the Unicorn",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Aumenta el ATK y la DEF de un monstruo equipado con esta carta en 700 puntos. Cuando esta carta es mandada del Campo al Cementerio, vuelve a la parte superior de tu Deck.",
    "category": ["Change ATK/DEF", "Send to Deck"]
  },
  "Magical Labyrinth": {
    "id": "64389297",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Magical Labyrinth",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Equipa <b>Labyrinth Wall</b> con esta carta. Ofrece <b>Labyrinth Wall</b> equipado con esta carta como Sacrificio para hacer la Invocación Especial de <b>Wall Shadow</b> de tu Deck.",
    "category": ["Special Summon"]
  },
  "Megamorph": {
    "id": "22046459",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Megamorph",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": " Mientras tus Life Points sean menores que los de tu adversario, dobla el ATK original del monstruo equipado con esta carta. Mientras tus Life Points sean mayores, el ATK original se divide a la mitad.",
    "category": ["Change ATK/DEF"]
  },
  "7 Completed": {
    "id": "86198326",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "7 Completed",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Activa esta carta eligiendo ATK o DEF; sólo puedes equiparla a un monstruo Máquina. Éste gana 700 ATK o DEF, dependiendo de tu elección.",
    "category": ["Change ATK/DEF"]
  },
  "Premature Burial": {
    "id": "70828912",
    "card-type": "equip-spell",
    "banlist": "Limited",
    "Genesys": 0,
    "name": "Premature Burial",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Paga 800 Life Points. Selecciona 1 Carta de Monstruo de tu Cementerio. Invócalo mediante una Invocación Especial al Campo en Posición de Ataque, y equípalo con esta carta. Cuando esta carta es destruida, destruye el monstruo equipado.",
    "category": ["Special Summon"],
    "ruling": "Si esta es regresada a la mano mientras está equipando a un monstruo, el monstruo no se destruye."
  },
  "Premature Burial 2": {
    "id": "70828912",
    "card-type": "equip-spell",
    "banlist": "Limited",
    "Genesys": 0,
    "name": "Premature Burial",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Paga 800 Life Points. Selecciona 1 Carta de Monstruo de tu Cementerio. Invócalo mediante una Invocación Especial al Campo en Posición de Ataque, y equípalo con esta carta. Cuando esta carta es destruida, destruye el monstruo equipado.",
    "category": ["Special Summon"],
    "ruling": "Si esta es regresada a la mano mientras está equipando a un monstruo, el monstruo no se destruye."
  },
  "Fairy Meteor Crush": {
    "id": "97687912",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Fairy Meteor Crush",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Cuando un monstruo equipado con esta carta ataca con un ATK superior a la DEF del monstruo en Posición de Defensa, inflige la diferencia a los Life Points de tu adversario como daño de batalla.",
    "category": ["Piercing"]
  },
  "Mask of the Accursed": {
    "id": "56948373",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Mask of the Accursed",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "El monstruo equipado con esta carta no puede atacar. El controlador del monstruo equipado recibe 500 puntos de daño a sus Life Points durante cada una de tus Standby Phases.",
    "category": ["Attack Restriction", "Damage LP"]
  },
  "Mask of Brutality": {
    "id": "82432018",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Mask of Brutality",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Aumenta el ATK de un monstruo equipado con esta carta en 1000 puntos y disminuye su DEF en 1000 puntos. Paga 1000 Life Points durante cada una de tus Standby Phases. Si no lo haces, destruye esta carta.",
    "category": ["Change ATK/DEF"]
  },
  "Lightning Blade": {
    "id": "55226821",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Lightning Blade",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Esta carta sólo puede ser equipada a un monstruo de Tipo Guerrero. Aumenta el ATK del monstruo equipado en 800 puntos y disminuye el ATK de todos los monstruos de AGUA en el Campo en 500 puntos.",
    "category": ["Change ATK/DEF"]
  },
  "Scroll of Bewitchment": {
    "id": "10352095",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Scroll of Bewitchment",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Selecciona 1 Atributo. Cambia el Atributo del monstruo equipado al que has seleccionado.",
    "category": ["Control"]
  },
  "United We Stand": {
    "id": "56747793",
    "card-type": "equip-spell",
    "banlist": "Limited",
    "Genesys": 0,
    "name": "United We Stand",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Aumenta el ATK y la DEF del monstruo equipado en 800 puntos por cada monstruo boca arriba que tu controles.",
    "category": ["Change ATK/DEF"]
  },
  "Mage Power": {
    "id": "83746708",
    "card-type": "equip-spell",
    "banlist": "Limited",
    "Genesys": 0,
    "name": "Mage Power",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Aumenta el ATK y la DEF del monstruo equipado en 500 puntos por cada Carta Mágica y de Trampa en tu Campo.",
    "category": ["Change ATK/DEF"]
  },
  "Cyclon Laser": {
    "id": "05494820",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Cyclon Laser",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Solamente <b>Gradius</b> puede ser equipado con esta carta. Aumenta el ATK de ese <b>Gradius</b> en 300 puntos. Cuando <b>Gradius</b> ataca con un ATK superior a la DEF de un monstruo en Posición de Defensa, inflige la diferencia a los Life Points de tu adversario como daño de batalla.",
    "category": ["Change ATK/DEF", "Piercing"]
  },
  "Ekibyo Drakmord": {
    "id": "69954399",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Ekibyo Drakmord",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Un monstruo equipado con esta carta no puede atacar. Destruye el monstruo equipado al final del 2do. turno del controlador del monstruo después de que esta carta fue activada. En ese momento, esta carta vuelve a la mano de su propietario.",
    "category": ["Attack Restriction", "Destroy Monster"]
  },
  "Dragonic Attack": {
    "id": "32437102",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dragonic Attack",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Esta carta sólo puede ser equipada a un monstruo de Tipo Guerrero. El monstruo equipado se considera de Tipo Dragón y aumenta su ATK y su DEF en 500 puntos.",
    "category": ["Change ATK/DEF"]
  },
  "Heart of Clear Water": {
    "id": "64801562",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Heart of Clear Water",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Si el ATK del monstruo equipado es 1300 o superior, destruye esta carta. El monstruo equipado con esta carta no puede ser destruido como resultado de una batalla o por el efecto de una carta que lo designe como objetivo. El daño de batalla se calcula normalmente.",
    "category": ["Battle Protection"]
  },
  "Fusion Sword Murasame Blade": {
    "id": "37684215",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Fusion Sword Murasame Blade",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Sólo puedes equipar esta carta a un monstruo Guerrero. Éste gana 800 ATK. Mientras esté equipada a un monstruo, esta carta no puede ser destruida por efectos de cartas.",
    "category": ["Change ATK/DEF"]
  },
  "Smoke Grenade of the Thief": {
    "id": "63789924",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Smoke Grenade of the Thief",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Cuando esta Carta Mágica de Equipo está activa y es destruida por el efecto de una carta, mira la mano de tu adversario, selecciona 1 carta de su mano y descártala.",
    "category": ["Destroy Hand"]
  },
  "Buster Rancher": {
    "id": "84740193",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Buster Rancher",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Solo puedes equipar esta carta a un monstruo con un ATK igual o menor a 1000 puntos. Durante el cálculo de daño, aumenta el ATK del monstruo equipado con esta carta en 2500 puntos solo cuando el monstruo de tu adversario que lucha esté en Posición de Ataque y su ATK sea igual a 2500 o más O cuando el monstruo de tu adversario que lucha esté en Posición de Defensa y su DEF es igual a 2500 o más.",
    "category": ["Change ATK/DEF"]
  },
  "Demotion": {
    "id": "72575145",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Demotion",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Disminuye en 2 Niveles el monstruo equipado con esta carta.",
    "category": ["Control"]
  },
  "Autonomous Action Unit": {
    "id": "71453557",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Autonomous Action Unit",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Paga 1500 Life Points. Selecciona 1 Carta de Monstruo del Cementerio de tu adversario. Invocala mediante una Invocación Especial a tu Campo en Posición de Ataque boca arriba, y equípala con esta carta. Cuando esta carta es retirada del Campo, destruye el monstruo equipado.",
    "category": ["Special Summon"]
  },
  "Raregold Armor": {
    "id": "07625614",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Raregold Armor",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Mientras controles el monstruo equipado con esta carta, tu adversario no puede atacar a otros monstruos que no sean el monstruo equipado.",
    "category": ["Battle Protection"]
  },
  "Metalsilver Armor": {
    "id": "33114323",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Metalsilver Armor",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Mientras controles el monstruo equipado con esta carta, tu adversario no puede usar el efecto de una carta Mágica, Carta de Trampa o Carta de Monstruo de Efecto que designen 1 monstruo que no sea el monstruo equipado como objetivo.",
    "category": ["Control"]
  },
  "Big Bang Shot": {
    "id": "61127349",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Big Bang Shot",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Un monstruo equipado con esta carta aumenta su ATK en 400 puntos. Cuando el monstruo equipado ataca con un ATK mayor que la DEF del monstruo en Posición de Defensa, inflige la diferencia a los Life Points de tu adversario como daño de batalla. Cuando esta carta es retirada del Campo, retira del juego al monstruo equipado.",
    "category": ["Change ATK/DEF", "Piercing", "Banish"]
  },
  "Butterfly Dagger - Elma": {
    "id": "69243953",
    "card-type": "equip-spell",
    "banlist": "Banned",
    "Genesys": 0,
    "name": "Butterfly Dagger - Elma",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "El monstruo equipado gana 300 ATK. Cuando esta carta es destruida y mandada al Cementerio mientras está equipada (excepto durante el Damage Step): puedes devolver esta carta a la mano.",
    "category": ["Send to Hand", "Change ATK/DEF"]
  },
  "Shooting Star Bow - Ceal": {
    "id": "95638658",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Shooting Star Bow - Ceal",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Un monstruo equipado con esta carta disminuye su ATK en 1000 puntos. Un monstruo equipado con esta carta puede atacar los Life Points de tu adversario directamente.",
    "category": ["Change ATK/DEF", "Attack Restriction"]
  },
  "Gravity Axe - Grarl": {
    "id": "32022366",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Gravity Axe - Grarl",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Un monstruo equipado con esta carta aumenta su ATK en 500 puntos. Mientras esta carta permanezca boca arriba en el Campo, los monstruos en el Campo de tu adversario no pueden cambiar su posición de batalla.",
    "category": ["Change ATK/DEF", "Position"]
  },
  "Wicked-Breaking Flamberge - Baou": {
    "id": "68427465",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Wicked-Breaking Flamberge - Baou",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Manda al Cementerio 1 carta en tu mano, y después selecciona 1 monstruo en el Campo; equipa esta carta a ese objetivo. Éste gana 500 ATK. Niega los efectos de monstruos del adversario destruidos en batalla con el monstruo equipado.",
    "category": ["Change ATK/DEF", "Negate Effect"]
  },
  "Rod of Silence - Kay'est": {
    "id": "95515060",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Rod of Silence - Kay'est",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Un monstruo equipado con esta carta aumenta su DEF en 500 puntos. Niega el efecto de una Carta Mágica, excepto esta carta, que designa un monstruo equipado con esta carta como objetivo y destruyela.",
    "category": ["Change ATK/DEF", "Negate Effect"]
  },
  "Twin Swords of Flashing Light - Tryce": {
    "id": "21900719",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Twin Swords of Flashing Light - Tryce",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Manda al Cementerio 1 carta en tu mano; equipa esta carta a un monstruo. Éste pierde 500 ATK, pero puede atacar una segunda vez durante cada Battle Phase.",
    "category": ["Change ATK/DEF", "Multi Attack"]
  },
  "Rod of the Mind's Eye": {
    "id": "94793422",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Rod of the Mind's Eye",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Si un monstruo equipado con esta carta inflige daño de batalla a tu adversario, el daño se convierte en 1000 puntos.",
    "category": ["Damage LP"]
  },
  "Falling Down": {
    "id": "32919136",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Falling Down",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Destruye esta carta si no hay ninguna carta <b>Archfiend</b> boca arriba en tu Campo. Toma el control de 1 monstruo boca arriba de tu adversario equipo con esta carta. Recibes 800 puntos de daño durante cada una de las Standby Phases de tu adversario.",
    "category": ["Control", "Damage LP"]
  },
  "Cestus of Dagla": {
    "id": "28106077",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Cestus of Dagla",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Sólo puedes equipar esta carta a un monstruo de Tipo Hada. Éste gana 500 ATK. Si éste inflige daño de batalla a tu adversario: tú ganas LP iguales al daño infligido.",
    "category": ["Change ATK/DEF", "Recover LP"]
  },
  "Fuhma Shuriken": {
    "id": "09373534",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Fuhma Shuriken",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Sólo puedes equipar esta carta a un monstruo <b>Ninja</b>. Éste gana 700 ATK. Cuando esta carta es mandada del Campo al Cementerio: inflige 700 puntos de daño a tu adversario.",
    "category": ["Change ATK/DEF", "Damage LP"]
  },
  "Opti-Camouflage Armor": {
    "id": "44762290",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Opti-Camouflage Armor",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Esta carta sólo puede ser equipada a un monstruo de Nivel 1. Un monstruo equipado con esta carta puede atacar los Life Points de tu adversario directamente.",
    "category": ["Direct Attack"]
  },
  "Amplifier": {
    "id": "00303660",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Amplifier",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Esta carta sólo puede ser equipada a <b>Jinzo</b>. Mientras esta carta esté equipada, los efectos de las Cartas de Trampa controladas por el controlador del monstruo equipado no son negadas por el efecto del monstruo equipado. Cuando esta carta es retirada del Campo, destruye el monstruo equipado. La activación y el efecto de esta carta no pueden ser negados por ninguna carta.",
    "category": ["Negate Effect"]
  },
  "Sword of the Soul-Eater": {
    "id": "05371656",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Sword of the Soul-Eater",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Sólo puedes equipar esta carta a un Monstruo Normal de Nivel 3 o inferior en tu Campo. Cuando activas esta carta, ofrece todos tus Monstruos Normales (excepto fichas) en tu Campo, excepto el monstruo equipado como Sacrificios. Aumenta el ATK del monstruo equipado en 1000 puntos por cada Monstruo Normal que hayas ofrecido como Sacrificio.",
    "category": ["Change ATK/DEF"]
  },
  "Fusion Weapon": {
    "id": "27967615",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Fusion Weapon",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Esta carta solo puede ser equipada a un Monstruo de Fusión de Nivel 6 o menos. Aumenta el ATK y la DEF del monstruo equipado en 1500 puntos.",
    "category": ["Change ATK/DEF", "Fusion"]
  },
  "Ritual Weapon": {
    "id": "54351224",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Ritual Weapon",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Esta carta sólo puede ser equipada a un Monstruo de Ritual de Nivel 6 o menos. Aumenta el ATK y la DEF del monstruo equipado en 1500 puntos.",
    "category": ["Change ATK/DEF", "Ritual"]
  },
  "Necklace of Command": {
    "id": "48576971",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Necklace of Command",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Cuando un monstruo en tu Campo equipado con esta carta es destruido como resultado de una batalla y esta carta es mandada al Cementerio, selecciona y activa 1 de los siguientes efectos:<br>● Roba 1 carta de tu Deck.<br>● Descarta 1 carta al azar de la mano de tu adversario al Cementerio.",
    "category": ["Destroy Hand", "Draw"]
  },
  "Flint": {
    "id": "75560629",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Flint",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Nadie puede cambiar la posición de batalla o declarar un ataque con el monstruo equipado con esta carta. Disminuye el ATK del monstruo equipado en 300 puntos. Si el monstruo equipado es destruido, selecciona 1 monstruo en el Campo y equípalo con esta carta.",
    "category": ["Change ATK/DEF", "Attack Restriction", "Position"]
  },
  "Ballista of Rampart Smashing": {
    "id": "00242146",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Ballista of Rampart Smashing",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Si un monstruo equipado con esta carta ataca a un monstruo boca abajo en Posición de Defensa, aumenta el ATK del monstruo equipado en 1500 puntos.",
    "category": ["Change ATK/DEF"]
  },
  "Fulfillment of the Contract": {
    "id": "48206762",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Fulfillment of the Contract",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Paga 800 Life Points. Selecciona 1 Monstruo de Ritual de tu Cementerio, Invócalo de Modo Especial y equípalo con esta carta. Cuando esta carta es destruida, retira el monstruo equipado del juego.",
    "category": ["Special Summon", "Ritual"]
  },
  "Re-Fusion": {
    "id": "74694807",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Re-Fusion",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Paga 800 Life Points. Selecciona 1 Monstruo de Fusión de tu Cementerio, Invócalo mediante una Invocación Especial en tu Campo y equípalo con esta carta. Cuando esta carta es destruida, retira el monstruo equipado del juego.",
    "category": ["Special Summon", "Fusion"]
  },
  "Legendary Black Belt": {
    "id": "96458440",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Legendary Black Belt",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Solo puedes equipar esta carta a <b>Chu-Ske the Mouse Fighter</b>, <b>Monk Fighter</b> o <b>Master Monk</b>. Cuando el monstruo equipado destruye el monstruo de tu adversario como resultado de una batalla y lo manda al Cementerio, inflige daño a los Life Points de tu adversario igual a la DEF del monstruo destruido.",
    "category": ["Damage LP"]
  },
  "Nitro Unit": {
    "id": "23842445",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Nitro Unit",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Sólo puedes equipar esta carta a un monstruo en el Campo de tu adversario. Cuando un monstruo destruye el monstruo equipado como resultado de una batalla y lo manda al Cementerio, inflige daño a los Life Points de tu adversario igual al ATK del monstruo equipado.",
    "category": ["Damage LP"]
  },
  "Elf's Light": {
    "id": "39897277",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Elf's Light",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Un monstruo de LUZ equipado con esta carta aumenta su ATK en 400 puntos y disminuye su DEF en 200 puntos.",
    "category": ["Change ATK/DEF"]
  },
  "Steel Shell": {
    "id": "02370081",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Steel Shell",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Un monstruo de AGUA equipado con esta carta aumenta su ATK en 400 puntos y disminuye su DEF en 200 puntos.",
    "category": ["Change ATK/DEF"]
  },
  "Burning Spear": {
    "id": "18937875",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Burning Spear",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Un monstruo de FUEGO equipado con esta carta aumenta su ATK en 400 puntos y disminuye su DEF en 200 puntos.",
    "category": ["Change ATK/DEF"]
  },
  "Gust Fan": {
    "id": "55321970",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Gust Fan",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Un monstruo de VIENTO equipado con esta carta aumenta su ATK en 400 puntos y disminuye su DEF en 200 puntos.",
    "category": ["Change ATK/DEF"]
  },
  "Sword of Dark Destruction": {
    "id": "37120512",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Sword of Dark Destruction",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Un monstruo de OSCURIDAD equipado con esta carta aumenta su ATK en 400 puntos y disminuye su DEF en 200 puntos.",
    "category": ["Change ATK/DEF"]
  },
  "Invigoration": {
    "id": "98374133",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Invigoration",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Un monstruo de TIERRA equipado con esta carta aumenta su ATK en 400 puntos y disminuye su DEF en 200 puntos.",
    "category": ["Change ATK/DEF"]
  },
  "Salamandra": {
    "id": "32268901",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Salamandra",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Sólo puedes equipar esta carta a un monstruo de FUEGO. Éste gana 700 ATK.",
    "category": ["Change ATK/DEF"]
  },
  "Sword of Dragon's Soul": {
    "id": "61405855",
    "card-type": "equip-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Sword of Dragon's Soul",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Esta carta solo puede ser equipada a un monstruo de Tipo Guerrero. Un monstruo equipado con esta carta aumenta su ATK en 700 puntos. Un monstruo de Tipo Dragón que batalle con el monstruo equipado con esta carta es destruido al final de la Battle Phase. (El cálculo de daño se aplica normalmente).",
    "category": ["Change ATK/DEF"]
  }
};