const spellcontinuousDetailed = {
  "7": {
    "id": "67048711",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "7",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If you control 3 \"7\": Draw 3 cards, then destroy all \"7\" on the field. When this card is sent from the field to your Graveyard: Gain 700 Life Points.",
    "category": ["Draw", "Recover LP"]
  },
  "Gravekeeper's Servant": {
    "id": "16762927",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Gravekeeper's Servant",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Your opponent must send 1 card from the top of their Deck to the Graveyard to declare an attack.",
    "category": ["Control"]
  },
  "Toll": {
    "id": "82003859",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Toll",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Each player must pay 500 Life Points to declare an attack.",
    "category": ["Control"]
  },
  "Chain Energy": {
    "id": "79323590",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Chain Energy",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Cada jugador debe pagar 500 Life Points por carta para Invocar mediante una Invocación Normal, Invocación Especial, Colocar o activar cartas de sus manos.",
    "category": ["Control"]
  },
  "Toon World": {
    "id": "15259703",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Toon World",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Activate this card by paying 1000 Life Points.",
    "category": ["Toon"]
  },
  "Messenger of Peace": {
    "id": "44656491",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Messenger of Peace",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Monsters with 1500 or more ATK cannot declare an attack. Once per turn, during your Standby Phase, pay 100 Life Points or destroy this card.",
    "category": ["Control", "Battle Protection"]
  },
  "Inspection": {
    "id": "16227556",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Inspection",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "During your opponent's Standby Phase: You can pay 500 Life Points; you opponent randomly reveals 1 card in their hand.",
    "category": ["Control"]
  },
  "Prohibition": {
    "id": "43711255",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Prohibition",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Activate by declaring 1 card name. Cards with that name, and their effects, cannot be used. Cards already on the field are not affected (including face-down cards).",
    "category": ["Control"]
  },
  "Burning Land": {
    "id": "24294108",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Burning Land",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When this card is activated: Destroy all Fields on the field. Once per turn, during the Standby Phase: The turn player takes 500 damage.",
    "category": ["Destroy S/T", "Damage LP"]
  },
  "Ground Collapse": {
    "id": "90502999",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Ground Collapse",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Activate by targeting 2 Monster Zones on the field; neither player can use those targeted zones. You cannot target an occupied zone.",
    "category": ["Control"]
  },
  "Insect Barrier": {
    "id": "23615409",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Insect Barrier",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Insect monsters your opponent controls cannot declare an attack.",
    "category": ["Control"]
  },
  "Mask of Dispel": {
    "id": "20765952",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Mask of Dispel",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Activate this card by targeting 1 face-up Spell on the field. Once per turn, during your Standby Phase: Inflict 500 damage to the controller of that target. When that target leaves the field, destroy this card.",
    "category": ["Damage LP"]
  },
  "Jam Breeding Machine": {
    "id": "21770260",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Jam Breeding Machine",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Once per turn, during your Standby Phase: Special Summon 1 \"Slime Token\" (Aqua/WATER/LEVEL 1/ATK 500/DEF 500) in Attack Position. You cannot Summon any monsters, except \"Slime Tokens\" (but you can Set).",
    "category": ["Special Summon", "Token"]
  },
  "Infinite Cards": {
    "id": "94163677",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Infinite Cards",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "There is no limit to the hand size for each player.",
    "category": ["Control"]
  },
  "Card of Safe Return": {
    "id": "57953380",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Card of Safe Return",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Cuando un monstruo es Invocado mediante una Invocación Especial de tu Cementerio al Campo, puedes robar 1 carta de tu Deck.",
    "category": ["Draw"]
  },
  "Spirit Message I": {
    "id": "31893528",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Spirit Message \"I\"",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "This card can only be placed on the field by the effect of \"Destiny Board\".",
    "category": ["Win Condition"]
  },
  "Spirit Message N": {
    "id": "67287533",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Spirit Message \"N\"",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "This card can only be placed on the field by the effect of \"Destiny Board\".",
    "category": ["Win Condition"]
  },
  "Spirit Message A": {
    "id": "94772232",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Spirit Message \"A\"",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "This card can only be placed on the field by the effect of \"Destiny Board\".",
    "category": ["Win Condition"]
  },
  "Spirit Message L": {
    "id": "30170981",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Spirit Message \"L\"",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "This card can only be placed on the field by the effect of \"Destiny Board\".",
    "category": ["Win Condition"]
  },
  "The Dark Door": {
    "id": "30606547",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "The Dark Door",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Only 1 monster can attack during each Battle Phase.",
    "category": ["Control"]
  },
  "Vengeful Bog Spirit": {
    "id": "95220856",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Vengeful Bog Spirit",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Monsters cannot attack the turn they are Summoned.",
    "category": ["Control"]
  },
  "The A. Forces": {
    "id": "00403847",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "The A. Forces",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "All Warrior monsters you control gain 200 ATK for each Warrior or Spellcaster monster you control.",
    "category": ["Change ATK/DEF"]
  },
  "Spring of Rebirth": {
    "id": "94425169",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Spring of Rebirth",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Each time a monster(s) is return from the field to the hand, gain 700 Life Points.",
    "category": ["Recover LP"]
  },
  "Spiritual Energy Settle Machine": {
    "id": "99173029",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Spiritual Energy Settle Machine",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Spirit monsters do not activate their effects that return to the hand during the End Phase. When this card leaves the field, return all Spirit monsters on the field to the hand. Once per turn, during your End Phase, discard 1 card to the Graveyard or destroy this card.",
    "category": ["Spirit"]
  },
  "Second Coin Toss": {
    "id": "36562627",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Second Coin Toss",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When a coin toss is performed, you can choose to redo the coin toss. (If the toss involved multiple coin flips, redo all of them.) You can only use the effect of \"Second Coin Toss\" once per turn.",
    "category": ["Gamble"]
  },
  "Convulsion of Nature": {
    "id": "62966332",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Convulsion of Nature",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Both players must turn their respective Decks upside down and proceed with the current Duel.",
    "category": ["Control"]
  },
  "Mirage of Nightmare": {
    "id": "41482598",
    "card-type": "continuous-spell",
    "banlist": "Banned",
    "Genesys": 0,
    "name": "Mirage of Nightmare",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Una vez por turno, durante la Standby Phase de tu adversario: roba cartas hasta que tu mano tenga 4 cartas. Si lo haces, durante tu próxima Standby Phase: descarta al azar el mismo número de cartas que robaste (o toda tu mano, si no tienes cartas suficientes).",
    "category": ["Draw", "Destroy Hand"]
  },
  "Call of the Mummy": {
    "id": "04861205",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Call of the Mummy",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Si no hay ningún monstruo en tu Campo, puedes Invocar mediante una Invocación Especial 1 monstruo de Tipo Zombi de tu mano. Puedes usar este efecto solo una vez por turno.",
    "category": ["Special Summon"]
  },
  "Card Shuffle": {
    "id": "12183332",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Card Shuffle",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Once per turn, you can pay 300 Life Points; Shuffle either your or your opponent's Deck.",
    "category": ["Send to Deck"]
  },
  "Dark Room of Nightmare": {
    "id": "85562745",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dark Room of Nightmare",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Cada vez que tu adversario reciba daño por el efecto de una carta, excepto por <b>Habitación Oscura de Pesadilla</b>, inflige 300 puntos de daño a tu adversario.",
    "category": ["Damage LP"]
  },
  "Dark Snake Syndrome": {
    "id": "47233801",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dark Snake Syndrome",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Once per turn, during your Standby Phase: Inflict damage to both players. This damage begins at 200 and is doubled during each of your following Standby Phases.",
    "category": ["Damage LP"]
  },
  "Banner of Courage": {
    "id": "10012614",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Banner of Courage",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "All monsters you control gain 200 ATK during your Battle Phase only.",
    "category": ["Change ATK/DEF"]
  },
  "Frontline Base": {
    "id": "46181000",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Frontline Base",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Once per turn: You can Special Summon 1 Level 4 or lower Union monster from your hand.",
    "category": ["Special Summon", "Union"]
  },
  "Kaiser Colosseum": {
    "id": "35059553",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Kaiser Colosseum",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "While you control 1 or more monsters, your opponent cannot control more monsters than you do. Cards that are already on the field before this card's activation are not affected by this effect.",
    "category": ["Control"]
  },
  "Kishido Spirit": {
    "id": "60519422",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Kishido Spirit",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Monsters you control cannot be destroyed by battle with monsters with the same ATK.",
    "category": ["Battle Protection"]
  },
  "Wave-Motion Cannon": {
    "id": "38992735",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Wave-Motion Cannon",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "During your Main Phase: You can send this card to the Graveyard; inflict 1000 damage to your opponent for each of your Standby Phases that have passed since this card was activated.",
    "category": ["Damage LP"]
  },
  "Continuous Destruction Punch": {
    "id": "68057622",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Continuous Destruction Punch",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "At the end of damage calculation, if a Defense Position monster you control is attacked and its DEF is higher than the attacking monster's ATK: Destroy the attacking monster.",
    "category": ["Destroy Monster"]
  },
  "Mass Driver": {
    "id": "34906152",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Mass Driver",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "You can Tribute 1 monster; inflict 400 damage to your opponent.",
    "category": ["Damage LP"]
  },
  "Senri Eye": {
    "id": "60391791",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Senri Eye",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Once per turn, during your Standby Phase: You can pay 100 Life Points; look at the top card of your opponent's Deck.",
    "category": ["Control"]
  },
  "Precious Cards from Beyond": {
    "id": "68304813",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Precious Cards from Beyond",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When you Tribute Summon a monster using 2 or more Tributes: Draw 2 cards.",
    "category": ["Draw"]
  },
  "Morale Boost": {
    "id": "93671934",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Morale Boost",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Each time a player equips an Equip Spell, the controller of that Equip gains 1000 Life Points. Each time an Equip Spell leaves the field, the controller of that Equip takes 1000 damage.",
    "category": ["Recover LP", "Damage LP"]
  },
  "Non-Spellcasting Area": {
    "id": "20065549",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Non-Spellcasting Area",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "All face-up non-Effect Monsters on the field are unaffected by other Spell effects.",
    "category": ["Unaffected"]
  },
  "Different Dimension Gate": {
    "id": "56460688",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Different Dimension Gate",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Activate this card by targeting 1 monster on each side of the field; banish them. When this card is destroyed and sent to the Graveyard: Return those banished monsters to the field in the same battle positions they were in.",
    "category": ["Banish"]
  },
  "Archfiend's Oath": {
    "id": "22796548",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Archfiend's Oath",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Once per turn: You can pay 500 Life Points, then declare 1 card name; excavate the top card of your Deck, and if it is the declared card, add it to your hand. Otherwise, send it to the Graveyard.",
    "category": ["Send to Hand"]
  },
  "Heart of the Underdog": {
    "id": "35762283",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Heart of the Underdog",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "During your Draw Phase, when you draw a Normal Monster(s): You can reveal it; draw 1 card.",
    "category": ["Draw"]
  },
  "Stumbling": {
    "id": "34646691",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Stumbling",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If a monster(s) is Summoned in Attack Position: Change it to Defense Position.",
    "category": ["Position"]
  },
  "Yellow Luster Shield": {
    "id": "04542651",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Yellow Luster Shield",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "All monsters you control gain 300 DEF.",
    "category": ["Change ATK/DEF"]
  },
  "D.D. Borderline": {
    "id": "60912752",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "D.D. Borderline",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "While there are no Spells in your Graveyard, neither player can conduct their Battle Phase.",
    "category": ["Control", "Battle Protection", "Attack Restriction"]
  },
  "Recycle": {
    "id": "96316857",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Recycle",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "During your Standby Phase: You can pay 300 Life Points, then target 1 Spell or Trap in your Graveyard; place it on the bottom of your Deck.",
    "category": ["Send to Deck"]
  },
  "Soul Absorption": {
    "id": "68073522",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Soul Absorption",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If a card(s) is banished: Gain 500 Life Points for each.",
    "category": ["Recover LP"]
  },
  "Weapon Change": {
    "id": "10035717",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Weapon Change",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Once per turn, during your Standby Phase: You can pay 700 Life Points, then target 1 Warrior or Machine monster you control; switch the current ATK and DEF of that target, until the end of your opponent's next turn.",
    "category": ["Change ATK/DEF"]
  },
  "Talisman of Trap Sealing": {
    "id": "19312169",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Talisman of Trap Sealing",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Activate this card only if you control \"Sealmaster Meisei\". Traps cannot be activated. Negate all Trap effects on the field. If you do not control \"Sealmaster Meisei\", destroy this card.",
    "category": ["Negate Effect", "Control"]
  },
  "Dust Barrier": {
    "id": "31476755",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dust Barrier",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Destroy this card during your 2nd Standby Phase after activation. Face-up Normal Monsters on the field are unaffected by your opponent's Spells.",
    "category": ["Unaffected"]
  },
  "Spell Economics": {
    "id": "04259068",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Spell Economics",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "You do not pay Life Points to activate Spells.",
    "category": ["Control"]
  },
  "Blessings of the Nile": {
    "id": "30653113",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Blessings of the Nile",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Each time card(s) are discarded from your hand to the Graveyard by an opponent's card effect, gain 1000 Life Points.",
    "category": ["Recover LP"]
  },
  "Level Limit - Area B": {
    "id": "03136426",
    "card-type": "continuous-spell",
    "banlist": "Semi-limited",
    "Genesys": 0,
    "name": "Level Limit - Area B",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Todos los monstruos de Nivel 4 o superior boca arriba en el Campo son cambiados a Posición de Defensa.",
    "category": ["Control", "Battle Protection", "Position"]
  },
  "The Third Sarcophagus": {
    "id": "78697395",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "The Third Sarcophagus",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "This card can only be placed on the field by the effect of \"The First Sarcophagus\".",
    "category": []
  },
  "The Second Sarcophagus": {
    "id": "04081094",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "The Second Sarcophagus",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "This card can only be placed on the field by the effect of \"The First Sarcophagus\".",
    "category": []
  },
  "Ectoplasmer": {
    "id": "97342942",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Ectoplasmer",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Once per turn, during the End Phase: The turn player must Tribute 1 face-up monster, and if they do, inflict damage to their opponent equal to half the original ATK of the Tributed monster.",
    "category": ["Damage LP"]
  },
  "Two-Man Cell Battle": {
    "id": "25578802",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Two-Man Cell Battle",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Once per turn. during the End Phase: The turn player can Special Summon 1 Level 4 Normal Monster from their hand.",
    "category": ["Special Summon"]
  },
  "Mokey Mokey Smackdown": {
    "id": "01965724",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Mokey Mokey Smackdown",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If a face-up Fairy monster you control is destroyed while you control \"Mokey Mokey\", until the end of this turn the ATK of each \"Mokey Mokey\" you control become 3000.",
    "category": ["Change ATK/DEF"]
  },
  "Lighten the Load": {
    "id": "37231841",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Lighten the Load",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Once per turn: You can shuffle 1 Level 7 or higher monster from your hand into your Deck; draw 1 card.",
    "category": ["Draw", "Send to Deck"]
  },
  "Poison Fangs": {
    "id": "76539047",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Poison Fangs",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When a Beast monster you control inflicts battle damage to your opponent: Inflict 500 damage to your opponent.",
    "category": ["Damage LP"]
  },
  "Spell Absorption": {
    "id": "51481927",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Spell Absorption",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Each time a Spell is activated, gain 500 Life Points when that Spell resolves.",
    "category": ["Recover LP"]
  },
  "Swords of Concealing Light": {
    "id": "12923641",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Swords of Concealing Light",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Destroy this card during your 2nd Standby Phase after activation. When this card resolves, change all monsters your opponent controls to face-down Defense Position. Monsters your opponent controls cannot change their battle positions.",
    "category": ["Control", "Position"]
  },
  "Spiral Spear Strike": {
    "id": "49328340",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Spiral Spear Strike",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If \"Gaia The Fierce Knight\", \"Swift Gaia the Fierce Knight\", or \"Gaia the Dragon Champion\" you control attacks a Defense Position monster, inflict piercing battle damage. If \"Gaia the Dragon Champion\" inflicts battle damage with this effect: Draw 2 cards, then discard 1 card.",
    "category": ["Piercing", "Draw"]
  },
  "Shifting Shadows": {
    "id": "59237154",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Shifting Shadows",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Once per turn: You can pay 300 Life Points; rearrange (but do not reveal) all face-down Defense Position monsters you control in the Monster Zones they were in.",
    "category": ["Position"]
  },
  "Impenetrable Formation": {
    "id": "96631852",
    "card-type": "continuous-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Impenetrable Formation",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Activate this card by targeting 1 monster you control. While you control 2 or more monsters, and all monsters you control are in Defense Position, the targeted monster gains 700 DEF. When the targeted monster leaves the field, destroy this card.",
    "category": ["Change ATK/DEF"]
  }
};