const spellquickDetailed = {
  "Tailor of the Fickle": {
    "id": "43641473",
    "card-type": "quick-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Tailor of the Fickle",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 Equip equipped to a monster and target another correct target: Switch that Equip to the new target.",
    "category": ["Control"]
  },
  "Rush Recklessly": {
    "id": "70046172",
    "card-type": "quick-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Rush Recklessly",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 face-up monster on the field; it gains 700 ATK, until the end of this turn.",
    "category": ["Change ATK/DEF"]
  },
  "The Reliable Guardian": {
    "id": "16430187",
    "card-type": "quick-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "The Reliable Guardian",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 face-up monster on the field; it gains 700 DEF, until the end of this turn.",
    "category": ["Change ATK/DEF"]
  },
  "Mystical Space Typhoon": {
    "id": "05318639",
    "card-type": "quick-spell",
    "banlist": "Limited",
    "Genesys": 0,
    "name": "Mystical Space Typhoon",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Destruye 1 Carta Mágica o de Trampa en el Campo.",
    "category": ["Destroy S/T"]
  },
  "Limiter Removal": {
    "id": "23171610",
    "card-type": "quick-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Limiter Removal",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Double the ATK of all Machine monsters you currently control, until the end of this turn. During the End Phase of this turn, destroy those monsters.",
    "category": ["Change ATK/DEF"]
  },
  "Monster Recovery": {
    "id": "93108433",
    "card-type": "quick-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Monster Recovery",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 monster you control that is owned by you; if it is still on the field, shuffle it and your entire hand into the Deck, also, after that, draw cards equal to the number of cards you shuffled from your hand into the Deck by this effect. (You cannot activate this card if you have a card in your hand that is owned by your opponent.)",
    "category": ["Send to Deck", "Draw"]
  },
  "Offerings to the Doomed": {
    "id": "19230407",
    "card-type": "quick-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Offerings to the Doomed",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 face-up monster on the field; destroy it, also skip your next Draw Phase.",
    "category": ["Destroy Monster"]
  },
  "De-Fusion": {
    "id": "95286165",
    "card-type": "quick-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "De-Fusion",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 Fusion Monster on the field; return it to the Fusion Deck, then, if all the Fusion Materials that were used for its Fusion Summon are in your Graveyard, you can Special Summon as many of them as possible.",
    "category": ["Fusion", "Special Summon"]
  },
  "Emergency Provisions": {
    "id": "53046408",
    "card-type": "quick-spell",
    "banlist": "Semi-limited",
    "Genesys": 0,
    "name": "Emergency Provisions",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Manda cualquier número de otras Cartas Mágicas o de Trampa que controles al Cementerio. Gana 1000 Life Points por cada carta mandada.",
    "category": ["Recover LP"]
  },
  "Super Rejuvenation": {
    "id": "27770341",
    "card-type": "quick-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Super Rejuvenation",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "During the End Phase of the turn this card was activated, draw a number of cards equal to the combined number of Dragon monsters you discarded or Tributed from your hand or your side of the field this turn.",
    "category": ["Draw"]
  },
  "Book of Moon": {
    "id": "14087893",
    "card-type": "quick-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Book of Moon",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Voltea 1 monstruo boca arriba en el Campo a Posición de Defensa boca abajo.",
    "category": ["Position"]
  },
  "Pyramid Energy": {
    "id": "76754619",
    "card-type": "quick-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Pyramid Energy",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Activate 1 of the following effects: ● All face-up monsters you currently control gain 200 ATK, until the end of this turn. ● All face-up monsters you currently control gain 500 DEF, until the end of this turn.",
    "category": ["Change ATK/DEF"]
  },
  "Combination Attack": {
    "id": "08964854",
    "card-type": "quick-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Combination Attack",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "During the Battle Phase: Target 1 monster that battled this turn and is equipped with a Union monster; Special Summon the Union monster, and if you do, the target can attack again this turn.",
    "category": ["Union", "Special Summon", "Multi Attack"]
  },
  "Poison of the Old Man": {
    "id": "08842266",
    "card-type": "quick-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Poison of the Old Man",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Activate 1 of these effects; ● Gain 1200 Life Points. ● Inflict 800 damage to your opponent.",
    "category": ["Recover LP", "Damage LP"]
  },
  "Jar Robber": {
    "id": "33784505",
    "card-type": "quick-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Jar Robber",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When \"Pot of Greed\" is activated: Negate its effect, and if you do, draw 1 card.",
    "category": ["Negate Effect", "Draw"]
  },
  "My Body as a Shield": {
    "id": "69279219",
    "card-type": "quick-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "My Body as a Shield",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When your opponent activates a Spell or Trap, or monster effect that would destroy a monster(s) on the field: Pay 1500 Life Points; negate the activation, and if you do, destroy it.",
    "category": ["Negate Activation", "Destroy S/T", "Destroy Monster"]
  },
  "Pigeonholing Books of Spell": {
    "id": "96677818",
    "card-type": "quick-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Pigeonholing Books of Spell",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "(This card is always treated as a \"Spellbook\" card.) Look at the top 3 cards of your Deck, then place them on the top of the Deck in any order.",
    "category": ["Send to Deck"]
  },
  "A Deal with Dark Ruler": {
    "id": "06850209",
    "card-type": "quick-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "A Deal with Dark Ruler",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If a Level 8 or higher monster under your control was sent to the Graveyard this turn: Special Summon 1 \"Berserk Dragon\" from your hand or Deck.",
    "category": ["Special Summon"]
  },
  "Reload": {
    "id": "22589918",
    "card-type": "quick-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Reload",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Añade tu mano a tu Deck y barajalo. Entonces roba el mismo número de cartas que añadiste a tu Deck.",
    "category": ["Send to Deck", "Draw"]
  },
  "Dedication through Light and Darkness": {
    "id": "69542930",
    "card-type": "quick-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dedication through Light and Darkness",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Tribute 1 \"Dark Magician\"; Special Summon 1 \"Dark Magician of Chaos\" from your hand, Deck, or Graveyard.",
    "category": ["Special Summon"]
  },
  "Mystik Wok": {
    "id": "80161395",
    "card-type": "quick-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Mystik Wok",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Ofrece 1 monstruo en tu Campo como Sacrificio. Selecciona el ATK o la DEF del Monstruo de Sacrificio, y aumenta tus Life Points en la cantidad seleccionada.",
    "category": ["Recover LP"]
  },
  "Enemy Controller": {
    "id": "98045062",
    "card-type": "quick-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Enemy Controller",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Activate 1 of these effects. ● Target 1 face-up monster your opponent controls; change its battle position. ● Tribute 1 monster, then target 1 face-up monster your opponent controls; take control of that target, until the End Phase.",
    "category": ["Control", "Position"]
  },
  "Order to Charge": {
    "id": "78986941",
    "card-type": "quick-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Order to Charge",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 non-Token Normal Monster you control; Tribute that Normal Monster, and if you do, destroy 1 monster your opponent controls.",
    "category": ["Destroy Monster"]
  },
  "Soul Reversal": {
    "id": "78864369",
    "card-type": "quick-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Soul Reversal",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 Flip monster in your Graveyard; place it on the top of your Deck.",
    "category": ["Flip", "Send to Deck"]
  },
  "Mind Wipe": {
    "id": "52817046",
    "card-type": "quick-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Mind Wipe",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If your opponent has 3 or less cards in their hand: They shuffle their entire hand into the Deck, then draws the same number of cards.",
    "category": ["Send to Deck", "Draw"]
  },
  "Serial Spell": {
    "id": "49398568",
    "card-type": "quick-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Serial Spell",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When you activate a Normal Spell: Discard all the cards in your hand to the Graveyard (min. 1); The effect of this card becomes the same as that Normal Spell.",
    "category": []
  },
  "Malice Dispersion": {
    "id": "13626450",
    "card-type": "quick-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Malice Dispersion",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Discard 1 card; destroy all Continuous Traps on the field.",
    "category": ["Destroy S/T"]
  },
  "The Big March of Animals": {
    "id": "01689516",
    "card-type": "quick-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "The Big March of Animals",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "All face-up Beast monsters you currently control gain 200 ATK for each Beast monster you currently control, until the end of this turn.",
    "category": ["Change ATK/DEF"]
  },
  "Inferno Tempest": {
    "id": "14391920",
    "card-type": "quick-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Inferno Tempest",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When you take 3000 or more battle damage from 1 attack: Banish all monsters in each player's Deck and Graveyard.",
    "category": ["Banish"]
  },
  "Scapegoat": {
    "id": "73915051",
    "card-type": "quick-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Scapegoat",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Cuando activas esta carta, no puedes Invocar ningún monstruo mediante una Invocación Normal, Invocación de Volteo o Invocación Especial en el mismo turno. Invoca mediante una Invocación Especial 4 <b>Fichas de Oveja</b> (Tipo Bestia/TIERRA/Nivel 1/ATK 0/DEF 0) en Posición de Defensa en tu Campo. Las fichas no se pueden usar como Sacrificio en una Invocación de Sacrificio.",
    "category": ["Special Summon", "Token"]
  },
  "Graceful Dice": {
    "id": "74137509",
    "card-type": "quick-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Graceful Dice",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Roll a six-sided dice. All monsters you currently control gain ATK and DEF equal to the result x 100, until the end of this turn.",
    "category": ["Gamble", "Change ATK/DEF"]
  },
  "Sebek's Blessing": {
    "id": "22537443",
    "card-type": "quick-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Sebek's Blessing",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If a monster you control inflicts battle damage to your opponent by a direct attack: Gain the same amount of Life Points.",
    "category": ["Recover LP"]
  }
};