const spellfieldDetailed = {
  "Forest": {
    "id": "87430998",
    "card-type": "field-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Forest",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "All Insect, Beast, Plant, and Beast-Warrior monsters on the field gain 200 ATK and DEF.",
    "category": ["Change ATK/DEF"]
  },
  "Wasteland": {
    "id": "23424603",
    "card-type": "field-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Wasteland",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "All Dinosaur, Zombie, and Rock monsters on the field gain 200 ATK and DEF.",
    "category": ["Change ATK/DEF"]
  },
  "Mountain": {
    "id": "50913601",
    "card-type": "field-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Mountain",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "All Dragon, Winged Beast, and Thunder monsters on the field gain 200 ATK and DEF.",
    "category": ["Change ATK/DEF"]
  },
  "Sogen": {
    "id": "86318356",
    "card-type": "field-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Sogen",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "All Warrior and Beast-Warrior monsters on the field gain 200 ATK and DEF.",
    "category": ["Change ATK/DEF"]
  },
  "Umi": {
    "id": "22702055",
    "card-type": "field-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Umi",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "All Fish, Sea Serpent, Thunder, and Aqua monsters on the field gain 200 ATK and DEF, also all Machine and Pyro monsters on the field lose 200 ATK and DEF.",
    "category": ["Change ATK/DEF"]
  },
  "Yami": {
    "id": "59197169",
    "card-type": "field-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Yami",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "All Fiend and Spellcaster monsters on the field gain 200 ATK and DEF, also all Fairy monsters on the field lose 200 ATK and DEF.",
    "category": ["Change ATK/DEF"]
  },
  "Chorus of Sanctuary": {
    "id": "81380218",
    "card-type": "field-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Chorus of Sanctuary",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "All Defense Position monsters on the field gain 500 DEF.",
    "category": ["Change ATK/DEF"]
  },
  "Gaia Power": {
    "id": "56594520",
    "card-type": "field-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Gaia Power",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "All EARTH monsters on the field gain 500 ATK and lose 400 DEF.",
    "category": ["Change ATK/DEF"]
  },
  "Umiiruka": {
    "id": "82999629",
    "card-type": "field-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Umiiruka",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "All WATER monsters on the field gain 500 ATK and lose 400 DEF.",
    "category": ["Change ATK/DEF"]
  },
  "Molten Destruction": {
    "id": "19384334",
    "card-type": "field-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Molten Destruction",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Aumenta el ATK de todos los monstruos de FUEGO en 500 puntos y disminuye su DEF en 400 puntos.",
    "category": ["Change ATK/DEF"]
  },
  "Rising Air Current": {
    "id": "45778932",
    "card-type": "field-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Rising Air Current",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "All WIND monsters on the field gain 500 ATK and lose 400 DEF.",
    "category": ["Change ATK/DEF"]
  },
  "Luminous Spark": {
    "id": "81777047",
    "card-type": "field-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Luminous Spark",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "All LIGHT monsters on the field gain 500 ATK and lose 400 DEF.",
    "category": ["Change ATK/DEF"]
  },
  "Mystic Plasma Zone": {
    "id": "18161786",
    "card-type": "field-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Mystic Plasma Zone",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "All DARK monsters on the field gain 500 ATK and lose 400 DEF.",
    "category": ["Change ATK/DEF"]
  },
  "Fusion Gate": {
    "id": "33550694",
    "card-type": "field-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Fusion Gate",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "During the Main Phase: The turn player can Fusion Summon 1 Fusion Monster from their Fusion Deck, by banishing Fusion Materials listed on it from their hand or field.",
    "category": ["Fusion"]
  },
  "Array of Revealing Light": {
    "id": "69296555",
    "card-type": "field-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Array of Revealing Light",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Activate this card by declare 1 monster Type. Any monster of the declared Type cannot declare an attack during the turn it is Summoned.",
    "category": ["Attack Restriction"]
  },
  "A Legendary Ocean": {
    "id": "00295517",
    "card-type": "field-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "A Legendary Ocean",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "El nombre de esta carta se trata como <b>Umi</b>. Reduce en 1 el Nivel de todos los monstruos de AGUA en la mano y en el Campo de ambos jugadores. Aumenta el ATK y la DEF de todos los monstruos de AGUA en 200 puntos.",
    "category": ["Control", "Change ATK/DEF"]
  },
  "Necrovalley": {
    "id": "47355498",
    "card-type": "field-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Necrovalley",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "All \"Gravekeeper's\" monster gain 500 ATK and DEF. Cards in either player's Graveyard cannot be banished. Cards in either player's Graveyard cannot be affected by card effects, except for their own effects.",
    "category": ["Control", "Change ATK/DEF"]
  },
  "Pandemonium": {
    "id": "94585852",
    "card-type": "field-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Pandemonium",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Neither player has to pay Life Points during the Standby Phase for \"Archfiend\" monsters. When a player's \"Archfiend\" monster(s) is destroyed and sent to the Graveyard (except during the Damage Step): That player can add 1 \"Archfiend\" monster from their Deck to their hand that is a lower Level than the destroyed monster.",
    "category": ["Control", "Send to Hand", "Search"]
  },
  "The Sanctuary in the Sky": {
    "id": "56433456",
    "card-type": "field-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "The Sanctuary in the Sky",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Battle damage to the controller of a Fairy monster from a battle involving that monster becomes 0.",
    "category": ["Battle Protection"]
  },
  "Harpies' Hunting Ground": {
    "id": "75782277",
    "card-type": "field-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Harpies' Hunting Ground",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "All Winged Beast monsters on the field gain 200 ATK and DEF. If any \"Harpie Lady\" or \"Harpie Lady Sisters\" is Normal or Special Summoned: The player who conducted the Summon targets 1 Spell or Trap on the field; that player destroys it.",
    "category": ["Change ATK/DEF", "Destroy S/T"]
  },
  "Centrifugal Field": {
    "id": "01801154",
    "card-type": "field-spell",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Centrifugal Field",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When a Fusion Monster(s) is destroyed by a card effect and sent to the Graveyard: Its owner targets 1 Fusion Material Monster in their Graveyard that is listed on that Fusion Monster; that player Special Summons it.",
    "category": ["Fusion", "Special Summon"]
  }
};