const trapcontinuousDetailed = {
  "Dragon Capture Jar": {
    "id": "50045299",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dragon Capture Jar",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Change all Dragon monsters on the field to Defense Position, also they cannot change their battle positions.",
    "category": ["Position", "Control"]
  },
  "Robbin' Goblin": {
    "id": "88279736",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Robbin' Goblin",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If a monster you control inflicts battle damage to your opponent: Your opponent discards 1 random card.",
    "category": ["Destroy Hand"]
  },
  "Spellbinding Circle": {
    "id": "18807108",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Spellbinding Circle",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Activate this card by targeting 1 monster your opponent controls; it cannot attack or change its battle position. When that monster is destroyed, destroy this card.",
    "category": ["Attack Restriction", "Position"]
  },
  "The Eye of Truth": {
    "id": "34694160",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "The Eye of Truth",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Your opponent pays with their hand revealed. Once per turn, during your opponent's Standby Phase, if they have a Spell in their hand: They gain 1000 Life Points.",
    "category": ["Control", "Recover LP"]
  },
  "Call of the Haunted": {
    "id": "97077563",
    "card-type": "continuous-trap",
    "banlist": "Limited",
    "Genesys": 0,
    "name": "Call of the Haunted",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Selecciona 1 monstruo de tu Cementerio e Invocalo mediante una Invocación Especial en Posición de Ataque. Cuando esta carta es retirada del Campo, destruye el monstruo. Cuando ese monstruo es destruido, destruye esta carta.",
    "category": ["Special Summon"],
    "ruling": "Si el monstruo fue tributado, ésta carta seguirá boca arriba. <br> Si el monstruo fue cambiado a posición boca abajo, ésta carta seguirá boca arriba pero ya no estará vinculada al monstruo."
  },
  "Call of the Haunted 2": {
    "id": "97077563",
    "card-type": "continuous-trap",
    "banlist": "Limited",
    "Genesys": 0,
    "name": "Call of the Haunted",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Selecciona 1 monstruo de tu Cementerio e Invocalo mediante una Invocación Especial en Posición de Ataque. Cuando esta carta es retirada del Campo, destruye el monstruo. Cuando ese monstruo es destruido, destruye esta carta.",
    "category": ["Special Summon"],
    "ruling": "Si el monstruo fue tributado, ésta carta seguirá boca arriba. <br> Si el monstruo fue cambiado a posición boca abajo, ésta carta seguirá boca arriba pero ya no estará vinculada al monstruo."
  },
  "Mirror Wall": {
    "id": "22359980",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Mirror Wall",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When an opponent's monster declares an attack, halve its ATK. Once per turn, during your Standby Phase, pay 2000 Life Points or destroy this card.",
    "category": ["Battle Protection", "Attack Restriction"]
  },
  "Appropriate": {
    "id": "48539234",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Appropriate",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Activate this card when your opponent draws a card(s), except during the Draw Phase. Each time your opponent draws a card(s), except during the Draw Phase, draw 2 cards.",
    "category": ["Draw"]
  },
  "Forced Requisition": {
    "id": "74923978",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Forced Requisition",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Activate this card when you discard a card(s). Each time you discard a card(s), your opponent discards the same number of cards.",
    "category": ["Destroy Hand"]
  },
  "DNA Surgery": {
    "id": "74701381",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "DNA Surgery",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Activate this card by declaring 1 monster Type. All face-up monsters on the field become that Type.",
    "category": ["Control"]
  },
  "The Regulation of Tribe": {
    "id": "00296499",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "The Regulation of Tribe",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Activate this card by declaring 1 monster Type. Monsters of the declared Type cannot attack. Once per turn, during your Standby Phase, tribute 1 monster you control or destroy this card.",
    "category": ["Control"]
  },
  "Light of Intervention": {
    "id": "62867251",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Light of Intervention",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Neither player can Set monsters or change them face-down. If a monster would be Set, it must be Normal Summoned in face-up Defense Position.",
    "category": ["Control"]
  },
  "Respect Play": {
    "id": "08951260",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Respect Play",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Each player plays with their hand revealed during their turn.",
    "category": ["Control"]
  },
  "Minor Goblin Official": {
    "id": "01918087",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Minor Goblin Official",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Activate this card only if your opponent's Life Points are 3000 or less. Once per turn, during your opponent's Standby Phase: Inflict 500 damage to your opponent.",
    "category": ["Damage LP"]
  },
  "Solemn Wishes": {
    "id": "35346968",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Solemn Wishes",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Each time you Draw a card(s), gain 500 Life Points.",
    "category": ["Recover LP"]
  },
  "Skull Invitation": {
    "id": "98139712",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Skull Invitation",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Each time a card(s) is sent to the Graveyard, inflict 300 damage to its owner for each.",
    "category": ["Damage LP"]
  },
  "Infinite Dismissal": {
    "id": "54109233",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Infinite Dismissal",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Once per turn, during the End Phase: Destroy all Level 3 or lower monsters that were Normal Summoned or Flip Summoned this turn.",
    "category": ["Destroy Monster"]
  },
  "Gravity Bind": {
    "id": "85742772",
    "card-type": "continuous-trap",
    "banlist": "Semi-limited",
    "Genesys": 0,
    "name": "Gravity Bind",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Ningún monstruo de Nivel 4 o superior puede atacar. Sus posiciones puede ser cambiadas.",
    "category": ["Battle Protection", "Attack Restriction"]
  },
  "Type Zero Magic Crusher": {
    "id": "21237481",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Type Zero Magic Crusher",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "You can discard 1 Spell; inflict 500 damage to your opponent.",
    "category": ["Damage LP"]
  },
  "Imperial Order": {
    "id": "61740673",
    "card-type": "continuous-trap",
    "banlist": "Banned",
    "Genesys": 0,
    "name": "Imperial Order",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Mientras esta carta permanezca boca arriba en el Campo, niega los efectos de todas las Cartas Mágicas en el Campo. Paga 700 Life Points durante cada una de tus Standby Phases. Si no lo haces, destruye esta carta.",
    "category": ["Negate Effect"]
  },
  "Mask of Restrict": {
    "id": "29549364",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Mask of Restrict",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Neither player can Tribute cards.",
    "category": ["Control"]
  },
  "Tornado Wall": {
    "id": "18605135",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Tornado Wall",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Esta carta solo puede ser activada cuando <b>Umi</b> está boca arriba en el Campo. Mientras <b>Umi</b> permanezca boca arriba en el Campo, todo el daño de batalla infligido por los monstruos atacantes a tus Life Points se convierte en 0. Cuando <b>Umi</b> es retirado del Campo, destruye esta carta.",
    "category": ["Battle Protection"]
  },
  "Fairy Box": {
    "id": "21598948",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Fairy Box",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When your opponent's monster declares an attack: Toss a coin and call it. If you call it right, the attacking monster's ATK becomes 0, until the end of the Battle Phase. Once per turn, during your Standby Phase, pay 500 Life Points or destroy this card.",
    "category": ["Gamble", "Change ATK/DEF"]
  },
  "Jam Defender": {
    "id": "21558682",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Jam Defender",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When an opponent's monster attacks a monster you control: You can target 1 \"Revival Jam\" you control; switch the attack to that new target.",
    "category": ["Position"]
  },
  "Royal Command": {
    "id": "33950246",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Royal Command",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Flip monsters' effects cannot be activated, also their effects are negated.",
    "category": ["Negate Effect", "Flip"]
  },
  "Skull Lair": {
    "id": "06733059",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Skull Lair",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Once per chain: You can banish any number of monster from your Graveyard equal to Level of 1 face-up monster on the field; destroy 1 face-up monster on the field whose Level is equal to the number of the cards you banished.",
    "category": ["Banish", "Special Summon"]
  },
  "Graverobber's Retribution": {
    "id": "33737664",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Graverobber's Retribution",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Once per turn, during your Standby Phase: Inflict 100 damage to your opponent for each of your opponent's banished monsters.",
    "category": ["Damage LP"]
  },
  "Blind Destruction": {
    "id": "32015116",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Blind Destruction",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Once per turn, during your Standby Phase: Roll a six-sided die. If the result is 1-5, destroy all monsters on the field with the same Level as the number rolled. If it is 6, destroy all Level 6 and higher monsters on the field.",
    "category": ["Gamble", "Destroy Monster"]
  },
  "The Emperor's Holiday": {
    "id": "68400115",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "The Emperor's Holiday",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Negate all Equip effects on the field.",
    "category": ["Negate Effect"]
  },
  "Destiny Board": {
    "id": "94212438",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Destiny Board",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When this card and all 4 \"Spirit Message\" cards with different names are placed on your field, you win the Duel. Once per turn, during your opponent's End Phase: Place 1 \"Spirit Message\" card from your hand or Deck in your Spell & Trap Zone face-up, in the proper order of \"I\", \"N\", \"A\", and \"L\". When any \"Spirit Message\" card or \"Destiny Board\" you control leaves the field, send all \"Spirit Message\" cards and \"Destiny Board\" you control to the Graveyard.",
    "category": ["Win Condition"]
  },
  "Fatal Abacus": {
    "id": "77910045",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Fatal Abacus",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Each time a monster(s) is sent from the field to the Graveyard, inflict 500 damage per card to the respective owner.",
    "category": ["Damage LP"]
  },
  "Life Absorbing Machine": {
    "id": "14318794",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Life Absorbing Machine",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Once per turn, during your Standby Phase: Gain Life Points equal to half of the total Life Points you paid during your last turn.",
    "category": ["Recover LP"]
  },
  "Soul Demolition": {
    "id": "76297408",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Soul Demolition",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "You can pay 500 Life Points, then both players target 1 monster in their opponent's Graveyard; Banish them. You must control a Fiend monster to activate this effect.",
    "category": ["Banish"]
  },
  "The Dragon's Bead": {
    "id": "92408984",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "The Dragon's Bead",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Descarta 1 carta de tu mano. Niega el efecto de una Carta de Trampa que designe 1 monstruo de Tipo Dragón boca arriba como objetivo y destruye la Carta de Trampa.",
    "category": ["Negate Effect", "Destroy S/T"]
  },
  "Dragon's Rage": {
    "id": "54178050",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dragon's Rage",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Cuando un monstruo de Tipo Dragón en tu Campo ataca con un ATK superior a la DEF de un monstruo en Posición de Defensa, inflige la diferencia como daño de batalla a los Life Points de tu adversario.",
    "category": ["Piercing"]
  },
  "Royal Oppression": {
    "id": "93016201",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Royal Oppression",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When a monster(s) would be Special Summoned, OR when an effect is activated that includes an effect that Special Summons a monster(s): You can pay 800 Life Points; negate the Summon or effect, and if you do, destroy it. Either player can use this effect.",
    "category": ["Control"]
  },
  "Bad Reaction to Simochi": {
    "id": "40633297",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Bad Reaction to Simochi",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Any effect that would make your opponent gain Life Points inflicts the same amount of damage to them, instead.",
    "category": ["Damage LP"]
  },
  "Ominous Fortunetelling": {
    "id": "56995655",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Ominous Fortunetelling",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Once per turn, during your Standby Phase: Choose 1 random card in your opponent's hand and call the type of card (Monster, Spell, or Trap). If you call it right, inflict 700 damage to your opponent.",
    "category": ["Damage LP"]
  },
  "Spirit's Invitation": {
    "id": "92394653",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Spirit's Invitation",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When a Spirit monster you control returns to your hand, except during the Damage Step: Target 1 monster your opponent controls; return it to the hand. Once per turn, during your Standby Phase: Pay 500 Life Points or destroy this card.",
    "category": ["Spirit", "Send to Hand"]
  },
  "Ordeal of a Traveler": {
    "id": "39537362",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Ordeal of a Traveler",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When an opponent's monster declares an attack: Your opponent chooses 1 random card in your hand and calls the type of the card (Monster, Spell, or Trap), then reveal that card and if they call it wrong, return the attacking monster to the hand. You must have at least 1 card in your hand to activate and to resolve this effect.",
    "category": ["Send to Hand", "Battle Protection"]
  },
  "Bottomless Shifting Sand": {
    "id": "76532077",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Bottomless Shifting Sand",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "At the end of your opponent's turn, destroy the face-up monster(s) with the highest ATK on the field. During your Standby Phase, if you have 4 or less cards in your hand, destroy this card.",
    "category": ["Destroy Monster"]
  },
  "Needle Wall": {
    "id": "38299233",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Needle Wall",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Once per turn, during your Standby Phase: Roll a six-sided die. Treat your opponent's Monster Zones as numbers 1-5, counting from your right, and destroy the monster that is in the same Monster Zone as the result. If the result is 6, roll again.",
    "category": ["Gamble", "Destroy Monster"]
  },
  "Coffin Seller": {
    "id": "65830223",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Coffin Seller",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If a monster(s) is sent to your opponent's Graveyard: Inflict 300 damage to your opponent.",
    "category": ["Damage LP"]
  },
  "Narrow Pass": {
    "id": "40172183",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Narrow Pass",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Activate this card only if both players control 2 or less monsters each: Neither player can Normal Summon more than two times.",
    "category": ["Control"]
  },
  "Nightmare Wheel": {
    "id": "54704216",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Nightmare Wheel",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Selecciona 1 monstruo que tu adversario controle. El monstruo seleccionado no puede atacar o cambiar su posición de batalla. Cuando el monstruo seleccionado es retirado del Campo, destruye esta carta. Durante cada una de tus Standby Phases tu adversario recibe 500 puntos de daño.",
    "category": ["Position", "Damage LP", "Attack Restriction"]
  },
  "Rivalry of Warlords": {
    "id": "90846359",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Rivalry of Warlords",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Each player can only control 1 Type of monster. Send all other face-up monsters they control to the Graveyard.",
    "category": ["Control"]
  },
  "Pitch-Black Power Stone": {
    "id": "34029630",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Pitch-Black Power Stone",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Activate this card by placing 3 Spell Counters on it. Once per turn, during your turn: You can target 1 other face-up card on the field that you can place a Spell Counter on; remove 1 Spell Counter from this card, and if you do, place 1 Spell Counter on that target. When the last Spell Counter(s) is removed from this card, destroy it.",
    "category": ["Spell Counter"]
  },
  "Remove Brainwashing": {
    "id": "94739788",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Remove Brainwashing",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Control of all monsters on the field returns to the owners.",
    "category": ["Control"]
  },
  "Final Attack Orders": {
    "id": "52503575",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Final Attack Orders",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "All face-up monsters on the field are changed to Attack Position and their battle positions cannot be changed.",
    "category": ["Position"]
  },
  "Skill Drain": {
    "id": "82732705",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Skill Drain",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Activate this card by paying 1000 Life Points. Negate the effects of all face-up monsters while they are face-up on the field (but their effects can still be activated).",
    "category": ["Negate Effect"]
  },
  "Battle-Scarred": {
    "id": "94463200",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Battle-Scarred",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Activate this card by targeting 1 \"Archfiend\" monster you control: Your opponent also pays the same Life Points that you pay for the targeted monster during the Standby Phase. When this card leaves the field, destroy the targeted monster. When the targeted monster leaves the field, destroy this card.",
    "category": ["Control"]
  },
  "Tower of Babel": {
    "id": "94256039",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Tower of Babel",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Each time a Spell is activated, place 1 Spell Counter on this card when that Spell resolves. If the 4th Spell Counter is placed on this card: Destroy this card, and if you do, the player who activated the Spell at that time takes 3000 damage.",
    "category": ["Damage LP", "Spell Counter"]
  },
  "Spatial Collapse": {
    "id": "20644748",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Spatial Collapse",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Activate this card only if both you and your opponent each have 5 or less cards on the field. The total number of cards that each player can have on the field is 5.",
    "category": ["Control"]
  },
  "Curse of Darkness": {
    "id": "84970821",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Curse of Darkness",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Each time a Spell is activated, inflict 1000 damage to the player who activated it when that Spell resolves.",
    "category": ["Damage LP"]
  },
  "Begone, Knave!": {
    "id": "20374520",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Begone, Knave!",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If a monster inflicts battle damage: Return that monster to the hand.",
    "category": ["Send to Hand"]
  },
  "DNA Transplant": {
    "id": "56769674",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "DNA Transplant",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Activate this card by declaring 1 monster Attribute. All face-up monsters become that Attribute.",
    "category": ["Control"]
  },
  "Robbin' Zombie": {
    "id": "83258273",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Robbin' Zombie",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If a monster you control inflicts battle damage to your opponent: Send the top card of their Deck to the Graveyard.",
    "category": ["Destroy Deck"]
  },
  "Backfire": {
    "id": "82705573",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Backfire",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Cuando un monstruo de FUEGO en tu Campo es destruido y mandado al Cementerio, inflige 500 puntos de daño a los Life Points de tu adversario.",
    "category": ["Damage LP"]
  },
  "Talisman of Spell Sealing": {
    "id": "71983925",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Talisman of Spell Sealing",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Activate this card only if you control \"Sealmaster Meisei\". Spells cannot be activated. Negate all Spell effects on the field. If you do not control \"Sealmaster Meisei\", destroy this card.",
    "category": ["Negate Effect", "Control"]
  },
  "Wall of Revealing Light": {
    "id": "17078030",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Wall of Revealing Light",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Activate by paying any multiple of 1000 Life Points. Monsters your opponent controls cannot attack if their ATK is less than or equal to the amount you paid.",
    "category": ["Battle Protection", "Attack Restriction"]
  },
  "Ninjitsu Art of Transformation": {
    "id": "70861343",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Ninjitsu Art of Transformation",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Activate this card by Tributing 1 face-up \"Ninja\" monster; Special Summon 1 Beast, Winged Beast, or Insect monster from your hand or Deck whose Level is less than or equal to the Level the Tributed monster had on the field +3. When this card leaves the field, destroy that monster.",
    "category": ["Special Summon"]
  },
  "The First Sarcophagus": {
    "id": "31076103",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "The First Sarcophagus",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If all 3 of \"The First Sarcophagus\", \"The Second Sarcophagus\", and \"The Third Sarcophagus\" are placed on your field, send all \"Sarcophagus\" cards you control to the Graveyard: Special Summon 1 \"Spirit of the Pharaoh\" from your hand or Deck. Once per turn, during your opponent End Phase: Place 1 \"Sarcophagus\" card from your hand or Deck in your Spell & Trap Zone face-up, in order \"The Second Sarcophagus\" and \"The Third Sarcophagus\". When any \"Sarcophagus\" card you control leaves the field, send all \"Sarcophagus\" cards you control to the Graveyard.",
    "category": []
  },
  "Judgment of the Desert": {
    "id": "04869446",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Judgment of the Desert",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Face-up monsters that are flipped face-up after activation of this card cannot change their battle positions.",
    "category": ["Position"]
  },
  "Human-Wave Tactics": {
    "id": "30353551",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Human-Wave Tactics",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Once per turn, during the End Phase: Special Summon Level 2 or lower Normal Monsters from your Deck equal to the number of your Level 2 or lower Normal Monsters destroyed by battle this turn.",
    "category": ["Special Summon"]
  },
  "Des Counterblow": {
    "id": "39131963",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Des Counterblow",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "At the end of the Damage Step, if a monster inflicts battle damage by a direct attack: Destroy that attacking monster.",
    "category": ["Destroy Monster"]
  },
  "Labyrinth of Nightmare": {
    "id": "66526672",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Labyrinth of Nightmare",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Once per turn, during the End Phase: Change the battle positions of all face-up monsters the turn player controls.",
    "category": ["Position"]
  },
  "Soul Resurrection": {
    "id": "92924317",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Soul Resurrection",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Activate this card by targeting 1 Normal Monster in your Graveyard; Special Summon it in Defense Position. When this card leaves the field, destroy that monster. When that monster is destroyed, destroy this card.",
    "category": ["Special Summon"]
  },
  "Spirit Barrier": {
    "id": "53239672",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Spirit Barrier",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "While you control a monster, you take no battle damage.",
    "category": ["Battle Protection"]
  },
  "Ninjitsu Art of Decoy": {
    "id": "89628781",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Ninjitsu Art of Decoy",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 face-up \"Ninja\" monster you control; it cannot be destroyed by battle.",
    "category": ["Battle Protection"]
  },
  "Enervating Mist": {
    "id": "26022485",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Enervating Mist",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Your opponent's hand size limit becomes 5.",
    "category": ["Control"]
  },
  "Greed": {
    "id": "89405199",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Greed",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Once per turn, during the End Phase, if a player draws a card(s) this turn by a card effect after this card resolves: Inflict damage to that player equal to the total number of cards they drawn by a card(s) effect this turn x 500.",
    "category": ["Damage LP"]
  },
  "Xing Zhen Hu": {
    "id": "76515293",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Xing Zhen Hu",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Selecciona 2 Cartas Mágicas y/o de Trampa Colocadas en el Campo para activar esta carta. Mientras esta carta permanezca boca arriba en el Campo, las Cartas Mágicas y/o de Trampa seleccionadas no puede ser activadas.",
    "category": ["Control"]
  },
  "Rare Metalmorph": {
    "id": "12503902",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Rare Metalmorph",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Activate this card by targeting 1 Machine monster on the field; it gains 500 ATK. Once, negate a Spell effect that targets that monster. When that monster leaves the field, destroy this card.",
    "category": ["Change ATK/DEF"]
  },
  "Chain Burst": {
    "id": "48276469",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Chain Burst",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Each time a player activates a Trap, they take 1000 damage when that Trap resolves.",
    "category": ["Damage LP"]
  },
  "Astral Barrier": {
    "id": "37053871",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Astral Barrier",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If your opponent's monster attacks a monster you control: You can make the attack a direct attack instead.",
    "category": ["Battle Protection"]
  },
  "Pole Position": {
    "id": "73578229",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Pole Position",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "The face-up monster(s) with the highest ATK on the field is unaffected by the Spell effects. When this card leaves the field, destroy the face-up monster(s) with the highest ATK on the field.",
    "category": ["Unaffected"]
  },
  "Lone Wolf": {
    "id": "82452993",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Lone Wolf",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If you control 1 \"Chu-Ske the Mouse Fighter\", \"Monk Fighter\", or \"Master Monk\" and no other monsters: Target that monster; it cannot be destroyed by battle, and is unaffected by opponent's monster effects.",
    "category": ["Battle Protection", "Unaffected"]
  },
  "Toon Defense": {
    "id": "43509019",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Toon Defense",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When an opponent's monster declares an attack targeting a face-up Level 4 or lower Toon monster you control: You can make the attack a direct attack instead.",
    "category": ["Battle Protection", "Toon"]
  },
  "Royal Decree": {
    "id": "51452091",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Royal Decree",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Mientras esta carta permanezca boca arriba en el Campo, niega los efectos de todas las Cartas de Trampa en el Campo excepto esta carta.",
    "category": ["Negate Effect", "Control"]
  },
  "Pyramid of Light": {
    "id": "53569894",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Pyramid of Light",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When this face-up card you control leaves the field, destroy as many \"Andro Sphinx\" and \"Sphinx Teleia\" you control as possible, and if you do, banish them.",
    "category": ["Destroy Monster"]
  },
  "Ultimate Offering": {
    "id": "80604091",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Ultimate Offering",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "During your Main Phase or your opponent's Battle Phase: You can pay 500 Life Points; immediately after this effect resolves, Normal Summon or Set 1 monster.",
    "category": ["Control"]
  },
  "Shadow Spell": {
    "id": "29267084",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Shadow Spell",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Activate this card by targeting 1 face-up monster your opponent controls; it loses 700 ATK, also it cannot attack or change its battle position. When that monster leaves the field, destroy this card.",
    "category": ["Change ATK/DEF"]
  },
  "Embodiment of Apophis": {
    "id": "28649820",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Embodiment of Apophis",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "During the Main Phase: Special Summon this card as a Normal Monster (Reptile/EARTH/Level 4/ATK 1600/DEF 1800). (This card is also still a Trap.)",
    "category": ["Special Summon"]
  },
  "Goblin Fan": {
    "id": "04149689",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Goblin Fan",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When a Level 2 or lower monster is Flip Summoned, destroy it. Its effects do not activate at that time.",
    "category": ["Destroy Monster"]
  },
  "Anti-Spell Fragrance": {
    "id": "58921041",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Anti-Spell Fragrance",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Both players must Set Spells before activating them, and cannot activate them until their next turn after Setting them.",
    "category": ["Control"]
  },
  "Aqua Chorus": {
    "id": "95132338",
    "card-type": "continuous-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Aqua Chorus",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If there are monsters with the same name on the field, all those monsters with the same name gain 500 ATK and DEF.",
    "category": ["Change ATK/DEF"]
  }
};