const trapnormalDetailed = {
  "Trap Hole": {
    "id": "04206964",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Trap Hole",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When your opponent Normal or Flip Summons 1 monster with 1000 or more ATK: Target that monster; destroy it.",
    "category": ["Destroy Monster"]
  },
  "Two-Pronged Attack": {
    "id": "83887306",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Two-Pronged Attack",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 2 monsters you control and 1 monster your opponent controls: Destroy them.",
    "category": ["Destroy Monster"]
  },
  "Fake Trap": {
    "id": "03027001",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Fake Trap",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When your opponent activates a Spell or Trap, or monster effect, that includes an effect that destroys a Trap(s) you control: Destroy this card instead. (If the cards that have been destroyed are Set, reveal them.)",
    "category": []
  },
  "Mirror Force": {
    "id": "44095762",
    "card-type": "normal-trap",
    "banlist": "Limited",
    "Genesys": 0,
    "name": "Mirror Force",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Cuando un monstruo de tu adversario ataca, niega el ataque y destruye todos los monstruos en Posición de Ataque de tu adversario.",
    "category": ["Destroy Monster", "Battle Protection"]
  },
  "Fairy's Hand Mirror": {
    "id": "17653779",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Fairy's Hand Mirror",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When your opponent activates a Spell that targets exactly 1 monster (and no other cards) on the field: Target another card that would be an appropriate target; that Spell now targets the new target.",
    "category": ["Control"]
  },
  "Snake Fang": {
    "id": "00596051",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Snake Fang",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 face-up monster on the field: It loses 500 DEF, until the end of this turn.",
    "category": ["Change ATK/DEF"]
  },
  "House of Adhesive Tape": {
    "id": "15083728",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "House of Adhesive Tape",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When your opponent Normal or Flip Summons 1 monster with 500 or less DEF: Target that monster; destroy it.",
    "category": ["Destroy Monster"]
  },
  "Eatgaboon": {
    "id": "42578427",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Eatgaboon",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When your opponent Normal or Flip Summons 1 monster with 500 or less ATK: Target that monster; destroy it.",
    "category": ["Destroy Monster"]
  },
  "Lightforce Sword": {
    "id": "49587034",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Lightforce Sword",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Banish 1 random card from your opponent's hand, face-down. During your opponent's 4th Standby Phase after this card's activation, return that card to their hand.",
    "category": ["Destroy Hand", "Banish"]
  },
  "Chain Destruction": {
    "id": "01248895",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Chain Destruction",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When a monster(s) with 2000 or less ATK is Summoned: Target 1 of them; destroy all cards with that name in its controller's hand and Main Deck.",
    "category": ["Destroy Monster"]
  },
  "Time Seal": {
    "id": "35316708",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Time Seal",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Skip the Draw Phase of your opponent's next turn.",
    "category": ["Control"]
  },
  "Graverobber": {
    "id": "61705417",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Graverobber",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 Spell in your opponent's Graveyard; add it to your hand, also if you activate that Spell, take 2000 damage when it resolves. During the End Phase of this turn, send that card to the Graveyard.",
    "category": ["Send to Hand", "Damage LP"]
  },
  "Gift of The Mystical Elf": {
    "id": "98299011",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Gift of The Mystical Elf",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Gain 300 Life Points for each monster on the field.",
    "category": ["Change ATK/DEF"]
  },
  "Dust Tornado": {
    "id": "60082869",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dust Tornado",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Destruye 1 Carta Mágica o de Trampa en el Campo de tu adversario. Puedes entonces Colocar 1 Carta Mágica o de Trampa de tu mano.",
    "category": ["Destroy S/T"]
  },
  "Solomon's Lawbook": {
    "id": "23471572",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Solomon's Lawbook",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Skip your next Standby Phase.",
    "category": ["Control"]
  },
  "Earthshaker": {
    "id": "60866277",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Earthshaker",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Declare 2 monster Attributes; your opponent chooses 1 of them, then destroy all face-up monsters on the field with that Attribute.",
    "category": ["Destroy Monster"]
  },
  "Enchanted Javelin": {
    "id": "96355986",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Enchanted Javelin",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When an opponent's monster declares an attack: Target the attacking monster; gain Life Points equal to its ATK.",
    "category": ["Recover LP"]
  },
  "Gust": {
    "id": "73079365",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Gust",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When a Spell(s) you control is destroyed and sent to the Graveyard by an opponent's card effect: Target 1 Spell or Trap on the field; destroy it.",
    "category": ["Destroy S/T"]
  },
  "Driving Snow": {
    "id": "00473469",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Driving Snow",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When a Trap(s) you control is destroyed and sent to the Graveyard by an opponent's card effect: Target 1 Spell or Trap on the field; destroy it.",
    "category": ["Destroy S/T"]
  },
  "Armored Glass": {
    "id": "36868108",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Armored Glass",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When a monster is equipped with an Equip Card: Negate all Equip Card effects on the field, until the end of this turn.",
    "category": ["Negate Effect"]
  },
  "World Suppression": {
    "id": "12253117",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "World Suppression",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When a Field Spell is activated: Negate all Field Spell effects on the field, until the end of this turn.",
    "category": ["Negate Effect"]
  },
  "Mystic Probe": {
    "id": "49251811",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Mystic Probe",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When a Continuous Spell is activated: Negate all Continuous Spell effects on the field, until the end of this turn.",
    "category": ["Negate Effect"]
  },
  "Metal Detector": {
    "id": "75646520",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Metal Detector",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When a Continuous Trap is activated: Negate all Continuous Trap effects on the field, until the end of this turn.",
    "category": ["Negate Effect"]
  },
  "Numinous Healer": {
    "id": "02130625",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Numinous Healer",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When you take damage: Gain 1000 Life Points, also gain 500 Life Points for each \"Numinous Healer\" in your Graveyard.",
    "category": ["Recover LP"]
  },
  "Backup Soldier": {
    "id": "36280194",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Backup Soldier",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If there are 5 or more monsters in your Graveyard: Target up to 3 non-Effect Monsters with 1500 or less ATK in your Graveyard; add them to your hand.",
    "category": ["Send to Hand"]
  },
  "Major Riot": {
    "id": "09074847",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Major Riot",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When a monster(s) is returned from the field to your hand by an opponent's card effect: Return all monster on the field to the hand, then each player Special Summon (from their hand) the same number of monster they returned, in face-down Defense Position.",
    "category": ["Send to Hand", "Special Summon"]
  },
  "Ceasefire": {
    "id": "36468556",
    "card-type": "normal-trap",
    "banlist": "Limited",
    "Genesys": 0,
    "name": "Ceasefire",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Voltea todos los monstruos boca abajo en Posición de Defensa en el Campo boca arriba. No se activan los Efectos de Volteo en este momento. Inflige 500 puntos de daño a los Life Points de tu adversario por cada Monstruo de Efecto en el Campo.",
    "category": ["Damage LP", "Flip"]
  },
  "Magical Hats": {
    "id": "81210420",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Magical Hats",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "During your opponent's Battle Phase, except during the Damage Step: Choose 2 Spells or Traps from your Deck and 1 monster you control, then Special Summon them as Normal Monsters (ATK 0/DEF 0) in face-down Defense Position, Set the chosen monster if it is face-up, and shuffle them in your Monster Zones. The 2 cards chosen from your Deck are destroyed at the end of the Battle Phase, and cannot remain on the field, except during this Battle Phase.",
    "category": ["Special Summon", "Destroy Deck"]
  },
  "Michizure": {
    "id": "37580756",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Michizure",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When a monster is sent from the field to your Graveyard, even during the Damage Step: Target 1 monster on the field; destroy it.",
    "category": ["Destroy Monster"]
  },
  "Gamble": {
    "id": "37313786",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Gamble",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If your opponent has 6 or more cards in their hand and your have 2 or less cards in your hand: Toss a coin and call heads or tails. If you call it right, draw until your have 5 cards in your hand. If you call it wrong, skip your next turn.",
    "category": ["Gamble", "Control"]
  },
  "Attack and Receive": {
    "id": "63689843",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Attack and Receive",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When you take damage: Inflict 700 damage to your opponent, also inflict 300 damage to your opponent for each \"Attack and Receive\" card in your Graveyard.",
    "category": ["Damage LP"]
  },
  "Shift": {
    "id": "59560625",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Shift",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When your opponent targets exactly 1 monster you control (and no other cards) for an attack, or with a Spell or Trap effect: Target another monster you control that would be an appropriate target; that attack, Spell or Trap now targets the new target.",
    "category": ["Control", "Battle Protection"]
  },
  "Shadow of Eyes": {
    "id": "58621589",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Shadow of Eyes",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When a monster(s) is Set on your opponent's field: Target 1 of those Set monsters; change that Set monster to face-up Attack Position. (Flip monster's effects are not activated at this time.)",
    "category": ["Position"]
  },
  "Mask of Weakness": {
    "id": "57882509",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Mask of Weakness",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When a monster declares an attack: Target the attacking monster; that target loses 700 ATK, until the end of this turn.",
    "category": ["Change ATK/DEF"]
  },
  "Torrential Tribute": {
    "id": "53582587",
    "card-type": "normal-trap",
    "banlist": "Limited",
    "Genesys": 0,
    "name": "Torrential Tribute",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Solo puedes activar esta carta cuando un monstruo es Invocado mediante una Invocación Normal, Invocación de Volteo o Invocación Especial. Destruye todos los monstruos en el Campo.",
    "category": ["Destroy Monster"]
  },
  "Jar of Greed": {
    "id": "83968380",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Jar of Greed",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Roba 1 carta de tu Deck.",
    "category": ["Draw"]
  },
  "Collected Power": {
    "id": "07565547",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Collected Power",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 face-up monster on the field; equip that target with all Equip on the field. If any of those Equip is now equipped to an incorrect target, destroy that Equip.",
    "category": ["Destroy S/T"]
  },
  "Dark Spirit of the Silent": {
    "id": "93599951",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dark Spirit of the Silent",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When an opponent's monster declares an attack: Negate that attack, and target 1 other face-up monster your opponent controls. That monster attacks instead. (If it is in face-up Defense Position, change it to Attack Position.)",
    "category": ["Battle Protection", "Control"]
  },
  "Deal of Phantom": {
    "id": "69122763",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Deal of Phantom",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 face-up monster on the field: It gains 100 ATK for each monster in your Graveyard, until the end of this turn.",
    "category": ["Change ATK/DEF"]
  },
  "Destruction Punch": {
    "id": "05616412",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Destruction Punch",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "At the end of the Damage Step, if a Defense Position monster you control is attacked and its DEF is higher than the ATK of the attacking monster: Destroy the attacking monster. (Damage calculation is applied normally.)",
    "category": ["Destroy Monster"]
  },
  "Magic Cylinder": {
    "id": "62279055",
    "card-type": "normal-trap",
    "banlist": "Limited",
    "Genesys": 0,
    "name": "Magic Cylinder",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Niega el ataque de 1 monstruo de tu adversario e inflige daño igual al ATK del monstruo atacante a los Life Points de tu adversario.",
    "category": ["Battle Protection", "Damage LP"]
  },
  "Bark of Dark Ruler": {
    "id": "41925941",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Bark of Dark Ruler",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If a Fiend monster you control battles, during the Damage Step: Pay Life Points (in multiples of 100), then target the opponent's battling monster; it loses that much ATK and DEF, until the end of this turn.",
    "category": ["Change ATK/DEF"]
  },
  "Ready for Intercepting": {
    "id": "31785398",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Ready for Intercepting",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 Warrior or Spellcaster monster on the field; change it to face-down Defense Position.",
    "category": ["Position"]
  },
  "A Feint Plan": {
    "id": "68170903",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "A Feint Plan",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Face-down monsters cannot be attacked for the rest of this turn.",
    "category": ["Battle Protection"]
  },
  "Burst Breath": {
    "id": "80163754",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Burst Breath",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Tribute 1 Dragon monster; destroy all face-up monsters on the field whose DEF is less than or equal to the ATK the Tributed monster had on the field.",
    "category": ["Destroy Monster"]
  },
  "Blast with Chain": {
    "id": "98239899",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Blast with Chain",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 face-up monster you control; equip this card to that target. It gains 500 ATK. If this card is destroyed by a card effect while equipped: Target 1 card on the field; destroy it.",
    "category": ["Change ATK/DEF", "Destroy S/T", "Destroy Monster"]
  },
  "Disappear": {
    "id": "24623598",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Disappear",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 card in your opponent's Graveyard; banish it.",
    "category": ["Banish"]
  },
  "Bubble Crash": {
    "id": "61622107",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Bubble Crash",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If any player has 6 or more cards in their hand and field: That player(s) send cards from the field or hand to the Graveyard until they have 5 cards in their hand and field.",
    "category": ["Send to Graveyard"]
  },
  "Bottomless Trap Hole": {
    "id": "29401950",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Bottomless Trap Hole",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When your opponent Summons a monster(s) with 1500 or more ATK: Destroy that monster(s) with 1500 or more ATK, and if you do, banish it.",
    "category": ["Destroy Monster", "Banish"]
  },
  "Nutrient Z": {
    "id": "29389368",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Nutrient Z",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "During the damage calculation of your opponent's turn, if you will take 2000 or more battle damage for that battle: Gain 4000 Life Points first.",
    "category": ["Recover LP"]
  },
  "Drop Off": {
    "id": "55773067",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Drop Off",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When your opponent draws for their normal draw in their Draw Phase: Your opponent discards 1 card they just drew.",
    "category": ["Destroy Hand"]
  },
  "Fiend Comedian": {
    "id": "81172176",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Fiend Comedian",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Toss a coin and call it. If you call it right, banish all cards in your opponent's Graveyard. If you call it wrong, send cards equal to the number of cards in your opponent's Graveyard from the top of your Deck to the Graveyard.",
    "category": ["Gamble", "Banish", "Destroy Deck"]
  },
  "Last Turn": {
    "id": "28566710",
    "card-type": "normal-trap",
    "banlist": "Semi-limited",
    "Genesys": 0,
    "name": "Last Turn",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Esta carta sólo puede ser activada durante el turno de tu adversario cuando tus Life Points son 1000 o menos. Selecciona 1 monstruo en tu Campo y manda todas las demás cartas en el Campo y en las manos de sus respectivos propietarios a sus respectivos Cementerios. Después de eso, tu adversario selecciona e Invoca mediante una Invocación Especial 1 monstruo de su Deck en Posición de Ataque y ataca tu monstruo seleccionado. (Cualquier daño de batalla de esta batalla se considera 0). El jugador cuyo monstruo permanezca solo en el Campo en la End Phase de este turno gana el Duelo. Cualquier otro caso resulta en EMPATE.",
    "category": ["Win Condition"]
  },
  "Ring of Destruction": {
    "id": "83555666",
    "card-type": "normal-trap",
    "banlist": "Limited",
    "Genesys": 0,
    "name": "Ring of Destruction",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Selecciona y destruye 1 monstruo boca arriba, e inflige daño igual a su ATK a ambos jugadores.",
    "category": ["Destroy Monster", "Damage LP"]
  },
  "Ring of Destruction 2": {
    "id": "83555666",
    "card-type": "normal-trap",
    "banlist": "Limited",
    "Genesys": 0,
    "name": "Ring of Destruction",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Selecciona y destruye 1 monstruo boca arriba, e inflige daño igual a su ATK a ambos jugadores.",
    "category": ["Destroy Monster", "Damage LP"]
  },
  "Needle Ceiling": {
    "id": "38411870",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Needle Ceiling",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If there are 4 or more monsters on the field: Destroy all face-up monsters on the field.",
    "category": ["Destroy Monster"]
  },
  "Statue of the Wicked": {
    "id": "65810489",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Statue of the Wicked",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If this Set card is destroyed and sent to the Graveyard: Special Summon 1 \"Wicked Token\" (Fiend/DARK/Level 4/ATK 1000/DEF 1000).",
    "category": ["Special Summon", "Token"]
  },
  "Dark Coffin": {
    "id": "01804528",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dark Coffin",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When this Set card is destroyed and sent to the Graveyard: Your opponent activates 1 of the following effects: ● Discard 1 random card. ● Target 1 monster you control; destroy it.",
    "category": ["Destroy Monster", "Destroy Hand"]
  },
  "Trap Dustshoot": {
    "id": "64697231",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Trap Dustshoot",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If your opponent has 4 or more cards in their hand: Look at your opponent's hand, then shuffle 1 monster from their hand to the Deck (if any).",
    "category": ["Destroy Hand", "Control"]
  },
  "Pyro Clock of Destiny": {
    "id": "01082946",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Pyro Clock of Destiny",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Move a turn count forward by 1 turn.",
    "category": ["Control"]
  },
  "Reckless Greed": {
    "id": "37576645",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Reckless Greed",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Roba 2 cartas, y después de eso sáltate tus 2 próximas Draw Phases.",
    "category": ["Draw"]
  },
  "Pharaoh's Treasure": {
    "id": "63571750",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Pharaoh's Treasure",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Shuffle this card face-up into your Deck. If you draw this face-up card that was added to the Deck by this effect: Send it from your hand to the Graveyard, then target 1 card in your Graveyard, except this card; add that target to your hand.",
    "category": ["Send to Deck", "Send to Hand"]
  },
  "Curse of Aging": {
    "id": "41398771",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Curse of Aging",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Discard 1 card; all monsters your opponent currently controls loses 500 ATK and DEF, until the end of this turn.",
    "category": ["Change ATK/DEF"]
  },
  "Raigeki Break": {
    "id": "04178474",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Raigeki Break",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Descarta 1 carta de tu mano para destruir 1 carta en el Campo.",
    "category": ["Destroy Monster", "Destroy S/T"]
  },
  "Disturbance Strategy": {
    "id": "77561728",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Disturbance Strategy",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Your opponent shuffles their entire hand into the Deck, then draws the same number of cards.",
    "category": ["Send to Deck", "Draw", "Destroy Hand"]
  },
  "Rite of Spirit": {
    "id": "30450531",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Rite of Spirit",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 \"Gravekeeper's\" monster in your Graveyard; Special Summon it. This card's activation and effect are unaffected by \"Necrovalley\".",
    "category": ["Special Summon"]
  },
  "Non Aggression Area": {
    "id": "76848240",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Non Aggression Area",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "During your Standby Phase: Discard 1 card; your opponent cannot Normal Summon, Set or Special Summon during their next turn.",
    "category": ["Control"]
  },
  "D. Tribe": {
    "id": "02833249",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "D. Tribe",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "All face-up monsters you currently control become Dragon, until the end of this turn.",
    "category": ["Control"]
  },
  "Rope of Life": {
    "id": "93382620",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Rope of Life",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When a monster(s) is destroyed by battle and sent to your Graveyard: Discard your entire hand (min.1), then target 1 of those monsters; Special Summon it, and if you do, it gains 800 ATK.",
    "category": ["Special Summon"]
  },
  "Huge Revolution": {
    "id": "65396880",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Huge Revolution",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "During your Main Phase, if you control \"People Running About\", \"Oppressed People\", and \"United Resistance\": Send all cards in your opponent's hand to the Graveyard, also destroy all cards your opponent controls.",
    "category": ["Destroy Monster", "Destroy S/T", "Destroy Hand"]
  },
  "Thunder of Ruler": {
    "id": "91781589",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Thunder of Ruler",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "During your opponent's Standby Phase: Your opponent skips the Battle Phase of this turn.",
    "category": ["Control"]
  },
  "Meteorain": {
    "id": "64274292",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Meteorain",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "During this turn, if your monsters attack a Defense Position monster, inflict piercing battle damage.",
    "category": ["Piercing"]
  },
  "Pineapple Blast": {
    "id": "90669991",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Pineapple Blast",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When you Normal Summon a monster, if your opponent controls more monsters than you do: Your opponent destroy monsters they control so they control the same number od monster as your do.",
    "category": ["Destroy Monster"]
  },
  "Secret Barrel": {
    "id": "27053506",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Secret Barrel",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Inflige daño a los Life Points de tu adversario igual al número total de cartas en el Campo de tu adversario y en la mano de tu adversario X 200 puntos.",
    "category": ["Damage LP"]
  },
  "Physical Double": {
    "id": "63442604",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Physical Double",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "During your opponent's turn: Target 1 face-up monster your opponent controls; Special Summon 1 \"Mirage Token\" with the same Level, Type, Attribute, ATK, and DEF as that target. Destroy this Token during the End Phase.",
    "category": ["Token", "Special Summon"]
  },
  "Formation Union": {
    "id": "26931058",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Formation Union",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Activate 1 of these effects. ● Target 1 Union monster you control; equip it to an appropriate monster you control. ● Target 1 Union monster equipped by its own effect you control; Special Summon it in Attack Position.",
    "category": ["Union", "Special Summon"]
  },
  "Adhesion Trap Hole": {
    "id": "62325062",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Adhesion Trap Hole",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When your opponent Summons a monster(s): Halve that monster(s)'s original ATK.",
    "category": ["Change ATK/DEF"]
  },
  "Amazoness Archers": {
    "id": "67987611",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Amazoness Archers",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When an opponent's monster declares an attack, while you control an \"Amazoness\" monster: Change all monsters your opponent currently controls to face-up Attack Position (Flip monster's effects are not activated at this time), they lose 500 ATK, also they must attack this turn, if able.",
    "category": ["Position", "Flip", "Negate Effect", "Change ATK/DEF"]
  },
  "Dramatic Rescue": {
    "id": "80193355",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dramatic Rescue",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When a card that targets an \"Amazoness\" monster is activated: Return the targeted monster to the hand, and if you do, Special Summon 1 other monster from your hand.",
    "category": ["Send to Hand", "Special Summon"]
  },
  "Exhausting Spell": {
    "id": "95451366",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Exhausting Spell",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Remove all Spell Counters from the field.",
    "category": ["Spell Counter"]
  },
  "Hidden Book of Spell": {
    "id": "21840375",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Hidden Book of Spell",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "(This card is always treated as a \"Spellbook\" card.) During your turn: Target 2 Spells in your Graveyard; shuffle them into your Deck.",
    "category": ["Send to Deck"]
  },
  "Miracle Restoring": {
    "id": "68334074",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Miracle Restoring",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Remove 2 Spell Counters from your field, then target 1 \"Dark Magician\" or \"Buster Blader\" in your Graveyard; Special Summon it.",
    "category": ["Spell Counter", "Special Summon"]
  },
  "Disarmament": {
    "id": "20727787",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Disarmament",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Destroy all face-up Equips on the field.",
    "category": ["Destroy S/T"]
  },
  "The Spell Absorbing Life": {
    "id": "99517131",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "The Spell Absorbing Life",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If a face-down Defense Position monster or an Effect Monster is on the field: Change all face-down Defense Position monsters on the field to face-up Defense Position (Flip monsters' effects are not activated at this time), also gain 500 Life Points for each Effect Monster on the field.",
    "category": ["Position", "Flip", "Recover LP"]
  },
  "Staunch Defender": {
    "id": "92854392",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Staunch Defender",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When an opponent's monster declares an attack: Target 1 face-up monster you control; during this turn, your opponent can only attack that targeted monster, and must attack it with all face-up monsters they control.",
    "category": ["Battle Protection", "Control"]
  },
  "Ojama Trio": {
    "id": "29843091",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Ojama Trio",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Invoca mediante una Invocación Especial 3 <b>Fichas de Ojama</b> (Tipo Bestia/LUZ/Nivel 2/ATK 0/DEF 1000) en Posición de Defensa en el Campo de tu adversario. Las fichas no pueden ser usadas como Sacrificio para una Invocación de Sacrificio. Cuando 1 <b>Ficha de Ojama</b> es destruida, inflige 300 puntos de daño a los Life Points de su controlador.",
    "category": ["Special Summon", "Token", "Damage LP"]
  },
  "Arsenal Robber": {
    "id": "55348096",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Arsenal Robber",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Your opponent sends 1 Equip Spell from their Deck to the Graveyard.",
    "category": ["Destroy Deck"]
  },
  "Really Eternal Rest": {
    "id": "28121403",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Really Eternal Rest",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Destroy all monsters equipped with an Equip Card(s).",
    "category": ["Destroy Monster"]
  },
  "Interdimensional Matter Transporter": {
    "id": "36261276",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Interdimensional Matter Transporter",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Selecciona 1 monstruo boca arriba en tu Campo y retiralo del juego hasta el End Phase de este turno.",
    "category": ["Banish"]
  },
  "Altar for Tribute": {
    "id": "21070956",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Altar for Tribute",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Send 1 monster you control to the Graveyard; gain Life Points equal to the original ATK of that monster.",
    "category": ["Recover LP"]
  },
  "Frozen Soul": {
    "id": "57069605",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Frozen Soul",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If your Life Points are lower than your opponent's and the difference is 2000 or more: Skip your opponent's next Battle Phase.",
    "category": ["Battle Protection"]
  },
  "Dark Scorpion Combination": {
    "id": "20858318",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dark Scorpion Combination",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If you control 1 \"Don Zaloog\", \"Dark Scorpion - Cliff the Trap Remover\", \"Dark Scorpion - Chick the Yellow\", \"Dark Scorpion - Gorg the Strong\", and \"Dark Scorpion - Meanae the Thorn\": During this turn, all of those 5 cards can attack directly. In that case, the battle damage inflicted to your opponent by each of those cards becomes 400.",
    "category": ["Direct Attack"]
  },
  "Archfiend's Roar": {
    "id": "56246017",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Archfiend's Roar",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Pay 500 Life Points, then target 1 \"Archfiend\" monster in your Graveyard; Special Summon it, but it cannot be Tributed. During the End Phase of this turn, destroy it.",
    "category": ["Special Summon"]
  },
  "Dice Re-Roll": {
    "id": "83241722",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dice Re-Roll",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "One time, during the rest of this turn, if either player(s) rolls a die (or dice), you can have the player(s) re-roll. (You can only gain this effect once per turn.)",
    "category": ["Gamble"]
  },
  "Sakuretsu Armor": {
    "id": "56120475",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Sakuretsu Armor",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Sólo puedes activar esta carta cuando tu adversario declara un ataque. Destruye el monstruo atacante.",
    "category": ["Battle Protection", "Destroy Monster"]
  },
  "Ray of Hope": {
    "id": "82529174",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Ray of Hope",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 2 LIGHT monsters in your Graveyard; shuffle them into the Deck.",
    "category": ["Send to Deck"]
  },
  "Blast Held by a Tribute": {
    "id": "89041555",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Blast Held by a Tribute",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When an opponent's Tribute Summoned monster declares an attack: Destroy as many face-up Attack Position monsters your opponent controls as possible, and if you do, inflict 1000 damage to your opponent.",
    "category": ["Destroy Monster", "Damage LP"]
  },
  "Big Burn": {
    "id": "95472621",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Big Burn",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When your opponent activates a card that targets a monster(s) in the Graveyard: Banish all monsters in both players' Graveyards.",
    "category": ["Banish"]
  },
  "Blasting the Ruins": {
    "id": "21466326",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Blasting the Ruins",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If there are 30 or more cards in your Graveyard: Inflict 3000 damage to your opponent.",
    "category": ["Damage LP"]
  },
  "Chain Disappearance": {
    "id": "57139487",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Chain Disappearance",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When a monster(s) with 1000 or less ATK is Summoned: Banish that monster(s) with 1000 or less ATK, and if you do, your opponent banishes all cards with the same name as that card(s) from their hand and Deck.",
    "category": ["Banish", "Destroy Deck", "Destroy Hand"]
  },
  "Zero Gravity": {
    "id": "83133491",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Zero Gravity",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Change the battle positions of all face-up monsters on the field.",
    "category": ["Position"]
  },
  "Dark Mirror Force": {
    "id": "20522190",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dark Mirror Force",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When an opponent's monster declares an attack: Banish all Defense Position monsters your opponent controls.",
    "category": ["Banish"]
  },
  "Energy Drain": {
    "id": "56916805",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Energy Drain",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 face-up monster you control; it gains ATK and DEF equal to the number of cards in your opponent's hand x 200, until the end of this turn.",
    "category": ["Change ATK/DEF"]
  },
  "Destruction Ring": {
    "id": "21219755",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Destruction Ring",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 face-up monster you control; Destroy it, and if you do, inflict 1000 damage to both players.",
    "category": ["Destroy Monster", "Damage LP"]
  },
  "Fiend's Hand Mirror": {
    "id": "58607704",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Fiend's Hand Mirror",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When an opponent's Spell that targets exactly 1 Spell or Trap on the field (and no other cards) is activated: Change the target to another correct target.",
    "category": ["Control"]
  },
  "Compulsory Evacuation Device": {
    "id": "94192409",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Compulsory Evacuation Device",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Devuelve 1 monstruo en el Campo a la mano de su propietario.",
    "category": ["Send to Hand"]
  },
  "A Hero Emerges": {
    "id": "21597117",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "A Hero Emerges",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When an opponent's monster declares an attack: Your opponent chooses 1 random card from your hand, then if it is a monster that can be Special Summoned, Special Summon it. Otherwise, send it to the Graveyard.",
    "category": ["Special Summon"]
  },
  "Self-Destruct Button": {
    "id": "57585212",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Self-Destruct Button",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If your Life Points are lower than your opponent's Life Points and the difference is 7000 or more: Both player's Life Points become 0.",
    "category": ["Control"]
  },
  "Micro Ray": {
    "id": "18190572",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Micro Ray",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 face-up monster on the field; its DEF becomes 0, until the end of this turn.",
    "category": ["Change ATK/DEF"]
  },
  "Light of Judgment": {
    "id": "44595286",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Light of Judgment",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If \"The Sanctuary in the Sky\" is on the field: Discard 1 LIGHT monster to the Graveyard; apply 1 of the following effects: ● Look at your opponent's hand and discard 1 card from their hand. ● Send 1 card your opponent controls to the Graveyard.",
    "category": ["Destroy Hand", "Send to Graveyard"]
  },
  "Solar Ray": {
    "id": "44472639",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Solar Ray",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Inflict 600 damage to your opponent for each face-up LIGHT monster you control.",
    "category": ["Damage LP"]
  },
  "Beckoning Light": {
    "id": "16255442",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Beckoning Light",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Discard your entire hand, then for each card you discarded to the Graveyard by this effect, add 1 LIGHT monster from your Graveyard to your hand.",
    "category": ["Send to Hand"]
  },
  "Draining Shield": {
    "id": "43250041",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Draining Shield",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When an opponent's monster declares an attack: Target the attacking monster; negate that attack, and if you do, gain Life Points equal to that target's ATK.",
    "category": ["Battle Protection", "Recover LP"]
  },
  "Dora of Fate": {
    "id": "67464807",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Dora of Fate",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "During your opponent's turn: Target 1 Level 2 o higher monster your opponent controls; once, during your next turn, when you Normal Summon a monster that is 1 Level lower than the targeted monster, inflict damage to your opponent equal to the Level of the targeted monster x 500.",
    "category": ["Damage LP"]
  },
  "Curse of Anubis": {
    "id": "66742250",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Curse of Anubis",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Todos los Monstruos de Efecto boca arriba en el Campo se cambian a Posición de Defensa. Durante este turno, la DEF original de esos Monstruos de Efecto se convierte en 0 y sus posiciones de batalla no pueden ser cambiadas.",
    "category": ["Position", "Change ATK/DEF"]
  },
  "Desert Sunlight": {
    "id": "93747864",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Desert Sunlight",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Change all monsters you control to face-up Defense Position.",
    "category": ["Position"]
  },
  "Order to Smash": {
    "id": "39019325",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Order to Smash",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 Level 2 or lower non-Token Normal Monster you control; Tribute that Normal Monster, and if you do, destroy up to 2 Spells or Traps your opponent controls.",
    "category": ["Destroy Monster"]
  },
  "Taunt": {
    "id": "90740329",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Taunt",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "During your opponent's Main Phase 1: Target 1 monster you control; while that monster is on the field, if your opponent attacks with a monster(s) this turn, they must target that monster as the attack target.",
    "category": ["Battle Protection", "Control"]
  },
  "Absolute End": {
    "id": "27744077",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Absolute End",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "During your opponent's turn: This turn, the attacks from your opponent's monsters become direct attacks.",
    "category": ["Direct Attack"]
  },
  "Heavy Slump": {
    "id": "52417194",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Heavy Slump",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If your opponent has 8 or more cards in their hand: They shuffle their entire hand into the Deck, then they draw 2 cards.",
    "category": ["Destroy Hand", "Draw"]
  },
  "Mind Crush": {
    "id": "15800838",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Mind Crush",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Declare 1 card name; if that card is in your opponent's hand, they must discard all copies of it, otherwise you discard 1 random card.",
    "category": ["Destroy Hand"]
  },
  "Null and Void": {
    "id": "80863132",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Null and Void",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When an effect of only draw a card(s) is activated: Sent that card(s) to the Graveyard instead.",
    "category": ["Send to Graveyard"]
  },
  "Gorgon's Eye": {
    "id": "52648457",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Gorgon's Eye",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Negate the effects of Defense Position monsters, until the end of this turn.",
    "category": ["Negate Effect"]
  },
  "Cemetery Bomb": {
    "id": "51394546",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Cemetery Bomb",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Inflict 100 damage to your opponent for each card in their Graveyard.",
    "category": ["Damage LP"]
  },
  "Hallowed Life Barrier": {
    "id": "88789641",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Hallowed Life Barrier",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Discard 1 card; you take no damage from your opponent's cards this turn.",
    "category": ["Control"]
  },
  "Tragedy": {
    "id": "35686187",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Tragedy",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When a face-up Attack Position monster(s) your opponent controls is changed to face-up Defense Position: Destroy all Defense Position monsters your opponent controls.",
    "category": ["Destroy Monster"]
  },
  "Fruits of Kozaky's Studies": {
    "id": "49998907",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Fruits of Kozaky's Studies",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Look at the top 3 cards of your Deck and return those cards to the top of the Deck in any order.",
    "category": ["Send to Deck"]
  },
  "Mind Haxorz": {
    "id": "75392615",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Mind Haxorz",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Pay 500 Life Points: Look at your opponent's hand and all Set cards they control.",
    "category": ["Control"]
  },
  "Fuh-Rin-Ka-Zan": {
    "id": "01781310",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Fuh-Rin-Ka-Zan",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If there are WIND, WATER, FIRE and EARTH monster(s) on the field: Apply 1 of these effects. ● Destroy all monsters your opponent controls. ● Destroy all Spells and Traps your opponent controls. ● Discard 2 random cards from your opponent's hand. ● Draw 2 cards.",
    "category": ["Destroy Monster", "Destroy Hand", "Destroy S/T", "Draw"]
  },
  "Pikeru's Circle of Enchantment": {
    "id": "74270067",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Pikeru's Circle of Enchantment",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "You take no effect damage, until the end of this turn.",
    "category": ["Control"]
  },
  "Spell Purification": {
    "id": "01669772",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Spell Purification",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Discard 1 card; destroy all Continuous Spells on the field.",
    "category": ["Destroy S/T"]
  },
  "Covering Fire": {
    "id": "74458486",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Covering Fire",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "During the Damage Step, if an opponent's monster attacks your monster: Target 1 other face-up monster you control; your attacked monster gains ATK equal to that target's ATK, during that Damage Step only.",
    "category": ["Change ATK/DEF"]
  },
  "Cross Counter": {
    "id": "37083210",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Cross Counter",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Before damage calculation, if an opponent's monster attacks a Defense Position monster and the DEF of the Defense Position monster is higher than the ATK of the attacking monster: The battle damage inflicted to your opponent by that attack is doubled. Destroy that attacking monster after damage calculation.",
    "category": ["Damage LP", "Destroy Monster"]
  },
  "Penalty Game!": {
    "id": "00967928",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Penalty Game!",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If your opponent has 4 cards in their hand: Activate 1 of these effects. ● Your opponent cannot draw cards during their next Draw Phase. ● Your opponent cannot activate Spells and Traps this turn.",
    "category": ["Control"]
  },
  "Threatening Roar": {
    "id": "36361633",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Threatening Roar",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Your opponent cannot declare an attack this turn.",
    "category": ["Battle Protection"]
  },
  "Phoenix Wing Wind Blast": {
    "id": "63356631",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Phoenix Wing Wind Blast",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Descarta 1 carta de tu mano. Devuelve 1 carta en el Campo de tu adversario a la parte superior del Deck de su propietario.",
    "category": ["Send to Deck"]
  },
  "Good Goblin Housekeeping": {
    "id": "09744376",
    "card-type": "normal-trap",
    "banlist": "Semi-limited",
    "Genesys": 0,
    "name": "Good Goblin Housekeeping",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Roba un número de cartas de tu Deck igual al número de cartas <b>Good Goblin Housekeeping</b> en tu Cementerio +1, selecciona 1 carta de tu mano, y devuelvela al fondo de tu Deck.",
    "category": ["Draw", "Send to Deck"]
  },
  "Beast Soul Swap": {
    "id": "35149085",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Beast Soul Swap",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 Beast monster you control; return it to the hand, and if you do, Special Summon 1 Beast monster from your hand with the same Level as the monster that was returned to the hand.",
    "category": ["Send to Hand", "Special Summon"]
  },
  "Assault on GHQ": {
    "id": "62633180",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Assault on GHQ",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 monster you control; destroy it, and if you do, send 2 cards from the top of your opponent's Deck to the Graveyard.",
    "category": ["Destroy Monster", "Destroy Deck"]
  },
  "D.D. Dynamite": {
    "id": "08628798",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "D.D. Dynamite",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Inflict 300 damage to your opponent for each of your opponent's banished cards.",
    "category": ["Damage LP"]
  },
  "Deck Devastation Virus": {
    "id": "35027493",
    "card-type": "normal-trap",
    "banlist": "Limited",
    "Genesys": 0,
    "name": "Deck Devastation Virus",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Sacrifica 1 monstruo de OSCURIDAD con un ATK de 2000 o más en tu Campo. Comprueba todos los monstruos en el Campo de tu adversario, la mano de tu adversario, y todas las cartas que robe durante los tres próximos turnos de tu adversario, y destruye todos los monstruos con un ATK de 1500 o menos.",
    "category": ["Destroy Monster", "Destroy Hand"]
  },
  "Elemental Burst": {
    "id": "61411502",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Elemental Burst",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Tribute 1 WIND, WATER, FIRE, and EARTH monsters; Destroy all cards your opponent controls.",
    "category": ["Destroy Monster", "Destroy S/T"]
  },
  "Forced Ceasefire": {
    "id": "97806240",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Forced Ceasefire",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Discard 1 card; Traps cannot be activated, until the end of this turn.",
    "category": ["Control"]
  },
  "Hero Signal": {
    "id": "22020907",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Hero Signal",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When a monster you control is destroyed by battle and sent to the Graveyard: Special Summon 1 Level 4 or lower \"Elemental HERO\" monster from your hand or Deck.",
    "category": ["Special Summon"]
  },
  "Pikeru's Second Sight": {
    "id": "58015506",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Pikeru's Second Sight",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Look at all cards your opponent draws until the end of their 2nd turn after this card's activation.",
    "category": ["Control"]
  },
  "Minefield Eruption": {
    "id": "85519211",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Minefield Eruption",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Inflict 1000 damage to your opponent for each face-up \"Mine Golem\" you control, then destroy all face-up \"Mine Golem\"(s) you control.",
    "category": ["Damage LP"]
  },
  "Kozaky's Self-Destruct Button": {
    "id": "21908319",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Kozaky's Self-Destruct Button",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "If this Set card is destroyed: Inflict 1000 damage to the player who destroyed this card.",
    "category": ["Damage LP"]
  },
  "Mispolymerization": {
    "id": "58392024",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Mispolymerization",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When a Fusion Monster(s) is Special Summoned: Return all face-up Fusion Monsters on the field to the Fusion Deck.",
    "category": ["Fusion", "Send to Deck"]
  },
  "Level Conversion Lab": {
    "id": "84397023",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Level Conversion Lab",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Reveal 1 monster in your hand, then roll a six-sided die. If the result is 1, send that monster to the Graveyard. If the result is 2-6, the Level of that monster becomes equal to the result, until the end of this turn.",
    "category": ["Gamble", "Control"]
  },
  "Rock Bombardment": {
    "id": "20781762",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Rock Bombardment",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Send 1 Rock monster from your Deck to the Graveyard; inflict 500 damage to your opponent.",
    "category": ["Send to Graveyard", "Damage LP"]
  },
  "Grave Lure": {
    "id": "57270476",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Grave Lure",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Turn the top card of your opponent's Deck face-up, then your opponent shuffles their Deck. When your opponent draws that face-up card, send it to the Graveyard.",
    "category": ["Send to Deck", "Destroy Hand"]
  },
  "Token Feastevil": {
    "id": "83675475",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Token Feastevil",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When a Token(s) is Special Summoned: Destroy as many Tokens on the field as possible, and if you do, inflict 300 damage to your opponent for each Token destroyed.",
    "category": ["Destroy Monster", "Damage LP", "Token"]
  },
  "White Hole": {
    "id": "43487744",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "White Hole",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When your opponent activates \"Dark Hole\": Monsters you control cannot be destroyed by that \"Dark Hole's\" effect.",
    "category": ["Control"]
  },
  "Call of the Grave": {
    "id": "16970158",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Call of the Grave",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When your opponent activates \"Monster Reborn\": Negate its effect.",
    "category": ["Negate Effect"]
  },
  "Anti Raigeki": {
    "id": "42364257",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Anti Raigeki",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When your opponent activates \"Raigeki\": Negate its effect, and if you do, destroy all monsters your opponent controls.",
    "category": ["Destroy Monster", "Negate Effect"]
  },
  "Magical Thorn": {
    "id": "53119267",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Magical Thorn",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Each time a card(s) is discarded from your opponent's hand to their Graveyard, inflict 500 damage to them for each.",
    "category": ["Damage LP"]
  },
  "Return from the Different Dimension": {
    "id": "27174286",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Return from the Different Dimension",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Pay half your Life Points; Special Summon as many of your banished monsters as possible. During the End Phase, banish all monsters on the field that were Special Summoned by this effect.",
    "category": ["Special Summon"]
  },
  "Reinforcements": {
    "id": "17814387",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Reinforcements",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 face-up monster on the field; it gains 500 ATK, until the end of this turn.",
    "category": ["Change ATK/DEF"]
  },
  "Waboku": {
    "id": "12607053",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Waboku",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "You take no battle damage this turn, also monsters you control cannot be destroyed by battle this turn.",
    "category": ["Battle Protection"]
  },
  "Reverse Trap": {
    "id": "77622396",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Reverse Trap",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "All effects that add or subtract ATK or DEF are reversed (Additions now subtract, and subtractions now add, instead. Multiplications and divisions, including halving or doubling, are not affected.), until the end of this turn.",
    "category": ["Change ATK/DEF"]
  },
  "Castle Walls": {
    "id": "44209392",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Castle Walls",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 face-up monster on the field; it gains 500 DEF, until the end of this turn.",
    "category": ["Change ATK/DEF"]
  },
  "Just Desserts": {
    "id": "24068492",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Just Desserts",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Inflige 500 puntos de daño a los Life Points de tu adversario por cada monstruo que tu adversario tiene en el campo.",
    "category": ["Damage LP"]
  },
  "Gryphon Wing": {
    "id": "55608151",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Gryphon Wing",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When your opponent activates \"Harpie's Feather Duster\": Negate its effect, and if you do, destroy all Spells and Traps your opponent controls.",
    "category": ["Negate Effect", "Destroy S/T"]
  },
  "Metalmorph": {
    "id": "68540058",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Metalmorph",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 face-up monster on the field; equip this card to that target. It gains 300 ATK and DEF. If it attacks, it gains ATK equal to half the ATK of the attack target, during damage calculation only.",
    "category": ["Change ATK/DEF"]
  },
  "Acid Trap Hole": {
    "id": "41356845",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Acid Trap Hole",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Target 1 face-down Defense Position monster on the field; flip it face-up, then destroy it if its DEF is 2000 or less, or return it face-down if its DEF is more than 2000.",
    "category": ["Destroy Monster"]
  },
  "Skull Dice": {
    "id": "00126218",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Skull Dice",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Roll a six-sided dice. All monsters your opponent currently controls lose ATK and DEF equal to the result x 100, until the end of this turn.",
    "category": ["Gamble", "Change ATK/DEF"]
  },
  "Windstorm of Etaqua": {
    "id": "59744639",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Windstorm of Etaqua",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Change the battle positions of all face-up monsters your opponent controls.",
    "category": ["Position"]
  },
  "Widespread Ruin": {
    "id": "77754944",
    "card-type": "normal-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Widespread Ruin",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When an opponent's monster declares an attack: Destroy the Attack Position monster your opponent controls with the highest ATK (your choice, if tied).",
    "category": ["Destroy Monster"]
  }
};