const trapcounterDetailed = {
  "Solemn Judgment": {
    "id": "41420027",
    "card-type": "counter-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Solemn Judgment",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Paga la mitad de tus Life Points para negar 1 activación de una Carta Mágica o de Trampa o 1 Invocación Normal, de Volteo o Especial y destruir la carta.",
    "category": ["Negate Activation", "Destroy S/T", "Destroy Monster"]
  },
  "Magic Jammer": {
    "id": "77414722",
    "card-type": "counter-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Magic Jammer",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Descarta 1 carta de tu mano. Niega la activación de una Carta Mágica y destruirla.",
    "category": ["Negate Activation", "Destroy S/T"]
  },
  "Seven Tools of the Bandit": {
    "id": "03819470",
    "card-type": "counter-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Seven Tools of the Bandit",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When a Trap is activated: Pay 1000 Life Points; negate the activation, and if you do, destroy it.",
    "category": ["Negate Activation", "Destroy S/T"]
  },
  "Horn of Heaven": {
    "id": "98069388",
    "card-type": "counter-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Horn of Heaven",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When a monster(s) would be Summoned: Tribute 1 monster; negate the Summon, and if you do, destroy that monster(s).",
    "category": ["Destroy Monster"]
  },
  "Magic Drain": {
    "id": "59344077",
    "card-type": "counter-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Magic Drain",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When your opponent activates a Spell: They can discard 1 Spell to negate this card's effect, otherwise negate the activation of that Spell, and if you do, destroy it.",
    "category": ["Destroy S/T", "Negate Activation"]
  },
  "Riryoku Field": {
    "id": "70344351",
    "card-type": "counter-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Riryoku Field",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When a Spell that targets exactly 1 monster on the field (and no other cards) is activated: Negate the activation, and if you do, destroy it.",
    "category": ["Negate Activation", "Destroy S/T"]
  },
  "Tutan Mask": {
    "id": "03149764",
    "card-type": "counter-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Tutan Mask",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When a Spell or Trap is activated that targets exactly 1 Zombie monster on the field (and no other cards): Negate the activation, and if you do, destroy it.",
    "category": ["Negate Activation", "Destroy S/T"]
  },
  "Curse of Royal": {
    "id": "02926176",
    "card-type": "counter-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Curse of Royal",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When a Spell or Trap is activated that would destroy exactly 1 Spell or Trap on the field (and no other cards): Negate the activation, and if you do it, destroy it.",
    "category": ["Negate Activation", "Destroy S/T"]
  },
  "Barrel Behind the Door": {
    "id": "78783370",
    "card-type": "counter-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Barrel Behind the Door",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When an effect that would inflict damage to you is activated: Your opponent takes the damage instead.",
    "category": ["Damage LP"]
  },
  "Trap of Board Eraser": {
    "id": "03055837",
    "card-type": "counter-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Trap of Board Eraser",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When an effect that would inflict damage to you is activated, if your opponent has at least 1 card in their hand: Reduce that damage to 0, and if you do, your opponent discards 1 card.",
    "category": ["Destroy Hand"]
  },
  "Spell Shield Type-8": {
    "id": "38275183",
    "card-type": "counter-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Spell Shield Type-8",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Activa 1 de estos efectos.<br>● Cuando es activada una Carta Mágica que selecciona exactamente a 1 monstruo en el Campo: niega la activación y, si lo haces, destruye la carta.<br>● Cuando es activada una Carta Mágica: manda al Cementerio, desde tu mano, 1 Carta Mágica; niega la activación y, si lo haces, destruye la carta.",
    "category": ["Negate Activation", "Destroy S/T"]
  },
  "Anti-Spell": {
    "id": "53112492",
    "card-type": "counter-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Anti-Spell",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When a Spell is activated: Remove 2 Spell Counters from your field; negate the activation, and if you do, destroy it.",
    "category": ["Spell Counter", "Negate Activation", "Destroy S/T"]
  },
  "Spell Vanishing": {
    "id": "29735721",
    "card-type": "counter-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Spell Vanishing",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When a Spell is activated: Discard 2 cards; negate the activation, and if you do, destroy it, then your opponent reveals their hand and Deck, send all cards with that Spell's name to the Graveyard.",
    "category": ["Negate Activation", "Control", "Destroy Hand"]
  },
  "Judgment of Anubis": {
    "id": "55256016",
    "card-type": "counter-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Judgment of Anubis",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When your opponent activates a Spell that would destroy a Spell(s) or Trap(s) on the field: Discard 1 card; negate the activation, and if you do, destroy it, then you can destroy 1 face-up monster your opponent controls, and if you do that, inflict damage to your opponent equal to the destroyed monster's ATK on the field.",
    "category": ["Destroy S/T", "Negate Activation", "Destroy Monster", "Damage LP"]
  },
  "Cursed Seal of the Forbidden Spell": {
    "id": "58851034",
    "card-type": "counter-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Cursed Seal of the Forbidden Spell",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When a Spell is activated: Discard 1 Spell; negate the activation, and if you do, destroy it, and if you do that, your opponent cannot activate Spells with that name for the rest of the Duel.",
    "category": ["Negate Activation", "Destroy S/T", "Control"]
  },
  "Trap Jammer": {
    "id": "19252988",
    "card-type": "counter-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Trap Jammer",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "Solo puedes activar esta carta cuando tu adversario activa una Carta de Trampa durante la Battle Phase. Niega la activación de la Carta de Trampa y destruyela.",
    "category": ["Negate Activation", "Destroy S/T"]
  },
  "Armor Break": {
    "id": "79649195",
    "card-type": "counter-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Armor Break",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When an Equip Spell is activated: Negate the activation, and if you do, destroy it.",
    "category": ["Negate Activation", "Destroy S/T"]
  },
  "Divine Wrath": {
    "id": "49010598",
    "card-type": "counter-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Divine Wrath",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When a monster effect is activated: Discard 1 card; negate the activation, and if you do, destroy that monster.",
    "category": ["Negate Activation", "Destroy Monster"]
  },
  "Spell-Stopping Statute": {
    "id": "10069180",
    "card-type": "counter-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Spell-Stopping Statute",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When your opponent activates a Continuous Spell: Negate the activation, and if you do, destroy it.",
    "category": ["Negate Activation", "Destroy S/T"]
  },
  "Royal Surrender": {
    "id": "56058888",
    "card-type": "counter-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Royal Surrender",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When your opponent activates a Continuous Trap: Negate the activation, and if you do, destroy it.",
    "category": ["Negate Activation", "Destroy S/T"]
  },
  "Negate Attack": {
    "id": "14315573",
    "card-type": "counter-trap",
    "banlist": "Unlimited",
    "Genesys": 0,
    "name": "Negate Attack",
    "atk": null,
    "def": null,
    "level": null,
    "type": null,
    "attribute": null,
    "effect": "When an opponent's monster declares an attack: Target the attacking monster; negate the attack, then end the Battle Phase.",
    "category": ["Battle Protection"]
  }
};